#!/bin/sh


#===============================================================================
# multicast yt streams
#===============================================================================


#===============================================================================
# script usage
#===============================================================================

usage () {
# if argument passed to function echo it
[ -z "${1}" ] || echo "! ${1}"
# display help
echo "\
$(basename "$0") -i url"
exit 2
}


#===============================================================================
# error messages
#===============================================================================

INVALID_OPT_ERR='Invalid option:'
REQ_ARG_ERR='requires an argument'
WRONG_ARGS_ERR='wrong number of arguments passed to script'


#===============================================================================
# check number of aruments passed to script
#===============================================================================

[ $# -gt 0 ] || usage "${WRONG_ARGS_ERR}"


#===============================================================================
# getopts check options passed to script
#===============================================================================

while getopts ':i:h' opt
do
  case ${opt} in
     i) infile="${OPTARG}";;
     h) usage;;
     \?) usage "${INVALID_OPT_ERR} ${OPTARG}" 1>&2;;
     :) usage "${INVALID_OPT_ERR} ${OPTARG} ${REQ_ARG_ERR}" 1>&2;;
  esac
done
shift $((OPTIND-1))


#===============================================================================
# url
#===============================================================================

# yt-dlp url
url=$(yt-dlp -f b -g --no-playlist "${infile}")

# check number of stream links
streamcount=$(echo "${url}" | wc -l)


#===============================================================================
# one stream containing audio and video
#===============================================================================

one_stream () {
ffmpeg \
-hide_banner \
-re \
-i "${url}" \
-c:a copy -c:v copy \
-tune zerolatency \
-f mpegts "udp://239.254.254.4:1234?pkt_size=1316"
}


#===============================================================================
# two streams containing audio and video
#===============================================================================

two_streams () {
video_url=$(echo "${url}" | awk 'BEGIN{ RS ="" ; FS ="\n" }{print $1}')
audio_url=$(echo "${url}" | awk 'BEGIN{ RS ="" ; FS ="\n" }{print $2}')

# ffmpeg join audio and video and stream
ffmpeg \
-hide_banner \
-re \
-i "${video_url}" \
-i "${audio_url}" \
-c:a copy -c:v copy \
-tune zerolatency \
-map 0:0 -map 1:0 \
-f mpegts "udp://239.254.254.4:1234?pkt_size=1316"
}


#===============================================================================
# case statement check for number of streams
#===============================================================================

case "${streamcount}" in
    1) one_stream;; # single stream
    2) two_streams;; # audio and video stream
    *) usage;;
esac
