#!/bin/sh

# audio-silence add silent audio to a video clip

# script usage
usage()
{
  echo "$(basename "$0") -i infile.(mp4|mkv|mov|m4v) -c (m|s) -r (44100|48000)"
  exit 2
}

# error messages
HOME_ERR='HOME directory not set or null'
NOTFILE_ERR='not a file'
INVALID_OPT_ERR='Invalid option:'
REQ_ARG_ERR='requires an argument'
WRONG_ARGS_ERR='wrong number of arguments passed to script'
ARGS_ERR='incorrect arguments passed to script'
FILE_EXT_ERR='has the wrong file extension'
NOT_MEDIA_FILE_ERR='is not a media file'

# number of args passed to script, needs to be stored before getopts
if [ $# -gt 0 ]; then
    first_arg="$1"
    third_arg="$3"
    fifth_arg="$5"
    args="$#"
else
   { echo "${WRONG_ARGS_ERR}" && usage; }
fi

# getopts and check if input a file
while getopts ':i:c:r:h' opt
do
  case ${opt} in
     i) infile="${OPTARG}"
	[ -f "${infile}" ] || { echo "${infile} ${NOTFILE_ERR}" && usage; };;
     c) channel="${OPTARG}";;
     r) rate="${OPTARG}";;
     h) usage;;
     \?) echo "${INVALID_OPT_ERR} ${OPTARG}" 1>&2 && usage;;
     :) echo "${INVALID_OPT_ERR} ${OPTARG} ${REQ_ARG_ERR}" 1>&2 && usage;;
  esac
done
shift $((OPTIND-1))

# variables
mono='mono'
stereo='stereo'

# check arguments
if [ "${args}" -eq 6 ]; then
   {
   [ "${first_arg}" = '-i' ] && \
   [ -f "${infile}" ] && \
   [ "${third_arg}" = '-c' ] && \
   [ "${channel}" = "${mono}" ] || [ "${channel}" = "${stereo}" ] && \
   [ "${fifth_arg}" = '-r' ] && \
   [ "${rate}" = '44100' ] || [ "${rate}" = '48000' ]
   } || { echo "${ARGS_ERR}" && usage; }
else
   { echo "${WRONG_ARGS_ERR}" && usage; }
fi

# infile, infile name and extension
infile_nopath="${infile##*/}"
infile_name="${infile_nopath%.*}"
infile_ext="${infile##*.}"

# file extension regular expressions for case statement
mp4='[Mm][Pp]4'
mkv='[Mm][Kk][Vv]'
mov='[Mm][[Oo][Vv]'
m4v='[Mm]4[Vv]'

# check the file extension before passing to the file command
case "${infile_ext}" in
    ${mp4}|${mkv}|${mov}|${m4v});;
    *) { echo "${infile} ${FILE_EXT_ERR}" && usage; };;
esac

# outfile file recording destination
videofile="${HOME:?${HOME_ERR}}/Desktop/${infile_name}-silence-$(date +"%Y-%m-%d-%H-%M-%S").mp4"

# file command check input file mime type
filetype="$(file --mime-type -b "${infile}")"

# video mimetypes
mov_mime='video/quicktime'
mkv_mime='video/x-matroska'
mp4_mime='video/mp4'
m4v_mime='video/x-m4v'

# check the files mime type is a video
case "${filetype}" in
    ${mov_mime}|${mkv_mime}|${mp4_mime}|${m4v_mime});;
    *) { echo "${infile} ${NOT_MEDIA_FILE_ERR}" && usage; };;
esac

# video function
video_silence () {
  ffmpeg \
  -hide_banner \
  -stats -v panic \
  -f lavfi \
  -i anullsrc=channel_layout="${channel}":sample_rate="${rate}" \
  -i "${infile}" \
  -shortest -c:v copy -c:a aac \
  -movflags +faststart -f mp4 \
  "${videofile}"
}

# video and audio function
video_audio_silence () {
  ffmpeg \
  -hide_banner \
  -stats -v panic \
  -f lavfi \
  -i anullsrc=channel_layout="${channel}":sample_rate="${rate}" \
  -i "${infile}" \
  -shortest -c:v copy -c:a aac \
  -map 0:a -map 1:v \
  -movflags +faststart -f mp4 \
  "${videofile}"
}

# check if video has an audio track
audio_check="$(ffprobe -i "${infile}" -show_streams -select_streams a -loglevel error)"

# check if audio_check is null which means the video doesnt have an audio track
if [ -z "${audio_check}" ]; then
   video_silence "${infile}" # fade video track
else
   video_audio_silence "${infile}" # fade video and audio track
fi
