#!/bin/sh

# combine video and audio clip

# script usage
script_usage=$(printf "%s\n%s\n" "$(basename "$0") -v video.(mp4|mov|mkv) -a audio.(wav|m4a)")

# video file destination
videofile="$HOME/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mp4"

# ffmpeg record function
record () {
    ffmpeg \
    -hide_banner \
    -stats -v panic \
    -i "$video" \
    -i "$audio" \
    -c:a aac \
    -c:v copy \
    -map 0:0 -map 1:0 \
    -movflags +faststart \
    -f mp4 \
    "$videofile"
}

# check arguments
if [ $# -eq 4 ]; then
   # group commands
   {
   [ "$1" = '-v' ] && \
   [ -f "$2" ] && \
   printf "%s\n" "$2" | grep -Eo '.(mov|mp4|mkv)$' 1>/dev/null && \
   [ "$3" = '-a' ] && \
   [ -f "$4" ] && \
   printf "%s\n" "$4" | grep -Eo '.(wav|m4a)$' 1>/dev/null
   } || { printf "%s\n" "$script_usage" && exit; }
   # run record function to combine video and audio into a video file
   # set variables
   video="$2"
   audio="$4"
   record "$video" "$audio"
else
   { printf "%s\n" "$script_usage" && exit; }
fi
