#!/bin/sh

# convert video at 30fps to dnxhd and audio to pcm

# script usage
usage()
{
# if argument passed to function echo it
[ -z "${1}" ] || echo "! ${1}"
# display help
echo "\
# convert video to dnxhd and audio to pcm

$(basename "$0") -i infile.(mp4|mkv|mov|m4v|webm) -o outfile.mov
-i infile.(mp4|mkv|mov|m4v|webm)
-o outfile.mov :optional agument # if option not provided defaults to infile-name-dnxhd-date-time"
exit 2
}

# error messages
NOTFILE_ERR='not a file'
INVALID_OPT_ERR='Invalid option:'
REQ_ARG_ERR='requires an argument'
WRONG_ARGS_ERR='wrong number of arguments passed to script'
NOT_MEDIA_FILE_ERR='is not a media file'

# if script is run arguments pass and check the options with getopts,
# else display script usage and exit
[ $# -gt 0 ] || usage "${WRONG_ARGS_ERR}"

# getopts check and validate options
while getopts ':i:o:h' opt
do
  case ${opt} in
     i) infile="${OPTARG}"
	[ -f "${infile}" ] || usage "${infile} ${NOTFILE_ERR}";;
     o) outfile="${OPTARG}";;
     h) usage;;
     \?) usage "${INVALID_OPT_ERR} ${OPTARG}" 1>&2;;
     :) usage "${INVALID_OPT_ERR} ${OPTARG} ${REQ_ARG_ERR}" 1>&2;;
  esac
done
shift $((OPTIND-1))

# variables
infile_nopath="${infile##*/}"
infile_name="${infile_nopath%.*}"

# infile file extension
infile_ext="${infile##*.}"

# defaults for variables if not defined
outfile_default="${infile_name}-dnxhd.mov"

# file command check input file mime type
filetype="$(file --mime-type -b "${infile}")"

# audio and video mimetypes
mov_mime='video/quicktime'
mkv_mime='video/x-matroska'
mp4_mime='video/mp4'
m4v_mime='video/x-m4v'
webm_mime='video/webm'

# dnxhd-pcm function
dnx () {
    ffmpeg \
    -hide_banner \
    -stats -v panic \
    -i "${infile}" \
    -c:v dnxhd \
    -c:a pcm_s16le \
    -s 1920x1080 \
    -r 30000/1001 \
    -b:v 145M \
    -pix_fmt yuv422p \
    -f mov \
    "${outfile:=${outfile_default}}"
}

# check the files mime type
case "${filetype}" in
    ${mov_mime}|${mkv_mime}|${mp4_mime}|${m4v_mime}|${webm_mime}) dnx "${infile}";;
    *) usage "${infile} ${NOT_MEDIA_FILE_ERR}";;
esac
