#!/bin/sh

# ffplay ebu meter

# script usage
script_usage="$(basename "$0") -i infile.(mp4|mkv|mov|m4v|aac|m4a|wav|mp3)"

# check arguments passed to script
if [ $# -eq 2 ]; then
   {
   [ "$1" = '-i' ] && \
   [ -f "$2" ]
   } || { echo "$script_usage" && exit; }
else
   { echo "$script_usage" && exit; }
fi

# infile and file extension
infile="$2"
infile_ext="${infile##*.}"

# file command check input file mime type
filetype="$(file --mime-type -b "$infile")"

# audio and video mimetypes
mov_mime='video/quicktime'
mkv_mime='video/x-matroska'
mp4_mime='video/mp4'
m4v_mime='video/x-m4v'
wav_mime='audio/x-wav'
audio_mime='audio/mpeg'
aac_mime='audio/x-hx-aac-adts'

# check the files mime type
case "$filetype" in
    ${mov_mime}|${mkv_mime}|${mp4_mime}|${m4v_mime}| \
    ${wav_mime}|${audio_mime}|${aac_mime});;
    *) { echo "$script_usage" && exit; };;
esac

# file extension regular expressions for case statement
mp4='[Mm][Pp]4'
mkv='[Mm][Kk][Vv]'
mov='[Mm][[Oo][Vv]'
m4v='[Mm]4[Vv]'
aac='[Aa][Aa][Cc]'
m4a='[Mm]4[Aa]'
wav='[Ww][Aa][Vv]'
mp3='[Mm][Pp]3'

# ebu function
ebu () {
    ffplay -hide_banner \
    -f lavfi -i \
    "amovie=${infile},
    ebur128=video=1:
    meter=18:
    dualmono=true:
    target=-16:
    size=1280x720 [out0][out1]"
}

# run the audio or video function based on the file extension
case "$infile_ext" in
    ${mp4}|${mkv}|${mov}|${m4v}| \
    ${aac}|${m4a}|${wav}|${mp3}) ebu "$infile";;
    *) { echo "$script_usage" && exit; };;
esac
