#!/bin/sh

# fade video and audio in and out

# script usage
script_usage=$(printf "%s\n%s\n" "$(basename "$0") -i video.(mp4|mov|mkv)")

# video file destination
videofile="$HOME/Desktop/video-$(date +"%Y-%m-%d-%H-%M-%S").mp4"

# ffmpeg record function
record () {
    printf "%s\n" "+ Getting video duration" && \
    video_dur=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$video" | cut -d\. -f1)
    vid_offset=$(printf "%s\n" "${video_dur}-1" | bc -l)
    printf "%s\n" "+ Converting video" && \
    ffmpeg \
    -hide_banner \
    -stats -v panic \
    -i "$video" \
    -filter_complex \
    " [0:a] afade=t=in:st=0:d=1,afade=t=out:st='$vid_offset':d=1[fa]; \
      [0:v] fade=t=in:st=0:d=1,fade=t=out:st='$vid_offset':d=1[fv]
    " \
    -c:a aac \
    -c:v libx264 -preset fast \
    -profile:v high \
    -crf 18 -coder 1 \
    -pix_fmt yuv420p \
    -map "[fv]" -map "[fa]" \
    -movflags +faststart \
    -f mp4 \
    "$videofile"
}

# check arguments
if [ $# -eq 2 ]; then
   # group commands
   {
   [ "$1" = '-i' ] && \
   [ -f "$2" ] && \
   printf "%s\n" "$2" | grep -Eo '.(mov|mp4|mkv)$' 1>/dev/null
   } || { printf "%s\n" "$script_usage" && exit; }
   # run record function to combine video and audio into a video file
   # set variables
   video="$2"
   record "$video"
else
   { printf "%s\n" "$script_usage" && exit; }
fi
