#!/bin/sh

# ffmpeg loudnorm

# script usage
script_usage="$(basename "$0") -i infile.(mkv|mp4|mov|m4v|m4a|aac|wav|mp3)"

# check arguments passed to script
if [ $# -eq 2 ]; then
   # group commands
   {
   [ "$1" = '-i' ] && \
   [ -f "$2" ]
   } || { echo "$script_usage" && exit; }
else
   { echo "$script_usage" && exit; }
fi

# infile and file extension
infile="$2" 
infile_ext="${infile##*.}"

# file extension regular expressions for case statement
mp4='[Mm][Pp]4'
mkv='[Mm][Kk][Vv]'
mov='[Mm][[Oo][Vv]'
m4v='[Mm]4[Vv]'
aac='[Aa][Aa][Cc]'
m4a='[Mm]4[Aa]'
wav='[Ww][Aa][Vv]'
mp3='[Mm][Pp]3'

# ffmpeg loudnorm get stats from file
normalize () {
    ffmpeg \
    -hide_banner \
    -i "$infile" \
    -af "loudnorm=I=-16:dual_mono=true:TP=-1.5:LRA=11:print_format=summary" \
    -f null -
}

# run the audio or video function based on the file extension
case "$infile_ext" in
    ${mp4}|${mkv}|${mov}|${m4v}| \
    ${aac}|${m4a}|${wav}|${mp3}) normalize "$infile";;
    *) { echo "$script_usage" && exit; };;
esac
