#!/bin/sh

# script usage
script_usage=$(printf "%s\n%s\n" "$(basename "$0") -i audio.wav")

# video file destination
outfile="$HOME/Desktop/outfile-$(date +"%Y-%m-%d-%H-%M-%S").wav"

# check arguments
if [ $# -eq 2 ]; then
   # group commands
   {
   [ "$1" = '-i' ] && \
   [ -f "$2" ] && \
   printf "%s\n" "$2" | grep -Eo '.(wav)$' 1>/dev/null
   } #|| { printf "%s\n" "$script_usage" && exit; }
   # run record function to combine video and audio into a video file
   # set variables
   infile="$2"
   #echo "$normalize" "$infile"
else
   { printf "%s\n" "$script_usage" && exit; }
fi

# print analyzing file
printf "%s\n" '+ analyzing file'

normalize=$(ffmpeg \
-hide_banner \
-i "$infile" \
-af "loudnorm=I=-16:dual_mono=true:TP=-1.5:LRA=11:print_format=json" \
-f null - 2>&1 | tail -n 12)

measured_I=$(printf "%s\n" "$normalize" | awk -F'"' '/input_i/ {print $4}')
measured_TP=$(printf "%s\n" "$normalize" | awk -F'"' '/input_tp/ {print $4}')
measured_LRA=$(printf "%s\n" "$normalize" | awk -F'"' '/input_lra/ {print $4}')
measured_thresh=$(printf "%s\n" "$normalize" | awk -F'"' '/input_thresh/ {print $4}')
offset=$(printf "%s\n" "$normalize" | awk -F'"' '/target_offset/ {print $4}')

printf "%s\n" "- measured_I=${measured_I}"
printf "%s\n" "- measured_TP=${measured_TP}"
printf "%s\n" "- measured_LRA=${measured_LRA}"
printf "%s\n" "- measured_thresh=${measured_thresh}"
printf "%s\n" "- offset=${offset}"

ffmpeg \
-hide_banner \
-i "$infile" \
-filter_complex \
"loudnorm=I=-16:
TP=-1.5:
LRA=11:
measured_I=${measured_I}:
measured_LRA=${measured_LRA}:
measured_TP=${measured_TP}:
measured_thresh=${measured_thresh}:
offset=${offset}:
linear=true:
print_format=summary [audio]" \
-map "[audio]" \
-ar 44.1k "$outfile"
