#!/bin/sh

# add subtitles to a video file

# script usage
script_usage="$(basename "$0") -v video.(mp4|mov|mkv|m4v) -s subtitle.srt"

# error messages
HOME_ERR='HOME directory not set or null'

# check arguments
if [ $# -eq 4 ]; then
   {
   [ "$1" = '-v' ] && \
   [ -f "$2" ] && \
   [ "$3" = '-s' ] && \
   [ -f "$4" ]
   } || { echo "$script_usage" && exit; }
else
   { echo "$script_usage" && exit; }
fi

# infile, infile name and extension
video="$2"
subs="$4"
subs_ext="${subs##*.}"
video_nopath="${video##*/}"
video_name="${video_nopath%.*}"
video_ext="${video##*.}"

# file command check input file mime type
video_filetype="$(file --mime-type -b $video)"
subs_filetype="$(file --mime-type -b $subs)"

# video mimetypes
mov_mime='video/quicktime'
mkv_mime='video/x-matroska'
mp4_mime='video/mp4'
m4v_mime='video/x-m4v'

# srt subtitles mime type
srt_mime='text/plain'

# check the video mime type
case "$video_filetype" in
    ${mov_mime}|${mkv_mime}|${mp4_mime}|${m4v_mime});;
    *) { echo "$script_usage" && exit; };;
esac

# check the subtitles mime type
case "$subs_filetype" in
    ${srt_mime});;
    *) { echo "$script_usage" && exit; };;
esac

# file extension regular expressions for case statement
mp4='[Mm][Pp]4'
mkv='[Mm][Kk][Vv]'
mov='[Mm][[Oo][Vv]'
m4v='[Mm]4[Vv]'

# outfile file recording destination
videofile="${HOME:?${HOME_ERR}}/Desktop/${video_name}-subs-$(date +"%Y-%m-%d-%H-%M-%S").mp4"

# audio is aac, copy audio stream
addsubs () {
    ffmpeg \
    -hide_banner \
    -stats -v panic \
    -i "$video" \
    -f srt \
    -i "$subs" \
    -c:a copy \
    -c:v copy \
    -c:s mov_text -metadata:s:s:0 \
    language=eng \
    -movflags +faststart \
    -f mp4 \
    "$videofile"
}

# check video file extension
case "$video_ext" in
    ${mp4}|${mkv}|${mov}|${m4v});;
    *) { echo "$script_usage" && exit; };;
esac

# run the ffmpeg function based on the audio file extension
case "$subs_ext" in
    srt) addsubs "$video" "$subs";;
    *) { echo "$script_usage" && exit; };;
esac
