#!/bin/sh

# create a waveform from an audio or video file and save as a png

# script usage
script_usage="$(basename "$0") -i infile.(mp4|mkv|mov|m4v|wav|aac|m4a|mp3)"

# error messages
HOME_ERR='HOME directory not set or null'

# check arguments
if [ $# -eq 2 ]; then
   {
   [ "$1" = '-i' ] && \
   [ -f "$2" ]
   } || { echo "$script_usage" && exit; }
else
   { echo "$script_usage" && exit; }
fi

# variables
infile="$2"
infile_nopath="${infile##*/}"
infile_name="${infile_nopath%.*}"

# save file extension as a lowercase variable for the case statement
infile_ext="${infile##*.}"

# file extension regular expressions for case statement
mp4='[Mm][Pp]4'
mkv='[Mm][Kk][Vv]'
mov='[Mm][[Oo][Vv]'
m4v='[Mm]4[Vv]'
aac='[Aa][Aa][Cc]'
m4a='[Mm]4[Aa]'
wav='[Ww][Aa][Vv]'
mp3='[Mm][Pp]3'

# outfile file recording destination
outfile="${HOME:?${HOME_ERR}}/Desktop/${infile_name}-waveform-$(date +"%Y-%m-%d-%H-%M-%S").png"

# ffmpeg record function
wform () {
    ffmpeg \
    -hide_banner \
    -stats -v panic \
    -i "$infile" \
    -filter_complex "aformat=channel_layouts=mono,showwavespic=s=1000x200" \
    -frames:v 1 "$outfile"
}

case "$infile_ext" in
    ${mp4}|${mkv}|${mov}|${m4v}| \
    ${aac}|${m4a}|${wav}|${mp3}) wform "$infile";;
    *) { echo "$script_usage" && exit; };;
esac
