#!/bin/sh

# create a waveform from an audio or video file and save as a png

# script usage
script_usage=$(printf "%s\n%s\n" "$(basename "$0") -i infile.(mp4|mkv|mov|m4v|wav|aac|m4a|mp3)")

# check arguments
if [ $# -eq 2 ]; then
   {
   [ "$1" = '-i' ] && \
   [ -f "$2" ]
   } || { printf "%s\n" "$script_usage" && exit; }
else
   { printf "%s\n" "$script_usage" && exit; }
fi

# variables
infile="$2"
infile_nopath="${infile##*/}"
infile_name="${infile_nopath%.*}"
infile_ext="${infile##*.}"

# outfile file recording destination
outfile="$HOME/Desktop/${infile_name}-waveform-$(date +"%Y-%m-%d-%H-%M-%S").png"

# ffmpeg record function
wform () {
    ffmpeg \
    -hide_banner \
    -stats -v panic \
    -i "$infile" \
    -filter_complex "aformat=channel_layouts=mono,showwavespic=s=1000x200" \
    -frames:v 1 "$outfile"
}


# run the ffmpeg function based on the file extension
case "$infile_ext" in
  mp4|mkv|mov|m4v|wav|aac|m4a|mp3) wform "$infile";;
  *) { printf "%s\n" "$script_usage" && exit; };;
esac
