#+STARTUP: content
#+OPTIONS: num:nil author nil

* i3wm cheat sheet

** floating toggle

$mod+Control+space

** start terminal

$mod+Return

**  kill focused window

$mod+Shift+q 

** rofi (app launcher)

$mod+d

** enter fullscreen mode for the focused container

$mod+f

**  change focus

$mod+h focus left
$mod+j focus down
$mod+k focus up
$mod+l focus right

** move focused window

$mod+Shift+h move left
$mod+Shift+j move down
$mod+Shift+k move up
$mod+Shift+l move right

** split in horizontal orientation

$mod+c split h

** split in vertical orientation

$mod+v split v

**  enter fullscreen mode for the focused container

$mod+f fullscreen toggle

** change container layout (stacked, tabbed, toggle split)

$mod+s layout stacking
$mod+w layout tabbed
$mod+e layout toggle split

** toggle tiling / floating

$mod+Control+space floating toggle

** change focus between tiling / floating windows

$mod+space focus mode_toggle

** sticky window toggle

$mod+Shift+s sticky toggle

** focus the parent container

$mod+a focus parent

** next previous workspace

$mod+Shift+Tab workspace prev
$mod+Tab workspace next

** switch to workspace

$mod+1 workspace 1
$mod+2 workspace 2
$mod+3 workspace 3
$mod+4 workspace 4
$mod+5 workspace 5
$mod+6 workspace 6
$mod+7 workspace 7
$mod+8 workspace 8
$mod+9 workspace 9
$mod+0 workspace 10

** move focused container to workspace

$mod+Shift+1 move container to workspace 1
$mod+Shift+2 move container to workspace 2
$mod+Shift+3 move container to workspace 3
$mod+Shift+4 move container to workspace 4
$mod+Shift+5 move container to workspace 5
$mod+Shift+6 move container to workspace 6
$mod+Shift+7 move container to workspace 7
$mod+Shift+8 move container to workspace 8
$mod+Shift+9 move container to workspace 9
$mod+Shift+0 move container to workspace 10

** reload the configuration file

$mod+Shift+c reload

** restart i3 inplace (preserves your layout/session, can be used to upgrade i3)

$mod+Shift+r restart

** exit i3 (logs you out of your X session)

$mod+Shift+e

** resize

$mod+r

# Pressing left will shrink the window’s width.
# Pressing right will grow the window’s width.
# Pressing up will shrink the window’s height.
# Pressing down will grow the window’s height.

h resize shrink width 10 px or 10 ppt
j resize grow height 10 px or 10 ppt
k resize shrink height 10 px or 10 ppt
l resize grow width 10 px or 10 ppt

# same bindings, but for the arrow keys

Left resize shrink width 10 px or 10 ppt
Down resize grow height 10 px or 10 ppt
Up resize shrink height 10 px or 10 ppt
Right resize grow width 10 px or 10 ppt

# back to normal: Enter or Escape

Return mode "default"
Escape mode "default"

** move floating window to center

$mod+n
