#!/bin/bash

[[ $# -eq 1 ]] || [[ $# -eq 3 ]] || exit # check number of arguments passed to script
[[ "$1" =~ \.txt$ ]] && videourl=$(cat "$1") || videourl="$1" # first argument on command line or text file

# ffmpeg duration flags
tflag="$2"
duration="$3" 

# convert grep command to bash for case statement
# grep -Eo '(http|https)://[a-zA-Z0-9:0-9./?=_@%-]*\.(mkv|mp4|avi|flv)'

case "$videourl" in
	*.@(mp4|mkv|avi|flv))
		printf "%s\n" video file;;
	*) 
		printf "%s\n" wildcard;;
esac 
