#!/bin/sh

#===============================================================================
# upscale-libplacebo 
# upscale video with ffmpeg libplacebo gsl
#===============================================================================

# dependencies:
# ffmpeg

# download the SSimSuperRes.glsl and use the -f option to specify the path to the file
# wget https://gist.githubusercontent.com/igv/2364ffa6e81540f29cb7ab4c9bc05b6b/raw/15d93440d0a24fc4b8770070be6a9fa2af6f200b/SSimSuperRes.glsl

#===============================================================================
# script usage
#===============================================================================

usage () {
# if argument passed to function echo it
[ -z "${1}" ] || echo "! ${1}"
# display help
echo "\
$(basename "$0") -i input -o output)
-i input.(mp4|mov|mkv|m4v|webm)
-f path-to-gsl-shader
-v (0|1) 
-p p(1|7)
-c (0|30)
-o output.mp4 : optional argument"
exit 2
}


#===============================================================================
# error messages
#===============================================================================

INVALID_OPT_ERR='Invalid option:'
REQ_ARG_ERR='requires an argument'
WRONG_ARGS_ERR='wrong number of arguments passed to script'
NOT_MEDIA_FILE_ERR='is not a media file'


#===============================================================================
# check the number of arguments passed to the script
#===============================================================================

[ $# -gt 0 ] || usage "${WRONG_ARGS_ERR}"


#===============================================================================
# getopts check the options passed to the script
#===============================================================================

while getopts ':i:f:v:o:h' opt
do
  case ${opt} in
     i) input="${OPTARG}";;
     f) shader_path="${OPTARG}";;
     v) vulkan="${OPTARG}";;
     p) preset="${OPTARG}";;
     c) cq="${OPTARG}";;
     h) usage;;
     o) outfile="${OPTARG}";;
     \?) usage "${INVALID_OPT_ERR} ${OPTARG}" 1>&2;;
     :) usage "${INVALID_OPT_ERR} ${OPTARG} ${REQ_ARG_ERR}" 1>&2;;
  esac
done
shift $((OPTIND-1))


#===============================================================================
# variables
#===============================================================================

# input name
input_nopath="${input##*/}"
input_name="${input_nopath%.*}"


#===============================================================================
# default values
#===============================================================================

# output default file name
output_default="${input_name}-4k.mp4"

# vulkan default
vulkan_default=1

# preset default
preset_default=p7

# cq default
cq_default=16


#===============================================================================
# ffmpeg function
#===============================================================================

upscale () {
    ffmpeg \
    -hide_banner \
    -stats -v panic \
    -init_hw_device vulkan=vk:"${vulkan:=${vulkan_default}}" \
    -i "${input}" \
    -filter_hw_device vk \
    -vf "yadif=mode=send_frame,
    format=yuv420p,
    hwupload,
    libplacebo=w=-2:h=2160:
    upscaler=ewa_lanczos:
    custom_shader_path=${shader_path}:
    disable_builtin=1:
    deband=true:
    deband_iterations=4:
    deband_threshold=12:
    deband_radius=32:
    deband_grain=6.0:
    antiringing=0.8:
    tonemapping=mobius:
    gamut_mode=relative:
    contrast=1.1:
    saturation=1.1:
    contrast_recovery=0.0:
    contrast_smoothness=5.0:
    dithering=blue:
    dither_temporal=1:
    format=yuv420p,
    hwdownload,format=yuv420p" \
    -c:v hevc_nvenc \
    -preset "${preset:=${preset_default}}" \
    -tune hq \
    -rc vbr \
    -cq "${cq:=${cq_default}}" \
    -b:v 0 \
    -c:a copy \
    -pix_fmt yuv420p -movflags +faststart \
    "${outfile:=${output_default}}"
}

#===============================================================================
# run ffmpeg function
#===============================================================================

upscale
