#+STARTUP: content
* arch chroot fix

[[http://pckr.co.uk/arch-grub-mkconfig-lvmetad-failures-inside-chroot-install/]]

When I am installing Arch to logical volumes and attempt to use grub-mkconfig and grub-install from within my chroot environment, I encounter the warning messages:

/run/lvm/lvmetad.socket: connect failed: No such file or directory
WARNING: Failed to connect to lvmetad. Falling back to internal scanning.

The lvmetad service is responsible for the metadata cache for logical volumes. The metadata daemon has two main purposes: It improves performance of LVM commands and it allows udev to automatically activate logical volumes or entire volume groups as they become available to the system.

So to resolve this problem we can make /run available from the host to the chroot environment.

Drop out of your chroot environment:

exit (or control & D) 

#+begin_src sh
mkdir /mnt/hostrun 
mount --bind /run /mnt/hostrun 
arch-chroot /mnt /bin/bash 
mkdir /run/lvm 
mount --bind /hostrun/lvm /run/lvm
#+end_src

Alternatively you can disable lvmetad from /etc/lvm/lvm.conf and set use_lvmetad = 0
Then continue with your grub-mkconfig and grub-install commands.

umount /run/lvm before exiting the chroot.

#+begin_src sh
sudo umount /run/lvm
#+end_src
