#!/bin/bash

[[ $# -eq 0 ]] || exit 
read -erp "enter a path to a directory or m3u8 files: " DIR
[[ -d $DIR || -f $DIR ]] && find $DIR -maxdepth 1 -name '*.m3u' -type f \
| while read file
do 
for line in `cat "$file"`; do
	LINK=`echo "$line" | grep -Eo '(http|https|rtmp)://[a-zA-Z0-9:0-9./?=_@&%|()[:blank:],;-]*'`
 	[ $? -eq 0 ] && ffprobe -hide_banner "$LINK"
	[ $? -eq 0 ] && grep -B 1 "$LINK" "$file" | sed -e '/--/d' >> iptv.m3u
done
done && sed -i '1i #EXTM3U' iptv.m3u || echo no directory or file found