#!/bin/sh


#===============================================================================
# mux-local - stream a local video with srt, video must be h264/aac
#===============================================================================


#===============================================================================
# script usage
#===============================================================================

usage () {
# if argument passed to function echo it
[ -z "${1}" ] || echo "! ${1}"
# display help
echo "\
$(basename "$0") -f input -s 00:00:00 -t 00:00:00 -i ip -p port"
exit 2
}


#===============================================================================
# error messages
#===============================================================================

INVALID_OPT_ERR='Invalid option:'
REQ_ARG_ERR='requires an argument'
WRONG_ARGS_ERR='wrong number of arguments passed to script'


#===============================================================================
# check number of aruments passed to script
#===============================================================================

[ $# -gt 0 ] || usage "${WRONG_ARGS_ERR}"


#===============================================================================
# getopts check options passed to script
#===============================================================================

while getopts 'f:i:p:s:t:h' opt
do
  case ${opt} in
     f) input="${OPTARG}";;
     i) ip="${OPTARG}";;
     p) port="${OPTARG}";;
     s) start="${OPTARG}";;
     t) end="${OPTARG}";;
     h) usage;;
     \?) usage "${INVALID_OPT_ERR} ${OPTARG}" 1>&2;;
     :) usage "${INVALID_OPT_ERR} ${OPTARG} ${REQ_ARG_ERR}" 1>&2;;
  esac
done
shift $((OPTIND-1))


#===============================================================================
# defaults
#===============================================================================

# default ip
ip_default='192.168.1.131'

# default port
port_default='6882'


#===============================================================================
# calculate duration using sexagesimal math
#===============================================================================

get_duration() {
    printf "%s %s\n" "$1" "$2" | awk '
        {
          start = $1
          end = $2
          if (start ~ /:/) {
            split(start, t, ":")
            sseconds = (t[1] * 3600) + (t[2] * 60) + t[3] 
          }
          if (end ~ /:/) {
            split(end, t, ":")
            eseconds = (t[1] * 3600) + (t[2] * 60) + t[3] 
          }
          duration = eseconds - sseconds
          printf("%s\n"), duration
        }' \
    | awk -F. '
        NF==1 { printf("%02d:%02d:%02d\n"), ($1 / 3600), ($1 % 3600 / 60), ($1 % 60) }\
        NF==2 { printf("%02d:%02d:%02d.%s\n"), ($1 / 3600), ($1 % 3600 / 60), ($1 % 60), ($2) }'
}


#===============================================================================
# one stream containing audio and video
#===============================================================================

one_stream () {
    ffmpeg \
    -hide_banner \
    -stats -v panic \
    -y \
    -re \
    -i "${input}" \
    -c:a copy -c:v copy \
    -tune zerolatency \
    -f mpegts "srt://${ip:=${ip_default}}:${port:=${port_default}}"
}


#===============================================================================
# one stream container audio and video - trim with stream copy
#===============================================================================

one_stream_trim () {
    if [ -n "${start}" ] && [ -n "${end}" ]; then
        duration=$(get_duration "${start}" "${end}")
        duration_arg="-t ${duration}"
    elif [ -n "${end}" ]; then
        duration_arg="-t ${end}"
    fi

    # shellcheck disable=SC2086
    ffmpeg \
    -hide_banner \
    -stats -v panic \
    -y \
    -ss "${start}" \
    -re \
    -i "${input}" \
    ${duration_arg} \
    -c:a copy -c:v copy \
    -tune zerolatency \
    -f mpegts "srt://${ip:=${ip_default}}:${port:=${port_default}}"
}


#===============================================================================
# case statement check if playing the whole video or trimming
#===============================================================================

# start, end, or both were provided
if [ -n "${start}" ] || [ -n "${end}" ]; then
    one_stream_trim
else
    one_stream
fi
