#+STARTUP: content
* ogr2ogr install

#+begin_src sh
sudo apt install gdal-bin
#+end_src

** convert csv to kml

where longitude and latitude are the column names in the csv

#+begin_src sh
ogr2ogr -f KML outfile.kml infile.csv -oo X_POSSIBLE_NAMES=longitude -oo Y_POSSIBLE_NAMES=latitude
#+end_src

** convert csv to libkml

where longitude and latitude are the column names in the csv

#+begin_src sh
ogr2ogr -f LIBKML outfile.kml infile.csv -oo X_POSSIBLE_NAMES=longitude -oo Y_POSSIBLE_NAMES=latitude
#+end_src

** convert csv to geojson

where longitude and latitude are the column names in the csv

#+begin_src sh
ogr2ogr -f GEOJSON outfile.json infile.csv -oo X_POSSIBLE_NAMES=longitude -oo Y_POSSIBLE_NAMES=latitude -oo KEEP_GEOM_COLUMNS=NO
#+end_src

** convert kml to csv

GEOMETRY: By default, the geometry of a feature written to a .csv file is discarded.

It is possible to export the geometry in its WKT representation by specifying GEOMETRY=AS_WKT. It is also possible to export point geometries into their X,Y,Z components (different columns in the csv file) by specifying GEOMETRY=AS_XYZ, GEOMETRY=AS_XY or GEOMETRY=AS_YX. The geometry column(s) will be prepended to the columns with the attributes values.

this will create x and y colums in the csv file,
where x is longitude and y is longitude

#+begin_src sh
ogr2ogr -f CSV output.csv input.kml -lco GEOMETRY=AS_XY
#+end_src
