#!/bin/sh

# bagpuss

# wmctrl
workspace() {
    printf "%s\n" "${@}" | awk '{ printf("%s\n", $1) }' | \
    while read -r line
    do
      wmctrl -s "${line}"
    done
}

# fzf prompt variables spaces to line up menu options
wspace="$(wmctrl -d | awk '{ printf("%s %s %s\n", $1, $2, "Workspace") }')"

# fzf prompt to specify function to run
menu=$(printf "%s\n" \
	      "${wspace}" \
	      | fzf --delimiter='\n' --prompt='Switch to Workspace: ' --info=inline --layout=reverse --no-multi)

# case statement to run function based on fzf prompt output
case "${menu}" in
   [0-9]*) workspace "${menu}";;
   *) exit;;
esac
