#+STARTUP: content
* debian efi i3-wm

burn the net iso to a disk
insert the disk and hold down the alt key on a mac
select the efi boot disc icon and not windows
select advanced options
select expert install
select debian sid
select guided install encrypted and lvm
select seperate home partition
install grub to main drive
dont select install efi boot to media
install packages
deselect debian desktop and print by pressing space
make sure only standard system utilities are selected

** upgrade to sid

#+begin_src sh
sudo nano /etc/apt/sources.list
#+end_src

Comment out (place a # in the beginning of each line) all lines.

#+begin_src sh
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
#+end_src

#+begin_src sh
sudo apt-get install --no-install-recommends \ 
xorg \
xinit \
x11-xserver-utils \
xserver-xorg-input-synaptics \
xserver-xorg-video-intel \
xserver-xorg-input-evdev \
network-manager \
wireless-tools \
wpasupplicant \
ttf-dejavu \
alsa-utils \
build-essential \
gdb \
firmware-linux-nonfree \
seahorse \ 
gnome-keyring \
broadcom-sta-dkms
#+end_src

** luks change password

#+begin_src sh
sudo cryptsetup -y luksAddKey ENCRYPTED_PARTITION
sudo cryptsetup luksRemoveKey ENCRYPTED_PARTITION
#+end_src

** find the luks partition

#+begin_src sh
less /etc/crypttab
#+end_src

** add new key

#+begin_src sh
sudo cryptsetup -y luksAddKey /dev/sda3
#+end_src

** remove old key

#+begin_src sh
sudo cryptsetup luksRemoveKey /dev/sda3
#+end_src

** debian i3-wm set up

#+begin_src sh
sudo apt install i3-wm i3lock i3status suckless-tools
#+end_src

** ~/.xinitrc

#+begin_src sh
vim ~/.xinitrc
#+end_src

#+begin_src conf
xkbcomp -I$HOME/.xkb $HOME/.xkb/keymap/keymap.xkb $DISPLAY
exec i3
#+end_src

** rxvt set up

#+begin_src sh
sudo apt install rxvt-unicode-256color
sudo apt install fonts-inconsolata
#+end_src

#+begin_src sh
xrdb ~/.Xresources
exec i3
#+end_src

** ranger

#+begin_src sh
sudo apt install ranger atool highlight mediainfo
#+end_src

Configuration

After startup, ranger creates a directory ~/.config/ranger.
To copy the default configuration to this directory issue the following command:

#+begin_src sh
ranger --copy-config=all
#+end_src

** git 

#+begin_src sh
sudo apt install git-core
#+end_src

** oathtool for 2 factorauth

#+begin_src sh
sudo apt install oathtool
#+end_src

** wireshark stable

#+begin_src sh
sudo apt install wireshark
#+end_src

** emacs

#+begin_src sh
sudo apt install emacs
#+end_src

** iptables

#+begin_src sh
sudo apt-get install iptables-persistent
#+end_src

** debian keyboard

#+begin_src sh
sudo dpkg-reconfigure keyboard-configuration
#+end_src

** How to set keyboard layout in initramfs

#+begin_src sh
sudo vim /etc/initramfs-tools/initramfs.conf
#+end_src

#+begin_src conf
#
# KEYMAP: [ y | n ]
#
# Load a keymap during the initramfs stage.
#

KEYMAP=y
apply changes
#+end_src

#+begin_src sh
sudo update-initramfs -u
#+end_src

** keyboard

#+begin_src sh
localectl set-x11-keymap gb pc104 mac
#+end_src

** change keyboard settings in gui

#+begin_src sh
vi /etc/vconsole.conf
#+end_src

remove 

#+begin_src conf
keymap=uk
#+end_src

** unbound dns server

#+begin_src sh
sudo apt install unbound dnssec-trigger
#+end_src

** thunar smb

#+begin_src sh
sudo apt install gvfs-backends gvfs-fuse
#+end_src

** themes 

#+begin_src sh
vim ~/.gtkrc-2.0
#+end_src

#+begin_src conf
gtk-icon-theme-name = "deepin"
gtk-theme-name = "deepin"
gtk-font-name = "Noto Sans Regular 11"
#+end_src

#+begin_src sh
mkdir ~/.local/share/themes
mkdir ~/.icons
#+end_src

Optional: run gtk-update-icon-cache -f -t ~/.icons/<theme_name> to create an icon cache 

** xkbcomp

#+begin_src sh
vim ~/.xinitrc
#+end_src

#+begin_src conf
#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# remap ctrl to alt, alt to super, super to ctrl
xkbcomp -I$HOME/.xkb $HOME/.xkb/keymap/keymap.xkb $DISPLAY

# start i3
exec i3
#+end_src

Since several people asked me how to get such a setup and it’s poorly documented (as in: I found it in the GRUB sources) I decided to blog about this. When using GRUB >=2.00-22 (as of February 2014 available in Debian/jessie and Debian/unstable) it’s possible to boot from a full-crypto setup (this doesn’t mean it’s recommended, but it worked fine in my test setups so far). This means not even an unencrypted /boot partition is needed.

Before executing the grub-install commands execute those steps (inside the system/chroot of course, adjust GRUB_PRELOAD_MODULES for your setup as needed, I’ve used it in a setup with SW-RAID/LVM):

#+begin_src sh
sudo echo GRUB_CRYPTODISK_ENABLE=y >> /etc/default/grub
sudo echo 'GRUB_PRELOAD_MODULES="lvm cryptodisk mdraid1x"' >> /etc/default/grub
#+end_src

** ranger

to stop ranger loading both the default and your custom rc.conf,
set the environmen variable: RANGER_LOAD_DEFAULT_RC to FALSE

**  chromium extensions

The newest Chromium in Debian sid disables remote extension loading by default. This has the effect of disabling extensions en masse. I'm not sure what the reasoning is, but it's damn inconvenient.

It's claimed that one way to get the old behavior back is to add

--enable-remote-extensions

to the list of flags in /etc/chromium.d/default-flags. This will affect all users on the system, and the file could be overwritten by an upgrade. In addition, until I know better what's behind the change, I'd really like to apply the change only to my account, not to all users.

fix latest Debian Chromium disabling remote extensions

#+begin_src conf
export CHROMIUM_FLAGS=$CHROMIUM_FLAGS" --enable-remote-extensions"
#+end_src

to my ~/.profile. Be sure to log out and back in to experience the change.

** syncthing

#+begin_src sh
sudo apt-get install apt-transport-https
#+end_src

** Add the release PGP keys:

#+begin_src sh
curl -s https://syncthing.net/release-key.txt | sudo apt-key add -
#+end_src

** Add the "stable" channel to your APT sources:

#+begin_src sh
echo "deb https://apt.syncthing.net/ syncthing stable" | sudo tee /etc/apt/sources.list.d/syncthing.list
#+end_src

** Update and install syncthing:

#+begin_src sh
sudo apt-get update
sudo apt-get install syncthing
#+end_src

** systemd user service

By default, users cannot set user services to run at boot time.
The admin must enable this on an individual basis for each user.

#+begin_src sh
sudo loginctl enable-linger <username>
#+end_src

** mpd

#+begin_src sh
sudo systemctl disable mpd
systemctl --user start mpd
#+end_src
