#+STARTUP: show2levels
#+OPTIONS: num:nil
#+OPTIONS: author:nil
* Freebsd Wayland

+ [[freebsd root dotfiles][https://github.com/NapoleonWils0n/freebsd-root-xps]]
+ [[freebsd dotfiles][https://github.com/NapoleonWils0n/freebsd-dotfiles-xps]]
+ [[freebsd home bin][https://github.com/NapoleonWils0n/freebsd-bin-xps]]

** download freebsd 

download the memstick.img.xz to install on a usb stick

#+begin_src sh
wget https://download.freebsd.org/releases/amd64/amd64/ISO-IMAGES/15.0/FreeBSD-15.0-RELEASE-amd64-memstick.img.xz
#+end_src

download the checksum

#+begin_src sh
wget https://download.freebsd.org/releases/amd64/amd64/ISO-IMAGES/15.0/CHECKSUM.SHA512-FreeBSD-15.0-RELEASE-amd64
#+end_src

Verify the checksum 

#+begin_src sh
sha512sum -c CHECKSUM.SHA512-FreeBSD-15.0-RELEASE-amd64 FreeBSD-15.0-RELEASE-amd64-memstick.img.xz
#+end_src

** writing an image file to usb
*** freebsd 

extract the xz file

#+begin_src sh
xz -dv FreeBSD-15.0-RELEASE-amd64-memstick.img.xz
#+end_src

dd the image to a usb drive

#+begin_src sh
sudo dd if=FreeBSD-15.0-RELEASE-amd64-memstick.img of=/dev/da0 bs=1M conv=sync
#+end_src

*** linux

extract the xz file

#+begin_src sh
xz -dv FreeBSD-15.0-RELEASE-amd64-memstick.img.xz
#+end_src

check the output of lblk to find the device

#+begin_src sh
lsblk
#+end_src

in this example the drive is /dev/sda

dd the image to a usb drive

#+begin_src sh
doas dd if=FreeBSD-15.0-RELEASE-amd64-memstick.img of=/dev/sda bs=1M conv=fsync status=progress
#+end_src

** remove old boot entry

on the dell xps we need to press F2 repeatedly when we start up to enter the bios

delete any boot entries by selecting them and pressing delete

then click apply and exit

plug in the freebsd usb stick and then pres F12 to enter the one time boot menu

select the usb drive to boot into freebsd

** freebsd installer

press enter to start the installer

select install

*** keymap

select

United States of America (Macbook/Macbook Pro) IS0-88591

*** set hostname

set to pollux

*** select installation type

set to

Packages (Tech Preview)

*** network or offline installation

select network

*** network configuration

select your ethernet connection

ue0

and select auto

*** partitioning

Select root on zfs during in

+ encrypt discs
+ encrypt swap
+ swap size 8gig

freebsd installer partition scheme
for apple hardware choose gpt (bios+uefi)

select Pool Type/Disks

select stripe and select you disk by pressing space and then ok by pressing enter

press procede with install

*** zfs configuration

press the left arrow to select yes and then enter

enter the your geli password

you will prompted to enter it twice

*** select system components

select the following options

use the arrow keys to move up and down and space to select

- base: System core
- devel: Build tools/headers (Required for dwl)
- src: System source code (Required for NVIDIA/Kmods)
- lib32: 32-bit compatibility (Good for Linuxulator)

*** Post-Install: Fetching the Ports Tree

FreeBSD 15 uses git for ports. Once booted:

#+begin_src sh
doas pkg install git
doas git clone https://git.freebsd.org/ports.git /usr/ports
#+end_src

*** set the root password

set the root password during the install

*** timezone

set the timezone

for the uk select

8 Europe

countries or region

select

49 United Kingdon of Great Britain and Northen Ireland

configuration

does the timezone abbreviation 'BST' look reasonable 

click Yes

*** time and date

press the left arrow key to select Set Date

and press enter

press the left arrow key to select Set Time

and press enter

*** system configuration

deselect

sshd and local_unbound 

we will install the unbound package

select 

- ntpd
- ntpd_sync_on_start
- powered
- moused
- dumpdev

*** system hardening

select everything except

9 disable_ddtrace

*** Freebsd firmware installation

keep the following selected

gpu-firmware-intel-kmod-kabylake

wifi-firmware-iwlwifi-kmod-22000

press enter

*** add user

press enter to select Yes

- Username should be set to your username you will log in with

- Full Name is your full name

- Uid leave empty for default

- Login group leave at default

- Login group invite to other groups should be set to wheel video operator

- Login class: (Default).

- Shell leave as default sh

- Home directory leave as default

- Home Directory persmission leave empty for default

- Enable ZFS encryption for the home directory use the default of no

- Use password based authentication leave as default of yes

- Use and empty password accept default of no

- Use a random password accept default of no

- Enter password: enter your password

- Lock out the account after creation leave at default of no

Press enter to select yes to create the user

Add another user press enter to select no

*** Final configuration

Select Finish and press enter to select

*** Manual Configuration

the installation is now finished

before exiting the installer would you like to open a shell in the new system to make any final manual modification's

press the left arrow key to select yes and press enter

this shell is operatin in a chroot in the new system

when finised making configuration changes, type exit

*** create zfs dataset in home for directories

change djwilcox to your username in the code below

#+begin_src sh
zfs create zroot/home/djwilcox/bin
zfs create zroot/home/djwilcox/desktop
zfs create zroot/home/djwilcox/documents
zfs create zroot/home/djwilcox/downloads
zfs create zroot/home/djwilcox/music
zfs create zroot/home/djwilcox/git
zfs create zroot/home/djwilcox/video
zfs create zroot/home/djwilcox/pictures
zfs create zroot/home/djwilcox/torrents
zfs create zroot/home/djwilcox/.cache
zfs create zroot/home/djwilcox/.config
zfs create zroot/home/djwilcox/.local
#+end_src

#+begin_src sh
chown -R djwilcox:djwilcox /mnt/home/djwilcox
#+end_src

check the directories have been created

#+begin_src sh
ls -al /mnt/home/djwilcox
#+end_src

exit the installer

#+begin_src sh
exit
#+end_src

select shutdown

press the right arrow once to select shutdown and then press enter

once its shutdown unplug the usb drive

*** log in

press the power button

enter the geli password

press enter at the log in screen

then log in with your username and password

** bectl crete boot environment

list the boot environments

#+begin_src sh
bectl list
#+end_src

switch to root

#+begin_src sh
su -
#+end_src

create a new boot environment

#+begin_src sh
bectl create fresh_install
#+end_src

shutdown 

#+begin_src sh
shutdown -p now
#+end_src

** pkg update

pkg is already installed with the new tech preview

#+begin_src sh
su -
#+end_src

run pkg update

#+BEGIN_SRC sh
pkg update
#+END_SRC

** prime list

switch to root

#+begin_src sh
su -
#+end_src

load linux64 needed for nvidia drivers

#+begin_src sh
kldload linux64
#+end_src

install prime list of packages

#+begin_src sh
pkg install $(cat prime-list-xps-2026.txt)
#+end_src

#+begin_example
FreeBSD-kernel-generic
FreeBSD-set-base
FreeBSD-set-devel
FreeBSD-set-lib32
FreeBSD-set-minimal
FreeBSD-set-src
ImageMagick7
abook
adwaita-qt5
adwaita-qt6
alacritty
apg
aria2
aspell
bat
ca_root_nss
cantarell-fonts
chromium
cmake
dictd
dnscrypt-proxy2
doas
dwlb
e2fsprogs-core
emacs-devel
en-aspell
evdev-proto
fd-find
ffmpeg
ffmpegthumbnailer
firacode
firefox
fusefs-ext2
gdb
git
gmake
gnome-themes-extra
gpu-firmware-intel-kmod-kabylake
graphviz
gstreamer1-libav
gstreamer1-plugins-bad
gstreamer1-plugins-opus
hs-pandoc
imv
jq
libc6-shim
libheif
libinput
libnotify
libva-intel-media-driver
libva-nvidia-driver
libva-utils
libvdpau-va-gl
libxcb
libxkbcommon
linux-nvidia-libs
mixertui
mpv
mpv-mpris
musicpc
musicpd
ncmpc
noto-basic
noto-emoji
nvidia-driver
nvidia-drm-61-kmod
nvidia-settings
oath-toolkit
obs-studio
ollama
openvpn
pavucontrol
pinentry-curses
pkg
pkgconf
playerctl
podman-suite
poudriere
py311-podman-compose
qbittorrent
qt5-style-plugins
qt5-wayland
qt5ct
qt6-wayland
qt6ct
ripgrep
ripgrep-all
rsync
rust
seatd
socat
sox
sudo
syncthing
tmux
tofi
translate-shell
tree
tree-sitter
ts
unbound
wayland
wayland-protocols
wayland-utils
wev
wget2
wifi-firmware-iwlwifi-kmod-22000
wl-clipboard
wlr-which-key
wlrctl
wlrobs
wlroots019
xcb-util-wm
xdg-desktop-portal-wlr
yt-dlp
zathura
zathura-pdf-mupdf
zip
zsh
zsh-completions
zsh-syntax-highlighting

#+end_example

** copy files into place

switch to root

#+begin_src sh
su -
#+end_src

Assuming you are in the git repo directory

#+begin_src sh
rsync -av ./etc/ /etc/
rsync -av ./usr/local/etc/ /usr/local/etc/
rsync -av ./boot/ /boot/
#+end_src

change the permisions

#+begin_src sh
chown -R root:wheel /boot
chown -R root:wheel /etc
chown -R root:wheel /usr/local/etc/
#+end_src

run cap_mkdb

#+begin_src sh
cap_mkdb /etc/login.conf
#+end_src

switch back to out user by running exit to exit from the root shell

#+begin_src sh
exit
#+end_src

run cap_mkdb

#+begin_src sh
cap_mkdb ~/.login_conf
#+end_src

change shell

#+begin_src sh
chsh -s /usr/local/bin/zsh
#+end_src

** install zsh

change the shell to zsh

#+BEGIN_SRC sh
chsh -s /usr/local/bin/zsh
#+END_SRC

** dwl
*** resources

+ dwl codeberg

[[https://codeberg.org/dwl/dwl]]

+ patches wiki

[[https://codeberg.org/dwl/dwl-patches/src/branch/main/patches]]

+ movestack patch

[[https://codeberg.org/dwl/dwl-patches/src/branch/main/patches/movestack]]

[[https://codeberg.org/dwl/dwl-patches/raw/branch/main/patches/movestack/movestack-0.8.patch]]

*** packages install

#+begin_src sh
doas pkg install seatd evdev-proto wayland-protocols gmake pkgconf libxcb libinput wayland wlroots019 libxkbcommon xcb-util-wm nvidia-driver nvidia-settings nvidia-drm-61-kmod libva-intel-driver libva-utils dwlb
#+end_src

we also need to edit /etc/rc.conf and add the path to the i915kms.ko file

#+begin_src sh
sudo sysrc kld_list+="i915kms nvidia-modeset nvidia-drm nvidia_gsp_tu10x_fw linux linux64"
#+end_src

or manually edit the config file

#+BEGIN_SRC sh
sudo vi /etc/rc.conf
#+END_SRC

then add the code below to /etc/rc.conf

#+BEGIN_SRC sh
kld_list="i915kms nvidia-modeset nvidia-drm nvidia_gsp_tu10x_fw linux linux64"
#+END_SRC

*** fstab

Add procfs to /etc/fstab with this line

#+begin_src sh
proc /proc procfs rw 0 0
#+end_src

The seatd daemon helps manage access to shared system devices for non-root users in compositors; this includes graphics cards. For traditional X11 managers, seatd is not needed, such as both Plasma and GNOME, but for the Wayland compositors discussed here, it will need enabled on the system and be running before starting a compositor environment. To enable and start the seatd daemon now, and on system initialization:

#+begin_src sh
sudo sysrc seatd_enable="YES"
sudo sysrc dbus_enable="YES"
#+end_src

*** build dwl
**** download dwl

#+begin_src sh
fetch 'https://codeberg.org/dwl/dwl/releases/download/v0.8/dwl-v0.8.tar.gz'
#+end_src

**** untar dwl

#+begin_src sh
tar -xf dwl-v0.8.tar.gz
#+end_src

**** change into the dwl directory

#+begin_src sh
cd dwl-v0.8
#+end_src

**** download the movestack patch

#+begin_src sh
fetch 'https://codeberg.org/dwl/dwl-patches/raw/branch/main/patches/movestack/movestack-0.8.patch'
#+end_src

**** patch dwl

#+begin_src sh
patch -p1 < ../movestack-0.8.patch
#+end_src

**** Makefile

#+begin_src sh
sed -i'' -e s/_POSIX_C_SOURCE=200809L/_XOPEN_SOURCE=700/ Makefile
#+end_src

**** config.h

rename config.def.h to config.h

#+begin_src sh
mv config.def.h config.h
#+end_src

edit config.h

#+begin_src c
/* Taken from https://github.com/djpohly/dwl/issues/466 */
#define COLOR(hex)    { ((hex >> 24) & 0xFF) / 255.0f, \
                        ((hex >> 16) & 0xFF) / 255.0f, \
                        ((hex >> 8) & 0xFF) / 255.0f, \
                        (hex & 0xFF) / 255.0f }
/* appearance */
static const int sloppyfocus               = 1;  /* focus follows mouse */
static const int bypass_surface_visibility = 0;  /* 1 means idle inhibitors will disable idle tracking even if it's surface isn't visible  */
static const unsigned int borderpx         = 1;  /* border pixel of windows */
static const float rootcolor[]             = COLOR(0x222222ff);
static const float bordercolor[]           = COLOR(0x444444ff);
static const float focuscolor[]            = COLOR(0x005577ff);
static const float urgentcolor[]           = COLOR(0xff0000ff);
/* This conforms to the xdg-protocol. Set the alpha to zero to restore the old behavior */
static const float fullscreen_bg[]         = {0.0f, 0.0f, 0.0f, 1.0f}; /* You can also use glsl colors */

/* tagging - TAGCOUNT must be no greater than 31 */
#define TAGCOUNT (9)

/* logging */
static int log_level = WLR_ERROR;

static const Rule rules[] = {
	/* app_id             title       tags mask     isfloating   monitor */
    /* default/example rule: can be changed but cannot be eliminated; at least one rule must exist */
	{ "mpv",  NULL,           0,       1,           0 },
};

/* layout(s) */
static const Layout layouts[] = {
	/* symbol     arrange function */
	{ "[]=",      tile },
	{ "><>",      NULL },    /* no layout function means floating behavior */
	{ "[M]",      monocle },
};

/* monitors */
/* (x=-1, y=-1) is reserved as an "autoconfigure" monitor position indicator
 ,* WARNING: negative values other than (-1, -1) cause problems with Xwayland clients due to
 ,* https://gitlab.freedesktop.org/xorg/xserver/-/issues/899 */
static const MonitorRule monrules[] = {
   /* name        mfact  nmaster scale layout       rotate/reflect                x    y
    ,* example of a HiDPI laptop monitor:
    { "eDP-1",    0.5f,  1,      2,    &layouts[0], WL_OUTPUT_TRANSFORM_NORMAL,   -1,  -1 }, */
	{ NULL,       0.55f, 1,      1,    &layouts[0], WL_OUTPUT_TRANSFORM_NORMAL,   -1,  -1 },
	/* default monitor rule: can be changed but cannot be eliminated; at least one monitor rule must exist */
};

/* keyboard */
static const struct xkb_rule_names xkb_rules = {
	/* can specify fields: rules, model, layout, variant, options */
	/* example:
	.options = "ctrl:nocaps",
	,*/
	.layout = "gb",
	.model = "104",
	.options = "ctrl:swap_lalt_lctl,custom:swap_sterling_numbersign,caps:none",
	.rules = "evdev",
	.variant = "mac",
};

static const int repeat_rate = 35;
static const int repeat_delay = 400;

/* Trackpad */
static const int tap_to_click = 1;
static const int tap_and_drag = 1;
static const int drag_lock = 1;
static const int natural_scrolling = 0;
static const int disable_while_typing = 1;
static const int left_handed = 0;
static const int middle_button_emulation = 0;
/* You can choose between:
LIBINPUT_CONFIG_SCROLL_NO_SCROLL
LIBINPUT_CONFIG_SCROLL_2FG
LIBINPUT_CONFIG_SCROLL_EDGE
LIBINPUT_CONFIG_SCROLL_ON_BUTTON_DOWN
,*/
static const enum libinput_config_scroll_method scroll_method = LIBINPUT_CONFIG_SCROLL_2FG;

/* You can choose between:
LIBINPUT_CONFIG_CLICK_METHOD_NONE
LIBINPUT_CONFIG_CLICK_METHOD_BUTTON_AREAS
LIBINPUT_CONFIG_CLICK_METHOD_CLICKFINGER
,*/
static const enum libinput_config_click_method click_method = LIBINPUT_CONFIG_CLICK_METHOD_BUTTON_AREAS;

/* You can choose between:
LIBINPUT_CONFIG_SEND_EVENTS_ENABLED
LIBINPUT_CONFIG_SEND_EVENTS_DISABLED
LIBINPUT_CONFIG_SEND_EVENTS_DISABLED_ON_EXTERNAL_MOUSE
,*/
static const uint32_t send_events_mode = LIBINPUT_CONFIG_SEND_EVENTS_ENABLED;

/* You can choose between:
LIBINPUT_CONFIG_ACCEL_PROFILE_FLAT
LIBINPUT_CONFIG_ACCEL_PROFILE_ADAPTIVE
,*/
static const enum libinput_config_accel_profile accel_profile = LIBINPUT_CONFIG_ACCEL_PROFILE_FLAT;
static const double accel_speed = 1.0;

/* You can choose between:
LIBINPUT_CONFIG_TAP_MAP_LRM -- 1/2/3 finger tap maps to left/right/middle
LIBINPUT_CONFIG_TAP_MAP_LMR -- 1/2/3 finger tap maps to left/middle/right
,*/
static const enum libinput_config_tap_button_map button_map = LIBINPUT_CONFIG_TAP_MAP_LRM;

/* If you want to use the windows key for MODKEY, use WLR_MODIFIER_LOGO */
#define MODKEY WLR_MODIFIER_LOGO

#define TAGKEYS(KEY,SKEY,TAG) \
	{ MODKEY,                    KEY,            view,            {.ui = 1 << TAG} }, \
	{ MODKEY|WLR_MODIFIER_CTRL,  KEY,            toggleview,      {.ui = 1 << TAG} }, \
	{ MODKEY|WLR_MODIFIER_SHIFT, SKEY,           tag,             {.ui = 1 << TAG} }, \
	{ MODKEY|WLR_MODIFIER_CTRL|WLR_MODIFIER_SHIFT,SKEY,toggletag, {.ui = 1 << TAG} }

/* helper for spawning shell commands in the pre dwm-5.0 fashion */
#define SHCMD(cmd) { .v = (const char*[]){ "/bin/sh", "-c", cmd, NULL } }

/* commands */
static const char *termcmd[] = { "alacritty", NULL };
static const char *menucmd[] = { "tofi-drun", NULL };
static const char *volumeup[]      = { "/usr/sbin/mixer",   "vol=+5%:+5%",  NULL };
static const char *volumedown[]    = { "/usr/sbin/mixer",   "vol=-5%:-5%",  NULL };
static const char *mutevolume[]    = { "/usr/sbin/mixer",   "vol.mute=^",        NULL };
static const char *cursorleft[]    = { "/usr/local/bin/wlrctl",   "pointer",  "move", "-1920",     NULL };
static const char *cursorright[]    = { "/usr/local/bin/wlrctl",   "pointer", "move", "1920",        NULL };
static const char *wlrwhichkey[]    = { "/usr/local/bin/wlr-which-key",  NULL };

static const Key keys[] = {
	/* Note that Shift changes certain key codes: 2 -> at, etc. */
	/* modifier                  key                  function          argument */
	{ 0,                         XKB_KEY_XF86AudioRaiseVolume, spawn, {.v = volumeup   } },
	{ 0,                         XKB_KEY_XF86AudioLowerVolume, spawn, {.v = volumedown } },
	{ 0,                         XKB_KEY_XF86AudioMute, spawn, {.v = mutevolume } },
	{ MODKEY,                    XKB_KEY_z,          spawn,          {.v = wlrwhichkey} },
	{ MODKEY,                    XKB_KEY_a,          spawn,          {.v = menucmd} },
	{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_Return,     spawn,          {.v = termcmd} },
	{ MODKEY|WLR_MODIFIER_CTRL,  XKB_KEY_Return,     spawn,          SHCMD("emacsclient -a= -c") },
	{ MODKEY|WLR_MODIFIER_ALT,  XKB_KEY_space,       spawn,          SHCMD("playerctl play-pause") },
	{ MODKEY,                    XKB_KEY_j,           focusstack,       {.i = +1} },
	{ MODKEY,                    XKB_KEY_k,           focusstack,       {.i = -1} },
	{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_J,           movestack,        {.i = +1} },
	{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_K,           movestack,        {.i = -1} },
	{ MODKEY,                    XKB_KEY_i,           incnmaster,       {.i = +1} },
	{ MODKEY,                    XKB_KEY_d,           incnmaster,       {.i = -1} },
	{ MODKEY,                    XKB_KEY_h,           setmfact,         {.f = -0.05f} },
	{ MODKEY,                    XKB_KEY_l,           setmfact,         {.f = +0.05f} },
	{ MODKEY,                    XKB_KEY_Return,      zoom,             {0} },
	{ MODKEY,                    XKB_KEY_Tab,         view,             {0} },
	{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_C,           killclient,       {0} },
	{ MODKEY,                    XKB_KEY_t,           setlayout,        {.v = &layouts[0]} },
	{ MODKEY,                    XKB_KEY_f,           setlayout,        {.v = &layouts[1]} },
	{ MODKEY,                    XKB_KEY_m,           setlayout,        {.v = &layouts[2]} },
	{ MODKEY,                    XKB_KEY_space,       setlayout,        {0} },
	{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_space,       togglefloating,   {0} },
	{ MODKEY,                    XKB_KEY_s,           togglefullscreen, {0} },
	{ MODKEY,                    XKB_KEY_0,           view,             {.ui = ~0} },
	{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_parenright,  tag,              {.ui = ~0} },
	{ MODKEY|WLR_MODIFIER_CTRL,  XKB_KEY_comma,       focusmon,         {.i = WLR_DIRECTION_LEFT} },
	{ MODKEY|WLR_MODIFIER_CTRL,  XKB_KEY_period,      focusmon,         {.i = WLR_DIRECTION_RIGHT} },
	{ MODKEY,                    XKB_KEY_comma,       spawn,            {.v = cursorleft} },
	{ MODKEY,                    XKB_KEY_period,      spawn,            {.v = cursorright} },
	{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_less,        tagmon,           {.i = WLR_DIRECTION_LEFT} },
	{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_greater,     tagmon,           {.i = WLR_DIRECTION_RIGHT} },
	TAGKEYS(          XKB_KEY_1, XKB_KEY_exclam,                        0),
	TAGKEYS(          XKB_KEY_2, XKB_KEY_at,                            1),
	TAGKEYS(          XKB_KEY_3, XKB_KEY_numbersign,                    2),
	TAGKEYS(          XKB_KEY_4, XKB_KEY_dollar,                        3),
	TAGKEYS(          XKB_KEY_5, XKB_KEY_percent,                       4),
	TAGKEYS(          XKB_KEY_6, XKB_KEY_asciicircum,                   5),
	TAGKEYS(          XKB_KEY_7, XKB_KEY_ampersand,                     6),
	TAGKEYS(          XKB_KEY_8, XKB_KEY_asterisk,                      7),
	TAGKEYS(          XKB_KEY_9, XKB_KEY_parenleft,                     8),
	{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_q,           quit,             {0} },

	/* Ctrl-Alt-Backspace and Ctrl-Alt-Fx used to be handled by X server */
	{ WLR_MODIFIER_CTRL|WLR_MODIFIER_ALT,XKB_KEY_Terminate_Server, quit, {0} },
	/* Ctrl-Alt-Fx is used to switch to another VT, if you don't know what a VT is
	 ,* do not remove them.
	 ,*/
#define CHVT(n) { WLR_MODIFIER_CTRL|WLR_MODIFIER_ALT,XKB_KEY_XF86Switch_VT_##n, chvt, {.ui = (n)} }
	CHVT(1), CHVT(2), CHVT(3), CHVT(4), CHVT(5), CHVT(6),
	CHVT(7), CHVT(8), CHVT(9), CHVT(10), CHVT(11), CHVT(12),
};

static const Button buttons[] = {
	{ MODKEY, BTN_LEFT,   moveresize,     {.ui = CurMove} },
	{ MODKEY, BTN_MIDDLE, togglefloating, {0} },
	{ MODKEY, BTN_RIGHT,  moveresize,     {.ui = CurResize} },
};

#+end_src

*** make dwl

make without xwayland

#+begin_src sh
gmake CC=cc CFLAGS+='-std=c11'
#+end_src

install

#+begin_src sh
doas cp dwl /usr/local/bin/
#+end_src

make sure its executable

#+begin_src sh
doas chmod + /usr/local/bin/dwl
#+end_src

*** dwl-start

dwl-start script to start dwl from a tty

move the dwl-start script to your local bin directory

#+begin_src sh
mv dwl-start ~/bin
#+end_src

make it executable

#+begin_src sh
chmod +x ~/bin/dwl-start
#+end_src

#+begin_src sh
#!/bin/sh

# start dwl with dbus
exec dbus-launch --exit-with-session dwl -s 'dwlb -font "monospace:size=16"' 2>/dev/null
#+end_src

** obs studio

Only root can grant real-time priority to processes for now, using rtprio(1).
Upcoming FreeBSD releases will have a MAC policy with a realtime user group.

Memory locking has to be allowed in /etc/login.conf or ~/.login_conf. Set the
resource limit ":memorylocked=unlimited:" and don't forget to run

#+begin_src sh
vi ~/.login_conf
#+end_src

#+begin_src conf
me:\
  :charset=UTF-8:\
  :lang=en_GB.UTF-8:\
  :setenv=LC_COLLATE=C:\
  :memorylocked=unlimited:
#+end_src

#+begin_src sh
cap_mkdb ~/.login_conf
#+end_src

** mpd

#+begin_src sh
sudo pkg install musicpd musicpc
#+end_src

create the mpd playlists directory

#+begin_src sh
mkdir -p ~/.config/mpd/playlists
#+end_src

touch files

#+begin_src sh
touch ~/.config/mpd/{mpd.db,mpd.log,mpd.pid,mpdstate,sticker.sql,socket}
#+end_src

start mpd

#+begin_src sh
musicpd &
#+end_src

** audio
*** freebsd set default audio

view detected audio devices

#+BEGIN_SRC sh
cat /dev/sndstat
#+END_SRC

change to the first audio device

#+BEGIN_SRC sh
sudo sysctl hw.snd.default_unit=1
#+END_SRC

change to the second audio device

#+BEGIN_SRC sh
sudo sysctl hw.snd.default_unit=2
#+END_SRC

**** freebsd bit perfect audio 

list audio devices

#+BEGIN_SRC sh
cat /dev/sndstat
#+END_SRC

set values at boot

#+BEGIN_SRC sh
sudo vim /etc/sysctl.conf
#+END_SRC

edit /etc/sysctl.conf

replace dev.pcm.2 with the number of your audio device

#+BEGIN_SRC sh
dev.pcm.2.play.vchans=0
dev.pcm.2.bitperfect=1
#+END_SRC

+ regular audio

#+BEGIN_SRC sh
sudo sysctl dev.pcm.2.bitperfect=0
#+END_SRC

+ bit perfect

#+BEGIN_SRC sh
sudo sysctl dev.pcm.2.bitperfect=1
#+END_SRC

+ show volume

#+BEGIN_SRC sh
mixer
#+END_SRC

***** set vol to 100

#+begin_src sh
mixer vol.volume=100:100
#+end_src

***** set pcm to 100

#+begin_src sh
mixer pcm.volume=100:100
#+end_src

***** set rec to 100

#+begin_src sh
mixer rec.volume=100:100
#+end_src

***** set monitor to 100

#+begin_src sh
mixer monitor.volume=100:100
#+end_src

***** increase and decrease the volume

increase the volume by 5%

#+begin_src conf
mixer vol=+5%:+5%
#+end_src

decrease the volume by 5%

#+begin_src conf
mixer vol=-5%:-5%
#+end_src

in the terminal you will need to quote the argument

increase the volume by 5%

#+begin_src sh
mixer vol="+5%:+5%"
#+end_src

decrease the volume by 5%

#+begin_src sh
mixer vol="-5%:-5%"
#+end_src

***** toggle mute

#+begin_src conf
mixer vol.mute=^
#+end_src

in the terminal you will need to quote the caret

#+begin_src sh
mixer vol.mute="^"
#+end_src

***** mute

#+begin_src sh
mixer vol.mute=1
#+end_src

***** unmute

#+begin_src sh
mixer vol.mute=0
#+end_src

** mixertui

Audio Mixer with a Terminal User Interface

*** Message from sysctlinfo-kmod-20221211:

To use this interface, make sure that you have loaded the sysctlinfo kernel
module, by doing

#+begin_src sh
sudo kldload sysctlinfo
#+end_src

use sysrc to add sysctlinfo_load="YES" to /boot/loader.conf

#+begin_src sh
sudo sysrc -f /boot/loader.conf sysctlinfo_load="YES"
#+end_src

or by manually your /boot/loader.conf

#+begin_src sh
sudo vi /boot/loader.conf
#+end_src

then add sysctlinfo_load="YES" to loader.conf

#+begin_src conf
sysctlinfo_load="YES"
#+end_src

*** Message from sysctlbyname-improved-kmod-20221211:

To use the sysctl.entryidinputbyname sysctl node and the sysctlbyname_improved
function, make sure that you have loaded the sysctlbyname_improved kernel
module, by doing

#+begin_src sh
sudo kldload sysctlbyname_improved
#+end_src

use sysrc to add sysctlbyname_improved="YES" to /boot/loader.conf

#+begin_src sh
sudo sysrc -f /boot/loader.conf sysctlbyname_improved="YES"
#+end_src

or by manually your /boot/loader.conf

#+begin_src sh
sudo vi /boot/loader.conf
#+end_src

then add sysctlbyname_improved to loader.conf

#+begin_src conf
sysctlbyname_improved="YES"
#+end_src

** obs studio
*** xdg runtime directory

make sure to set up the xdg runtime directory as described earlier

*** dmesg

After logging in run dmesg as root to make sure the device is recognised

#+BEGIN_SRC sh
# dmesg
#+END_SRC

*** check dsp devices

Check /dev/dsp* for the device

#+BEGIN_SRC sh
ls /dev/dsp*
#+END_SRC

in my case my mic is listed as /dev/dsp2

*** unmute the mic

Un mute the volume for the devices mixer,
the mixer number for dsp2 will be mixer2

#+BEGIN_SRC sh
mixer -f /dev/mixer2 mic.volume=100:100
#+END_SRC

*** pavucontrol

obs uses pulse audio so install pavucontrol to adjust the volume

#+begin_src sh
sudo pkg install pavucontrol
#+end_src

*** pulseaudio

obs studio use pulseaudio so we need to start pulseaudio before opening obs studio,
otherwise the mic wont show up 

+ start pulse audio

#+BEGIN_SRC sh
pulseaudio --start
#+END_SRC

+ stop pulseaudio

#+BEGIN_SRC sh
pulseaudio --kill
#+END_SRC

** bectl

See which boot environments you have.

#+BEGIN_SRC sh
bectl list
#+END_SRC

The only boot environment is named default. Under active, N means the environment is active now.  
An R means the environment will be active on reboot.

check the current version of freebsd with uname

#+BEGIN_SRC sh
uname -s
#+END_SRC

*** create new boot environment

I need to upgrade this host to the latest version of FreeBSD 12.0, p3.  
This is where we need a new boot environment. I’ll name it after the release.

run the bectl commands as root

#+BEGIN_SRC sh
doas bectl create 15.0-p0
#+END_SRC

list the boot environments

#+BEGIN_SRC sh
bectl list
#+END_SRC

Activate the new boot environment.

#+BEGIN_SRC sh
doas bectl activate 15.0-p0
#+END_SRC

list the boot environments

#+BEGIN_SRC sh
bectl list
#+END_SRC

While the default environment has an N, indicating it’s active now,
the 15.0-p0 environment has an R, so it will be active after a reboot.

Reboot. After the reboot, you’ll see the new environment is running.

**** install updates in new boot environment

check for package updates

#+BEGIN_SRC sh
pkg update
pkg upgrade
#+END_SRC

create a zfs snapshot

#+BEGIN_SRC sh
zfs snapshot -r zroot@14.0-p0
#+END_SRC

** unbound dns server

dont select local_unbound during freebsd setup

we will use the unbound package instead

install unbound dns server

#+BEGIN_SRC sh
doas pkg install unbound
#+END_SRC

enable unbound to start at boot 

We can use the sysrc command to disable the local_unbound service in /etc/rc.conf

#+BEGIN_SRC sh
sysrc local_unbound_enable="NO"
#+END_SRC

enable the unbound package dns server

#+BEGIN_SRC sh
sysrc unbound_enable="YES"
#+END_SRC

You can also edit the /etc/rc.conf as root to enable unbound

#+BEGIN_SRC sh
vi /etc/rc.conf
#+END_SRC

the local_unbound service should be set to NO

#+BEGIN_SRC sh
local_unbound_enable="NO"
#+END_SRC

and the unbound package version of unbound should be set to YES

#+BEGIN_SRC sh
unbound_enable="YES"
#+END_SRC

*** ca_root_nss install

Install the ca_root_nss package which contains the trusted internet root CA servers
This is used by unbound to create the root.key file which is auto trusted

#+BEGIN_SRC sh
pkg install ca_root_nss
#+END_SRC

*** unbound config

dnscrypt needs - do-not-query-localhost: no
in the custom.conf file in order to work

**** unbound.conf

Create a unbound.conf configuration file for unbound
switch to root and then create unbound.conf

#+BEGIN_SRC sh
doas /usr/local/etc/unbound/unbound.conf
#+END_SRC

#+BEGIN_SRC sh
#=========================================================================#
# unbound custom.conf
#=========================================================================#

server:
	verbosity: 1
	access-control: 0.0.0.0/0 refuse
	access-control: 127.0.0.0/8 allow
	access-control: ::0/0 refuse
	access-control: ::1 allow
	access-control: ::ffff:127.0.0.1 allow
	
	# enable to not answer id.server and hostname.bind queries.
	hide-identity: yes
	hide-version: yes
	harden-glue: yes
	harden-dnssec-stripped: yes

        # Ensure it's pointing to your updated anchor
        auto-trust-anchor-file: "/usr/local/etc/unbound/root.key"
        # dont query localhost needed for dnscrypt-proxy
        do-not-query-localhost: no

include: "/usr/local/etc/unbound/forward.conf"
#+END_SRC

**** unbound forward.conf

edit the unbound forward.conf file as root

#+BEGIN_SRC sh
doas vi /usr/local/etc/unbound/forward.conf
#+END_SRC

this will use dnscrypt as the forwarder

#+BEGIN_SRC sh
forward-zone:
	name: "."
	forward-addr: 127.0.0.1@5353
#+END_SRC

** dnscrypt-proxy2
*** dnscrypt-proxy2 install

dnscrypt-proxy2 and dns over https 

install dnscrypt-proxy as root

#+BEGIN_SRC sh
pkg install dnscrypt-proxy2
#+END_SRC

*** dnscrypt config
**** dnscrypt-proxy.toml

edit the dnscrypt-proxy.toml as root

#+BEGIN_SRC sh
vi /usr/local/etc/dnscrypt-proxy/dnscrypt-proxy.toml
#+END_SRC

+ dnscrypt-proxy.toml file
  
The complete dnscrypt-proxy.toml file should look like this

#+BEGIN_SRC sh
##############################################
#                                            #
#        dnscrypt-proxy configuration        #
#                                            #
##############################################

## This is an example configuration file.
## You should adjust it to your needs, and save it as "dnscrypt-proxy.toml"
##
## Online documentation is available here: https://dnscrypt.info/doc


###############################################################################
#                             Global settings                                  #
###############################################################################

## List of servers to use
##
## Servers from the "public-resolvers" source (see down below) can
## be viewed here: https://dnscrypt.info/public-servers
##
## The proxy will automatically pick working servers from this list.
## Note that the require_* filters do NOT apply when using this setting.
##
## By default, this list is empty and all registered servers matching the
## require_* filters will be used instead.
##
## Remove the leading # first to enable this; lines starting with # are ignored.

# server_names = ['scaleway-fr', 'google', 'yandex', 'cloudflare']
#server_names = ['quad9-dnscrypt-ip4-filter-pri', 'google', 'cloudflare']
#server_names = ['quad9-dnscrypt-ip4-core', 'google', 'cloudflare']
server_names = ['quad9-dnscrypt-ip4-filter-pri']

## List of local addresses and ports to listen to. Can be IPv4 and/or IPv6.
## Example with both IPv4 and IPv6:
## listen_addresses = ['127.0.0.1:5353']
##
## To listen to all IPv4 addresses, use `listen_addresses = ['0.0.0.0:53']`
## To listen to all IPv4+IPv6 addresses, use `listen_addresses = ['[::]:53']`

listen_addresses = ['127.0.0.1:5353']


## Maximum number of simultaneous client connections to accept

max_clients = 250


## Switch to a different system user after listening sockets have been created.
## Note (1): this feature is currently unsupported on Windows.
## Note (2): this feature is not compatible with systemd socket activation.
## Note (3): when using -pidfile, the PID file directory must be writable by the new user

# user_name = 'nobody'


###############################################################################
#                            Server Selection                                  #
###############################################################################

## Require servers (from remote sources) to satisfy specific properties

# Use servers reachable over IPv4
ipv4_servers = true

# Use servers reachable over IPv6 -- Do not enable if you don't have IPv6 connectivity
ipv6_servers = false

# Use servers implementing the DNSCrypt protocol
dnscrypt_servers = true

# Use servers implementing the DNS-over-HTTPS protocol
doh_servers = true

# Use servers implementing the Oblivious DoH protocol
odoh_servers = false


## Require servers defined by remote sources to satisfy specific properties

# Server must support DNS security extensions (DNSSEC)
require_dnssec = false

# Server must not log user queries (declarative)
require_nolog = false

# Server must not enforce its own blocklist (for parental control, ads blocking...)
require_nofilter = false

# Server names to avoid even if they match all criteria
disabled_server_names = []


###############################################################################
#                           Connection Settings                                #
###############################################################################

## Always use TCP to connect to upstream servers.
## This can be useful if you need to route everything through Tor.
## Otherwise, leave this to `false`, as it doesn't improve security
## (dnscrypt-proxy will always encrypt everything even using UDP), and can
## only increase latency.

force_tcp = false


## Enable support for HTTP/3 (HTTP over QUIC)
## Note that, like DNSCrypt but unlike other HTTP versions, this uses
## UDP and (usually) port 443 instead of TCP.

http3 = false

## When http3 is true, always try HTTP/3 first for DoH servers.
## If the HTTP/3 connection fails, fallback to HTTP/2 and don't try
## HTTP/3 again for that server. By default, HTTP/3 is only used for
## servers that advertise support via the Alt-Svc header.
##
## WARNING: This setting is disabled by default because it will make
## connections significantly slower for servers that don't support HTTP/3.
## This is primarily a workaround for server operators who haven't
## configured their servers to send proper Alt-Svc headers. The better
## solution is to reach out to these operators and encourage them to
## fix their servers to correctly advertise HTTP/3 support.

http3_probe = false


## SOCKS proxy
## Uncomment the following line to route all TCP connections to a local Tor node
## Tor doesn't support UDP, so set `force_tcp` to `true` as well. When passing
## a random username and password to Tor's socks5 connection, dnscrypt-proxy gets
## an isolated circuit so it will not share an exit node with other applications.
## Note: the random username and password used by dnscrypt-proxy should not
## actually be defined in Tor's configuration.

# proxy = 'socks5://dnscrypt:dnscrypt@127.0.0.1:9050'


## HTTP/HTTPS proxy
## Only for DoH servers

# http_proxy = 'http://127.0.0.1:8888'


## How long a DNS query will wait for a response, in milliseconds.
## If you have a network with *a lot* of latency, you may need to
## increase this. Startup may be slower if you do so.
## Don't increase it too much. 10000 is the highest reasonable value.
## A timeout below 5000 is not recommended.

timeout = 5000


## Keepalive for HTTP (HTTPS, HTTP/2, HTTP/3) queries, in seconds

keepalive = 30


## Add EDNS-client-subnet information to outgoing queries
##
## Multiple networks can be listed; they will be randomly chosen.
## These networks don't have to match your actual networks.

# edns_client_subnet = ['0.0.0.0/0', '2001:db8::/32']


## Response for blocked queries. Options are `refused`, `hinfo` (default) or
## an IP response. To give an IP response, use the format `a:<IPv4>,aaaa:<IPv6>`.
## Using the `hinfo` option means that some responses will be lies.
## Unfortunately, the `hinfo` option appears to be required for Android 8+

# blocked_query_response = 'refused'


###############################################################################
#                        Load Balancing & Performance                          #
###############################################################################

## Load-balancing strategy: 'wp2' (default), 'p2', 'ph', 'p<n>', 'first', or 'random'
## 'wp2' (default): Weighted Power of Two - selects the better performing server
## from two random candidates based on real-time RTT and success rates.
## 'p2': Randomly choose 1 of the fastest 2 servers by latency.
## 'ph': Randomly choose from fastest half of servers.
## 'p<n>': Randomly choose from fastest n servers (e.g., 'p3' for fastest 3).
## 'first': Always use the fastest server.
## 'random': Randomly choose from all servers.
## The response quality still depends on the server itself.

# lb_strategy = 'wp2'

## Set to `true` to constantly try to estimate the latency of all the resolvers
## and adjust the load-balancing parameters accordingly, or to `false` to disable.
## Default is `true` that makes 'p2' `lb_strategy` work well.

# lb_estimator = true

## Dynamically reduce query timeout as the number of concurrent connections
## approaches max_clients to prevent overload. Value must be between 0.0 and 1.0.
## 0.0 = no reduction, 1.0 = maximum reduction.
## Uses a quartic curve to keep timeout high at low load and reduce sharply near limit.
## For example, with timeout=5000ms, max_clients=250, and timeout_load_reduction=0.75:
## - At 125 connections (50% load): timeout remains ~4765ms (95.3%)
## - At 187 connections (75% load): timeout reduces to ~3826ms (76.5%)
## - At 225 connections (90% load): timeout reduces to ~2539ms (50.8%)
## - At 250 connections (100% load): timeout reduces to ~1250ms (25%)
## This helps maintain responsiveness under high load by failing fast.

# timeout_load_reduction = 0.75

## Set to `true` to enable hot reloading of configuration files (like allowed-names.txt,
## blocked-names.txt, etc.) when they are modified. This can increase CPU and memory usage.
## Default is `false` (hot reloading is disabled).

# enable_hot_reload = false


###############################################################################
#                                Logging                                       #
###############################################################################

## Log level (0-6, default: 2 - 0 is very verbose, 6 only contains fatal errors)

# log_level = 2


## Log file for the application, as an alternative to sending logs to
## the standard system logging service (syslog/Windows event log).
##
## This file is different from other log files, and will not be
## automatically rotated by the application.

# log_file = 'dnscrypt-proxy.log'


## When using a log file, only keep logs from the most recent launch.

# log_file_latest = true


## Use the system logger (syslog on Unix, Event Log on Windows)

# use_syslog = true


## Automatic log files rotation

# Maximum log files size in MB - Set to 0 for unlimited.
log_files_max_size = 10

# How long to keep backup files, in days
log_files_max_age = 7

# Maximum log files backups to keep (or 0 to keep all backups)
log_files_max_backups = 1


###############################################################################
#                           Certificate Management                             #
###############################################################################

## The maximum concurrency to reload certificates from the resolvers.
## Default is 10.

# cert_refresh_concurrency = 10


## Delay, in minutes, after which certificates are reloaded

cert_refresh_delay = 240


## Initially don't check DNSCrypt server certificates for expiration, and
## only start checking them after a first successful connection to a resolver.
## This can be useful on routers with no battery-backed clock.

# cert_ignore_timestamp = false


## DNSCrypt: Create a new, unique key for every single DNS query
## This may improve privacy but can also have a significant impact on CPU usage
## Only enable if you don't have a lot of network load

# dnscrypt_ephemeral_keys = false


## DoH: Disable TLS session tickets - increases privacy but also latency

# tls_disable_session_tickets = false


## DoH: Use TLS 1.2 and specific cipher suite instead of the server preference
## 49199 = TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
## 49195 = TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
## 52392 = TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
## 52393 = TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
##
## On non-Intel CPUs such as MIPS routers and ARM systems (Android, Raspberry Pi...),
## uncommenting the following line may improve performance.
## This may also help on Intel CPUs running 32-bit operating systems.
## However, this can cause issues fetching sources or connecting to some HTTP servers,
## and should not be set on regular CPUs.
##
## Keep tls_cipher_suite undefined to let the app automatically choose secure parameters.

# tls_cipher_suite = [52392, 49199]


## Log TLS key material to a file, for debugging purposes only.
## This file will contain the TLS master key, which can be used to decrypt
## all TLS traffic to/from DoH servers.
## Never ever enable except for debugging purposes with a tool such as mitmproxy.

# tls_key_log_file = '/tmp/keylog.txt'


###############################################################################
#                            Startup & Network                                 #
###############################################################################

## Bootstrap resolvers
##
## These are normal, non-encrypted DNS resolvers, that will be only used
## for one-shot queries when retrieving the initial resolvers list and if
## the system DNS configuration doesn't work.
##
## No user queries will ever be leaked through these resolvers, and they will
## not be used after IP addresses of DoH resolvers have been found (if you are
## using DoH).
##
## They will never be used if lists have already been cached, and if the stamps
## of the configured servers already include IP addresses (which is the case for
## most of DoH servers, and for all DNSCrypt servers and relays).
##
## They will not be used if the configured system DNS works, or after the
## proxy already has at least one usable secure resolver.
##
## Resolvers supporting DNSSEC are recommended, and, if you are using
## DoH, bootstrap resolvers should ideally be operated by a different entity
## than the DoH servers you will be using, especially if you have IPv6 enabled.
##
## People in China may want to use 114.114.114.114:53 here.
## Other popular options include 8.8.8.8, 9.9.9.9 and 1.1.1.1.
##
## If more than one resolver is specified, they will be tried in sequence.
##
## TL;DR: put valid standard resolver addresses here. Your actual queries will
## not be sent there. If you're using DNSCrypt or Anonymized DNS and your
## lists are up to date, these resolvers will not even be used.

bootstrap_resolvers = ['9.9.9.11:53', '8.8.8.8:53']


## When internal DNS resolution is required, for example to retrieve
## the resolvers list:
##
## - queries will be sent to dnscrypt-proxy itself, if it is already
##   running with active servers (*)
## - or else, queries will be sent to fallback servers
## - finally, if `ignore_system_dns` is `false`, queries will be sent
##   to the system DNS
##
## (*) this is incompatible with systemd sockets.
## `listen_addresses` must not be empty.

ignore_system_dns = true


## Maximum time (in seconds) to wait for network connectivity before
## initializing the proxy.
## Useful if the proxy is automatically started at boot, and network
## connectivity is not guaranteed to be immediately available.
## Use 0 to not test for connectivity at all (not recommended),
## and -1 to wait as much as possible.

netprobe_timeout = 60

## Address and port to try initializing a connection to, just to check
## if the network is up. It can be any address and any port, even if
## there is nothing answering these on the other side. Just don't use
## a local address, as the goal is to check for Internet connectivity.
## On Windows, a datagram with a single, nul byte will be sent, only
## when the system starts.
## On other operating systems, the connection will be initialized
## but nothing will be sent at all.

netprobe_address = '9.9.9.9:53'


## Offline mode - Do not use any remote encrypted servers.
## The proxy will remain fully functional to respond to queries that
## plugins can handle directly (forwarding, cloaking, ...)

# offline_mode = false


## Additional data to attach to outgoing queries.
## These strings will be added as TXT records to queries.
## Do not use, except on servers explicitly asking for extra data
## to be present.
## encrypted-dns-server can be configured to use this for access control
## in the [access_control] section

# query_meta = ['key1:value1', 'key2:value2', 'token:MySecretToken']


###############################################################################
#                                 Filters                                      #
###############################################################################

## Note: if you are using dnsmasq, disable the `dnssec` option in dnsmasq if you
## configure dnscrypt-proxy to do any kind of filtering (including the filters
## below and blocklists).
## You can still choose resolvers that do DNSSEC validation.


## Immediately respond to IPv6-related queries with an empty response
## This makes things faster when there is no IPv6 connectivity, but can
## also cause reliability issues with some stub resolvers.

block_ipv6 = true


## Immediately respond to A and AAAA queries for host names without a domain name
## This also prevents "dotless domain names" from being resolved upstream.

block_unqualified = true


## Immediately respond to queries for local zones instead of leaking them to
## upstream resolvers (always causing errors or timeouts).

block_undelegated = true


## TTL for synthetic responses sent when a request has been blocked (due to
## IPv6 or blocklists).

reject_ttl = 10


###############################################################################
#                              Forwarding                                      #
###############################################################################

## Route queries for specific domains to a dedicated set of servers

## See the `example-forwarding-rules.txt` file for an example

# forwarding_rules = 'forwarding-rules.txt'


###############################################################################
#                              Cloaking                                        #
###############################################################################

## Cloaking returns a predefined address for a specific name.
## In addition to acting as a HOSTS file, it can also return the IP address
## of a different name. It will also do CNAME flattening.
## If 'cloak_ptr' is set, then PTR (reverse lookups) are enabled
## for cloaking rules that do not contain wild cards.
##
## See the `example-cloaking-rules.txt` file for an example

# cloaking_rules = 'cloaking-rules.txt'

## TTL used when serving entries in cloaking-rules.txt

# cloak_ttl = 600
# cloak_ptr = false


###############################################################################
#                                DNS Cache                                     #
###############################################################################

## Enable a DNS cache to reduce latency and outgoing traffic

cache = false


## Cache size

cache_size = 4096


## Minimum TTL for cached entries

cache_min_ttl = 2400


## Maximum TTL for cached entries

cache_max_ttl = 86400


## Minimum TTL for negatively cached entries

cache_neg_min_ttl = 60


## Maximum TTL for negatively cached entries

cache_neg_max_ttl = 600


###############################################################################
#                           Captive portal handling                            #
###############################################################################

[captive_portals]

## A file that contains a set of names used by operating systems to
## check for connectivity and captive portals, along with hard-coded
## IP addresses to return.

# map_file = 'example-captive-portals.txt'


###############################################################################
#                            Local DoH server                                  #
###############################################################################

[local_doh]

## dnscrypt-proxy can act as a local DoH server. By doing so, web browsers
## requiring a direct connection to a DoH server in order to enable some
## features will enable these, without bypassing your DNS proxy.

## Addresses that the local DoH server should listen to

# listen_addresses = ['127.0.0.1:3000']


## Path of the DoH URL. This is not a file, but the part after the hostname
## in the URL. By convention, `/dns-query` is frequently chosen.
## For each `listen_address` the complete URL to access the server will be:
## `https://<listen_address><path>` (ex: `https://127.0.0.1/dns-query`)

# path = '/dns-query'


## Certificate file and key - Note that the certificate has to be trusted.
## Can be generated using the following command:
## openssl req -x509 -nodes -newkey rsa:2048 -days 5000 -sha256 -keyout localhost.pem -out localhost.pem
## See the documentation (wiki) for more information.

# cert_file = 'localhost.pem'
# cert_key_file = 'localhost.pem'


###############################################################################
#                              Query logging                                   #
###############################################################################

[query_log]

## Path to the query log file (absolute, or relative to the same directory as the config file)
## Can be set to /dev/stdout in order to log to the standard output.

# file = 'query.log'


## Query log format (currently supported: tsv and ltsv)

format = 'tsv'


## Do not log these query types, to reduce verbosity. Keep empty to log everything.

# ignored_qtypes = ['DNSKEY', 'NS']


###############################################################################
#                        Suspicious queries logging                            #
###############################################################################

[nx_log]

## Log queries for nonexistent zones
## These queries can reveal the presence of malware, broken/obsolete applications,
## and devices signaling their presence to 3rd parties.

## Path to the query log file (absolute, or relative to the same directory as the config file)

# file = 'nx.log'


## Query log format (currently supported: tsv and ltsv)

format = 'tsv'


###############################################################################
#                    Pattern-based blocking (blocklists)                       #
###############################################################################

## Blocklists are made of one pattern per line. Example of valid patterns:
##
##   example.com
##   =example.com
##   *sex*
##   ads.*
##   ads*.example.*
##   ads*.example[0-9]*.com
##
## Example blocklist files can be found at https://download.dnscrypt.info/blocklists/
## A script to build blocklists from public feeds can be found in the
## `utils/generate-domains-blocklists` directory of the dnscrypt-proxy source code.

[blocked_names]

## Path to the file of blocking rules (absolute, or relative to the same directory as the config file)

# blocked_names_file = 'blocked-names.txt'


## Optional path to a file logging blocked queries

# log_file = 'blocked-names.log'


## Optional log format: tsv or ltsv (default: tsv)

# log_format = 'tsv'


###############################################################################
#                  Pattern-based IP blocking (IP blocklists)                   #
###############################################################################

## IP blocklists are made of one pattern per line. Example of valid patterns:
##
##   127.*
##   fe80:abcd:*
##   192.168.1.4

[blocked_ips]

## Path to the file of blocking rules (absolute, or relative to the same directory as the config file)

# blocked_ips_file = 'blocked-ips.txt'


## Optional path to a file logging blocked queries

# log_file = 'blocked-ips.log'


## Optional log format: tsv or ltsv (default: tsv)

# log_format = 'tsv'


###############################################################################
#                 Pattern-based allow lists (blocklists bypass)                #
###############################################################################

## Allowlists support the same patterns as blocklists
## If a name matches an allowlist entry, the corresponding session
## will bypass names and IP filters.
##
## Time-based rules are also supported to make some websites only accessible at specific times of the day.

[allowed_names]

## Path to the file of allow list rules (absolute, or relative to the same directory as the config file)

# allowed_names_file = 'allowed-names.txt'


## Optional path to a file logging allowed queries

# log_file = 'allowed-names.log'


## Optional log format: tsv or ltsv (default: tsv)

# log_format = 'tsv'


###############################################################################
#           Pattern-based allowed IPs lists (blocklists bypass)                #
###############################################################################

## Allowed IP lists support the same patterns as IP blocklists
## If an IP response matches an allowed entry, the corresponding session
## will bypass IP filters.
##
## Time-based rules are also supported to make some websites only accessible at specific times of the day.

[allowed_ips]

## Path to the file of allowed ip rules (absolute, or relative to the same directory as the config file)

# allowed_ips_file = 'allowed-ips.txt'


## Optional path to a file logging allowed queries

# log_file = 'allowed-ips.log'

## Optional log format: tsv or ltsv (default: tsv)

# log_format = 'tsv'


###############################################################################
#                        Time access restrictions                              #
###############################################################################

## One or more weekly schedules can be defined here.
## Patterns in the name-based blocked_names file can optionally be followed with @schedule_name
## to apply the pattern 'schedule_name' only when it matches a time range of that schedule.
##
## For example, the following rule in a blocklist file:
## *.youtube.* @time-to-sleep
## would block access to YouTube during the times defined by the 'time-to-sleep' schedule.
##
## {after='21:00', before= '7:00'} matches 0:00-7:00 and 21:00-0:00
## {after= '9:00', before='18:00'} matches 9:00-18:00

[schedules]

# [schedules.time-to-sleep]
#   mon = [{after='21:00', before='7:00'}]
#   tue = [{after='21:00', before='7:00'}]
#   wed = [{after='21:00', before='7:00'}]
#   thu = [{after='21:00', before='7:00'}]
#   fri = [{after='23:00', before='7:00'}]
#   sat = [{after='23:00', before='7:00'}]
#   sun = [{after='21:00', before='7:00'}]

# [schedules.work]
#   mon = [{after='9:00', before='18:00'}]
#   tue = [{after='9:00', before='18:00'}]
#   wed = [{after='9:00', before='18:00'}]
#   thu = [{after='9:00', before='18:00'}]
#   fri = [{after='9:00', before='17:00'}]


###############################################################################
#                                Servers                                       #
###############################################################################

## Remote lists of available servers
## Multiple sources can be used simultaneously, but every source
## requires a dedicated cache file.
##
## Refer to the documentation for URLs of public sources.
##
## A prefix can be prepended to server names in order to
## avoid collisions if different sources share the same for
## different servers. In that case, names listed in `server_names`
## must include the prefixes.
##
## If the `urls` property is missing, cache files and valid signatures
## must already be present. This doesn't prevent these cache files from
## expiring after `refresh_delay` hours.
## `refreshed_delay` must be in the [24..168] interval.
## The minimum delay of 24 hours (1 day) avoids unnecessary requests to servers.
## The maximum delay of 168 hours (1 week) ensures cache freshness.

[sources]

### An example of a remote source from https://github.com/DNSCrypt/dnscrypt-resolvers

[sources.public-resolvers]
urls = [
  'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md',
  'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md',
]
cache_file = 'public-resolvers.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 73
prefix = ''

### Anonymized DNS relays

[sources.relays]
urls = [
  'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md',
  'https://download.dnscrypt.info/resolvers-list/v3/relays.md',
]
cache_file = 'relays.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 73
prefix = ''

### ODoH (Oblivious DoH) servers and relays

# [sources.odoh-servers]
#   urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/odoh-servers.md', 'https://download.dnscrypt.info/resolvers-list/v3/odoh-servers.md']
#   cache_file = 'odoh-servers.md'
#   minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
#   refresh_delay = 73
#   prefix = ''
# [sources.odoh-relays]
#   urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/odoh-relays.md', 'https://download.dnscrypt.info/resolvers-list/v3/odoh-relays.md']
#   cache_file = 'odoh-relays.md'
#   minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
#   refresh_delay = 73
#   prefix = ''

### Quad9

# [sources.quad9-resolvers]
#   urls = ['https://quad9.net/dnscrypt/quad9-resolvers.md']
#   minisign_key = 'RWQBphd2+f6eiAqBsvDZEBXBGHQBJfeG6G+wJPPKxCZMoEQYpmoysKUN'
#   cache_file = 'quad9-resolvers.md'
#   prefix = 'quad9-'

### Another example source, with resolvers censoring some websites not appropriate for children
### This is a subset of the `public-resolvers` list, so enabling both is useless.

# [sources.parental-control]
#   urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/parental-control.md', 'https://download.dnscrypt.info/resolvers-list/v3/parental-control.md']
#   cache_file = 'parental-control.md'
#   minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'

### dnscry.pt servers - See https://www.dnscry.pt

#  [sources.dnscry-pt-resolvers]
#    urls = ["https://www.dnscry.pt/resolvers.md"]
#    minisign_key = "RWQM31Nwkqh01x88SvrBL8djp1NH56Rb4mKLHz16K7qsXgEomnDv6ziQ"
#    cache_file = "dnscry.pt-resolvers.md"
#    refresh_delay = 73
#    prefix = "dnscry.pt-"


###############################################################################
#                        Servers with known bugs                               #
###############################################################################

[broken_implementations]

## Cisco servers currently cannot handle queries larger than 1472 bytes, and don't
## truncate responses larger than questions as expected by the DNSCrypt protocol.
## This prevents large responses from being received over UDP and over relays.
##
## Older versions of the `dnsdist` server software had a bug with queries larger
## than 1500 bytes. This is fixed since `dnsdist` version 1.5.0, but
## some server may still run an outdated version.
##
## The list below enables workarounds to make non-relayed usage more reliable
## until the servers are fixed.

fragments_blocked = [
  'cisco',
  'cisco-ipv6',
  'cisco-familyshield',
  'cisco-familyshield-ipv6',
  'cisco-sandbox',
  'cleanbrowsing-adult',
  'cleanbrowsing-adult-ipv6',
  'cleanbrowsing-family',
  'cleanbrowsing-family-ipv6',
  'cleanbrowsing-security',
  'cleanbrowsing-security-ipv6',
]


###############################################################################
#                Certificate-based client authentication for DoH               #
###############################################################################

[doh_client_x509_auth]

## Use an X509 certificate to authenticate yourself when connecting to DoH servers.
## This is only useful if you are operating your own, private DoH server(s).
## 'creds' maps servers to certificates, and supports multiple entries.
## If you are not using the standard root CA, an optional "root_ca"
## property set to the path to a root CRT file can be added to a server entry.

# creds = [
#    { server_name='*', client_cert='client.crt', client_key='client.key' }
# ]


###############################################################################
#                          Anonymized DNS                                      #
###############################################################################

[anonymized_dns]

## Routes are indirect ways to reach DNSCrypt servers.
##
## A route maps a server name ("server_name") to one or more relays that will be
## used to connect to that server.
##
## A relay can be specified as a DNS Stamp (either a relay stamp, or a
## DNSCrypt stamp) or a server name.
##
## The following example routes "example-server-1" via `anon-example-1` or `anon-example-2`,
## and "example-server-2" via the relay whose relay DNS stamp is
## "sdns://gRIxMzcuNzQuMjIzLjIzNDo0NDM".
##
## !!! THESE ARE JUST EXAMPLES !!!
##
## Review the list of available relays from the "relays.md" file, and, for each
## server you want to use, define the relays you want connections to go through.
##
## Carefully choose relays and servers so that they are run by different entities.
##
## "server_name" can also be set to "*" to define a default route, for all servers:
## { server_name='*', via=['anon-example-1', 'anon-example-2'] }
##
## If a route is ["*"], the proxy automatically picks a relay on a distinct network.
## { server_name='*', via=['*'] } is also an option, but is likely to be suboptimal.
##
## Manual selection is always recommended over automatic selection, so that you can
## select (relay,server) pairs that work well and fit your own criteria (close by or
## in different countries, operated by different entities, on distinct ISPs...)

# routes = [
#    { server_name='example-server-1', via=['anon-example-1', 'anon-example-2'] },
#    { server_name='example-server-2', via=['sdns://gRIxMzcuNzQuMjIzLjIzNDo0NDM'] }
# ]


## Skip resolvers incompatible with anonymization instead of using them directly

skip_incompatible = false


## If public server certificates for a non-conformant server cannot be
## retrieved via a relay, try getting them directly. Actual queries
## will then always go through relays.

# direct_cert_fallback = false


###############################################################################
#                                 DNS64                                        #
###############################################################################

[dns64]

## DNS64 is a mechanism for synthesizing AAAA records from A records.
## It is used with an IPv6/IPv4 translator to enable client-server
## communication between an IPv6-only client and an IPv4-only server,
## without requiring any changes to either the IPv6 or the IPv4 node,
## for the class of applications that work through NATs.
##
## There are two options to synthesize such records:
## Option 1: Using a set of static IPv6 prefixes;
## Option 2: By discovering the IPv6 prefix from DNS64-enabled resolver.
##
## If both options are configured - only static prefixes are used.
## (Ref. RFC6147, RFC6052, RFC7050)
##
## Do not enable unless you know what DNS64 is and why you need it, or else
## you won't be able to connect to anything at all.

## Static prefix(es) as Pref64::/n CIDRs

# prefix = ['64:ff9b::/96']

## DNS64-enabled resolver(s) to discover Pref64::/n CIDRs
## These resolvers are used to query for Well-Known IPv4-only Name (WKN) "ipv4only.arpa." to discover only.
## Set with your ISP's resolvers in case of custom prefixes (other than Well-Known Prefix 64:ff9b::/96).
## IMPORTANT: Default resolvers listed below support Well-Known Prefix 64:ff9b::/96 only.

# resolver = ['[2606:4700:4700::64]:53', '[2001:4860:4860::64]:53']


###############################################################################
#                           IP Encryption                                      #
###############################################################################

[ip_encryption]

## Encrypt client IP addresses in plugin logs using IPCrypt
## This provides privacy for client IP addresses while maintaining
## the ability to distinguish between different clients in logs

## Encryption algorithm (default: "none")
## - "none": No encryption (default)
## - "ipcrypt-deterministic": Deterministic encryption (same IP always encrypts to same value) - requires 16-byte key
## - "ipcrypt-nd": Non-deterministic encryption with 8-byte tweak - requires 16-byte key
## - "ipcrypt-ndx": Non-deterministic encryption with 16-byte tweak (extended) - requires 32-byte key
## - "ipcrypt-pfx": Prefix-preserving encryption (preserves network prefix relationships) - requires 32-byte key

algorithm = "none"

## Encryption key in hexadecimal format (required if algorithm is not "none")
## Key size depends on algorithm:
## - ipcrypt-deterministic: 32 hex chars (16 bytes) - Generate with: openssl rand -hex 16
## - ipcrypt-nd: 32 hex chars (16 bytes) - Generate with: openssl rand -hex 16
## - ipcrypt-ndx: 64 hex chars (32 bytes) - Generate with: openssl rand -hex 32
## Example for deterministic/nd: key = "1234567890abcdef1234567890abcdef"
## Example for ndx: key = "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
## IMPORTANT: Keep this key secret

key = ""


###############################################################################
#                            Monitoring UI                                     #
###############################################################################

[monitoring_ui]

## Enable the monitoring UI
enabled = false

## Listen address for the monitoring UI
listen_address = "127.0.0.1:8080"

## Optional username and password for basic authentication
## To disable authentication, set username to an empty string: username = ""
## If both username and password are empty, no authentication is required
username = "admin"
password = "changeme"

## Optional TLS certificate and key for HTTPS
## If both are empty, HTTP will be used
tls_certificate = ""
tls_key = ""

## Enable query logging in the monitoring UI
## This will show recent queries in the UI
enable_query_log = true

## Privacy level for the monitoring UI
## 0: show all details including client IPs
## 1: anonymize client IPs (default)
## 2: aggregate data only (no individual queries or domains shown)
privacy_level = 1

## Maximum number of recent query log entries to keep in memory
## Helps control memory usage on high-traffic servers
## Default: 100
# max_query_log_entries = 100

## Maximum memory usage in MB for recent query logs
## Automatic cleanup when limit is exceeded
## Default: 1
# max_memory_mb = 1

## Enable Prometheus metrics endpoint
## Default: false
# prometheus_enabled = false

## Path for Prometheus metrics endpoint
## Default: /metrics
# prometheus_path = "/metrics"


###############################################################################
#                            Static entries                                    #
###############################################################################

[static]

## Optional, local, static list of additional servers
## Mostly useful for testing your own servers.

# [static.myserver]
#   stamp = 'sdns://AQcAAAAAAAAAAAAQMi5kbnNjcnlwdC1jZXJ0Lg'
#+END_SRC

**** rc.conf

use the sysrc command as root to add commands to /etc/rc.conf

#+BEGIN_SRC sh
sudo sysrc dnscrypt_proxy_enable="YES"
sudo sysrc dnscrypt_proxy_pidfile="/var/run/dnscrypt-proxy.pid"
sudo sysrc dnscrypt_proxy_logfile="/var/log/dnscrypt-proxy.log"
#+END_SRC

we also need to enable unbound in the /etc/rc.conf

#+BEGIN_SRC sh
# unbound dns
local_unbound_enable="NO"
unbound_enable="YES"
# dnscrypt
dnscrypt_proxy_enable="YES"
dnscrypt_proxy_pidfile="/var/run/dnscrypt-proxy.pid"
dnscrypt_proxy_logfile="/var/log/dnscrypt-proxy.log"
#+END_SRC

**** resolv.conf

Stop unbound dns server and take down interfaces before editing resolv.conf

edit /etc/resolv.conf as root

#+begin_src sh
doas vi /etc/resolv.conf
#+end_src

#+BEGIN_SRC sh
# Generated by resolvconf
search localdomain
nameserver 127.0.0.1
options edns0
#+END_SRC

avoid overwriting /etc/resolv.conf

edit /etc/dhclient-enter-hooks as root

#+BEGIN_SRC sh
doas vi /etc/dhclient-enter-hooks
#+END_SRC

add the following to /etc/dhclient-enter-hooks

#+BEGIN_SRC sh
add_new_resolv_conf() {
  # We don't want /etc/resolv.conf changed
  # So this is an empty function
  return 0
}
#+END_SRC

protect your /etc/resolv.conf from being modified by setting the immutable (write-protection) attribute as root

#+BEGIN_SRC sh
chattr +i /etc/resolv.conf
#+END_SRC

restart unbound

#+begin_src sh
doas service unbound restart
#+end_src

*** dnscrypt check

dnscrypt-proxy -resolve google.com -config /usr/local/etc/dnscrypt-proxy/dnscrypt-proxy.toml

website to test dnsec is working

[[https://dnssec.vs.uni-due.de/][dnsec test]]

check you are using quad9

[[https://on.quad9.net/]]

** ssh-agent and ssh-add

start the ssh-agent

#+begin_src sh
eval $(ssh-agent)
#+end_src

run ssh-add and enter the password for your ssh key

#+begin_src sh
ssh-add
#+end_src

** gpg

To export your secret keys, use:

#+begin_src sh
gpg --export-secret-key -a > secret.key
#+end_src

and to import them again:

#+begin_src sh
gpg --import secret.key
#+end_src

create the gpg-agent.conf file

#+begin_src sh
vi ~/.gnupg/gpg-agent.conf
#+end_src

add the following code

#+begin_src conf
pinentry-program /usr/local/bin/pinentry-curses
default-cache-ttl 36000
max-cache-ttl 36000
#+end_src

** bluetooth freebsd stop

#+BEGIN_SRC sh
sudo service bluetooth onestop ubt0
#+END_SRC

** mount drives devfs rules
	
add user to operator group

#+begin_src sh
sudo pw groupmod operator -m djwilcox
#+end_src

Edit /etc/devfs.rules to allow the operator group to be able to read and write the device:

#+begin_src sh
sudo vi /etc/devfs.rules
#+end_src

/etc/devfs.rules


#+begin_src sh
[localrules=5]
add path 'da*' mode 0660 group operator
#+end_src

Then edit /etc/rc.conf to enable the devfs.rules(5) ruleset:

#+begin_src sh
sudo vi /etc/rc.conf
#+end_src

#+begin_src sh
devfs_system_ruleset="localrules"
#+end_src

or use sysrc instead

#+begin_src sh
sudo sysrc devfs_system_ruleset="localrules"
#+end_src

Next allow regular user to mount file system:

#+begin_src sh
sudo vi /etc/sysctl.conf
#+end_src

#+begin_src sh
vfs.usermount=1
#+end_src

Also execute sysctl to make the update available now:

#+begin_src sh
sudo sysctl vfs.usermount=1
#+end_src

vfs.usermount: 0 -> 1

Create a directory which a regular use can mount to:

#+begin_src sh
sudo mkdir -p /mnt/usb
#+end_src

change the permission so your user own the directory with chown
replace username with your username

#+begin_src sh
sudo chown username:username /mnt/usb
#+end_src

** ext2fs

enable ext2fs with sysrc

#+begin_src sh
sudo sysrc kld_list="ext2fs"
#+end_src

or edit your /etc/rc.conf manually

#+begin_src sh
sudo vi /etc/rc.conf
#+end_src

enable ext2fs by adding the following code to your rc.conf

#+begin_src conf
kld_list="ext2fs"
#+end_src

To load as a kernel loadable module:

#+begin_src sh
sudo kldload ext2fs
#+end_src

To mount a ext2fs volume located on /dev/ada1s1:

#+begin_src sh
mount -t ext2fs /dev/ada1s1 /mnt/usb
#+end_src

alternative command

#+begin_src sh
doas fuse-ext2 /dev/da0p1 /home/djwilcox/mnt -o rw+,uid=1001,gid=1001
#+end_src

** chromium widevine
*** chromium install

#+begin_src sh
sudo pkg install chromium
#+end_src

*** linux enable

#+begin_src sh
sudo sysrc linux_enable="YES"
sudo service linux start
#+end_src

*** tmpfs and nullfs

make sure you have switched to root

enable tmpfs and nullfs in loader.conf
then use kldload to load them

#+begin_src sh
sysrc -f /boot/loader.conf nullfs_load=YES
kldload -n nullfs
sysrc -f /boot/loader.conf tmpfs_load=YES
kldload -n tmpfs
#+end_src

*** fstab

Some programs need linprocfs mounted on /compat/linux/proc.
Add the following line to /etc/fstab:

#+begin_src conf
linprocfs   /compat/linux/proc	linprocfs	rw	0	0
#+end_src

Then run "mount /compat/linux/proc".

#+begin_src sh
sudo mount /compat/linux/proc
#+end_src

Some programs need linsysfs mounted on /compat/linux/sys.
Add the following line to /etc/fstab:

#+begin_src conf
linsysfs    /compat/linux/sys	linsysfs	rw	0	0
#+end_src

Then run "mount /compat/linux/sys".

#+begin_src sh
sudo mount /compat/linux/sys
#+end_src

*** foreign-cdm

#+begin_src sh
sudo pkg install foreign-cdm
#+end_src

*** poudriere

switch to root using either sudo or doas

+ switch to root using sudo 

#+BEGIN_SRC sh
sudo su
#+END_SRC

+ or use doas to switch to root

#+BEGIN_SRC sh
doas su
#+END_SRC

*** Create an SSL Certificate and Key

When we build packages with poudriere, we want to be able to sign them with a private key. This will ensure all of our machines that the packages created are legitimate and that nobody is intercepting the connection to the build machine to serve malicious packages.

To start off, we will create a directory structure for our key and certificate. Since all of our optional software configuration takes place within the /usr/local/etc directory, and because other software uses the /usr/local/etc/ssl location, this is where we will place our files.

We will ensure that we have an ssl directory that contains two subdirectories called keys and certs.

all command must be run as root

#+BEGIN_SRC sh
mkdir -p /usr/local/etc/ssl/keys
mkdir -p /usr/local/etc/ssl/certs
#+END_SRC

Our private key, which must be kept secret, will be placed in the keys directory. This will be used to sign the packages that we will be creating. Keeping this secure is essential to ensuring that our packages are not being tampered with. We can lock down the directory so that users without root or sudo privileges will be unable to interact with the directory or its contents:

#+BEGIN_SRC sh
chmod 0600 /usr/local/etc/ssl/keys
#+END_SRC

The certs directory will contain our publicly available certificate created with the key. As such, we can leave the default permissions on that directory.

Next, we will generate a 4096 bit key called poudriere.key, and place it in our keys directory by typing:

#+BEGIN_SRC sh
openssl genrsa -out /usr/local/etc/ssl/keys/poudriere.key 4096
#+END_SRC

After the key is generated, we can create a public cert from it by typing:

#+BEGIN_SRC sh
openssl rsa -in /usr/local/etc/ssl/keys/poudriere.key -pubout -out /usr/local/etc/ssl/certs/poudriere.cert
#+END_SRC

We now have the SSL components we need to sign packages and verify the signatures. Later on, we will configure our clients to use the generated certificate for package verification.

*** poudriere install

#+BEGIN_SRC sh
pkg install poudriere
#+END_SRC

*** create the distfiles directory

#+BEGIN_SRC sh
mkdir -p /usr/ports/distfiles
#+END_SRC

edit the poudriere.conf file

#+BEGIN_SRC sh
vi /usr/local/etc/poudriere.conf
#+END_SRC

change the poudriere.conf so it looks like this

#+BEGIN_SRC sh
# Poudriere can optionally use ZFS for its ports/jail storage. For
# ZFS define ZPOOL, otherwise set NO_ZFS=yes
# 
#### ZFS
# The pool where poudriere will create all the filesystems it needs
# poudriere will use ${ZPOOL}/${ZROOTFS} as its root
#
# You need at least 7GB of free space in this pool to have a working
# poudriere.
#
ZPOOL=zroot

### NO ZFS
# To not use ZFS, define NO_ZFS=yes
#NO_ZFS=yes

# root of the poudriere zfs filesystem, by default /poudriere
ZROOTFS=/poudriere

# the host where to download sets for the jails setup
# You can specify here a host or an IP
# replace _PROTO_ by http or ftp
# replace _CHANGE_THIS_ by the hostname of the mirrors where you want to fetch
# by default: ftp://ftp.freebsd.org
#
# Also note that every protocols supported by fetch(1) are supported here, even
# file:///
# Suggested: https://download.FreeBSD.org
FREEBSD_HOST=https://download.FreeBSD.org

# By default the jails have no /etc/resolv.conf, you will need to set
# RESOLV_CONF to a file on your hosts system that will be copied has
# /etc/resolv.conf for the jail, except if you don't need it (using an http
# proxy for example)
RESOLV_CONF=/etc/resolv.conf

# The directory where poudriere will store jails and ports
BASEFS=/usr/local/poudriere

# The directory where the jail will store the packages and logs
# by default a zfs filesystem will be created and set to
# ${BASEFS}/data
#
#POUDRIERE_DATA=${BASEFS}/data

# Use portlint to check ports sanity
USE_PORTLINT=no

# When building packages, a memory device can be used to speedup the build.
# Only one of MFSSIZE or USE_TMPFS is supported. TMPFS is generally faster
# and will expand to the needed amount of RAM. MFS is a slower since it
# uses UFS and several abstraction layers.

# If set WRKDIRPREFIX will be mdmfs of the given size (mM or gG)
#MFSSIZE=4G

# Use tmpfs(5)
# This can be a space-separated list of options:
# wrkdir    - Use tmpfs(5) for port building WRKDIRPREFIX
# data      - Use tmpfs(5) for poudriere cache/temp build data
# localbase - Use tmpfs(5) for LOCALBASE (installing ports for packaging/testing)
# all       - Run the entire build in memory, including builder jails.
# yes       - Enables tmpfs(5) for wrkdir and data
# no        - Disable use of tmpfs(5)
# EXAMPLE: USE_TMPFS="wrkdir data"
USE_TMPFS=yes

# How much memory to limit tmpfs size to for *each builder* in GiB
# (default: none)
#TMPFS_LIMIT=8

# How much memory to limit jail processes to for *each builder*
# in GiB (default: none)
#MAX_MEMORY=8

# How many file descriptors to limit each jail process to (default: 1024)
# This can also be set per PKGBASE, such as MAX_FILES_RStudio=2048.
# Package names with hyphens (-) should be replaced with underscores (_).
#MAX_FILES=1024

# If set the given directory will be used for the distfiles
# This allows to share the distfiles between jails and ports tree
# If this is "no", poudriere must be supplied a ports tree that already has
# the required distfiles.
DISTFILES_CACHE=/usr/ports/distfiles

# If set the ports tree marked to use git will use the defined
# mirror (default: git.FreeBSD.org/port.git)
#
# Example to use github mirror:
#GIT_BASEURL=https://github.com/freebsd/freebsd-src.git

# If set the source tree marked to use git will use the defined
# mirror (default: git.FreeBSD.org/src.git)
#
# Example to use github mirror:
#GIT_PORTSURL=https://github.com/freebsd/freebsd-ports.git

# If set the ports tree or source tree marked to use svn will use the defined
# mirror (default: svn.FreeBSD.org)
# The SSL fingerprints are published here:
# https://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/svn.html#svn-mirrors
#SVN_HOST=svn.FreeBSD.org

# Automatic OPTION change detection
# When bulk building packages, compare the options from kept packages to
# the current options to be built. If they differ, the existing package
# will be deleted and the port will be rebuilt.
# Valid options: yes, no, verbose
# verbose will display the old and new options
CHECK_CHANGED_OPTIONS=verbose

# Automatic Dependency change detection
# When bulk building packages, compare the dependencies from kept packages to
# the current dependencies for every port. If they differ, the existing package
# will be deleted and the port will be rebuilt. This helps catch changes such
# as DEFAULT_RUBY_VERSION, PERL_VERSION, WITHOUT_X11 that change dependencies
# for many ports.
# Valid options: yes, no
# Default: yes
CHECK_CHANGED_DEPS=yes

# Consider bad dependency lines on the wrong PKGNAME as fatal.
# For example:
#    BUILD_DEPENDS=  p5-List-MoreUtils>=0:lang/p5-List-MoreUtils
# If this port's PKGNAME were really "List-MoreUtils" then it would
# not be recorded into the resulting package.  The next build with
# CHECK_CHANGED_DEPS enabled would consider it a "new dependency"
# since it is in the port but not in the package.  This is usually
# a warning but can be made fatal instead by enabling this option.
# Default: no
#BAD_PKGNAME_DEPS_ARE_FATAL=yes

# Path to the RSA key to sign the PKG repo with. See pkg-repo(8)
# This produces a repo that supports SIGNATURE_TYPE=PUBKEY
# Default: not set
PKG_REPO_SIGNING_KEY=/usr/local/etc/ssl/keys/poudriere.key

# Command to sign the PKG repo with. See pkg-repo(8)
# This produces a repo that supports SIGNATURE_TYPE=FINGERPRINTS
# Default: not set
#SIGNING_COMMAND=ssh signing-server sign.sh

# Repo signing command execution context
# If SIGNING_COMMAND is set, run pkg-repo(8) on the host?
#   no  -   Run in the jail
#   yes -   Run on the host
# Default: no
#PKG_REPO_FROM_HOST=yes

# ccache support. Supply the path to your ccache cache directory.
# It will be mounted into the jail and be shared among all jails.
# It is recommended that extra ccache configuration be done with
# ccache -o rather than from the environment.
#CCACHE_DIR=/var/cache/ccache

# Static ccache support from host.  This uses the existing
# ccache from the host in the build jail.  This is useful for
# using ccache+memcached which cannot easily be bootstrapped
# otherwise.  The path to the PREFIX where ccache was installed
# must be used here, and ccache must have been built statically.
# Note also that ccache+memcached will require network access
# which is normally disabled.  Separately setting RESTRICT_NETWORKING=no
# may be required for non-localhost memcached servers.
#CCACHE_STATIC_PREFIX=/usr/local

# The jails normally only allow network access during the 'make fetch'
# phase.  This is a security restriction to prevent random things
# ran during a build from accessing the network.  Disabling this
# is not advised.  ALLOW_NETWORKING_PACKAGES may be used to allow networking
# for a subset of packages only.
#RESTRICT_NETWORKING=yes
#ALLOW_NETWORKING_PACKAGES="npm-foo"

# parallel build support.
#
# By default poudriere uses hw.ncpu to determine the number of builders.
# You can override this default by changing PARALLEL_JOBS here, or
# by specifying the -J flag to bulk/testport.
#
# Example to define PARALLEL_JOBS to one single job
# PARALLEL_JOBS=1

# How many jobs should be used for preparing the build? These tend to
# be more IO bound and may be worth tweaking. Default: PARALLEL_JOBS * 1.25
# PREPARE_PARALLEL_JOBS=1


# If set, failed builds will save the WRKDIR to ${POUDRIERE_DATA}/wrkdirs
# SAVE_WRKDIR=yes

# Choose the default format for the workdir packing: could be tar,tgz,tbz,txz,tzst
# default is tbz
# WRKDIR_ARCHIVE_FORMAT=tbz

# Disable Linux support
# NOLINUX=yes

# By default poudriere sets FORCE_PACKAGE
# To disable it (useful when building public packages):
# NO_FORCE_PACKAGE=yes

# By default poudriere sets PACKAGE_BUILDING
# To disable it:
# NO_PACKAGE_BUILDING=yes

# If you are using a proxy define it here:
# export HTTP_PROXY=bla
# export FTP_PROXY=bla
#
# Cleanout the restricted packages
# NO_RESTRICTED=yes

# By default MAKE_JOBS is disabled to allow only one process per cpu
# Use the following to allow it anyway
# ALLOW_MAKE_JOBS=yes

# List of packages that will always be allowed to use MAKE_JOBS
# regardless of ALLOW_MAKE_JOBS. This is useful for allowing ports
# which holdup the rest of the queue to build more quickly.
#ALLOW_MAKE_JOBS_PACKAGES="pkg ccache py*"

# Timestamp every line of build logs
# Default: no
#TIMESTAMP_LOGS=no

# URL where your POUDRIERE_DATA/logs are hosted
# This will be used for giving URL hints to the HTML output when
# scheduling and starting builds
#URL_BASE=http://yourdomain.com/poudriere/


# This defines the max time (in seconds) that a command may run for a build
# before it is killed for taking too long. Default: 86400
#MAX_EXECUTION_TIME=86400

# This defines the time (in seconds) before a command is considered to
# be in a runaway state for having no output on stdout. Default: 7200
#NOHANG_TIME=7200


# The repository is updated atomically if set yes. This leaves the
# repository untouched until the build completes. This involves using
# hardlinks and symlinks. The operations are fast, but can be intrusive
# for remote syncing or backups.
# Recommended to always keep on.
# Default: yes
#ATOMIC_PACKAGE_REPOSITORY=yes

# When using ATOMIC_PACKAGE_REPOSITORY, commit the packages if some
# packages fail to build. Ignored ports are considered successful.
# This can be set to 'no' to only commit the packages once no failures
# are encountered.
# Default: yes
#COMMIT_PACKAGES_ON_FAILURE=yes

# Keep older package repositories. This can be used to rollback a system
# or to bisect issues by changing the repository to one of the older
# versions and reinstalling everything with `pkg upgrade -f`
# ATOMIC_PACKAGE_REPOSITORY is required for this.
# Default: no
#KEEP_OLD_PACKAGES=no

# How many old package repositories to keep with KEEP_OLD_PACKAGES
# Default: 5
#KEEP_OLD_PACKAGES_COUNT=5

# Make testing errors fatal.
# If set to 'no', ports with test failure will be marked as failed but still
# packaged to permit testing dependent ports (useful for bulk -t -a)
# Default: yes
#PORTTESTING_FATAL=yes

# Define the building jail hostname to be used when building the packages
# Some port/packages hardcode the hostname of the host during build time
# This is a necessary setup for reproducible builds.
#BUILDER_HOSTNAME=pkg.FreeBSD.org

# Define to get a predictable timestamp on the ports tree
# This is a necessary setup for reproducible builds.
#PRESERVE_TIMESTAMP=yes

# Define to yes to build and stage as a regular user
# Default: yes, unless CCACHE_DIR is set and CCACHE_DIR_NON_ROOT_SAFE is not
# set.  Note that to use ccache with BUILD_AS_NON_ROOT you will need to
# use a non-shared CCACHE_DIR that is only built by PORTBUILD_USER and chowned
# to that user.  Then set CCACHE_DIR_NON_ROOT_SAFE to yes.
#BUILD_AS_NON_ROOT=no

# Define to the username to build as when BUILD_AS_NON_ROOT is yes.
# Default: nobody (uid PORTBUILD_UID)
#PORTBUILD_USER=nobody

# Define to the uid to use for PORTBUILD_USER if the user does not
# already exist in the jail.
# Default: 65532
#PORTBUILD_UID=65534

# Define pkgname globs to boost priority for
# Default: none
#PRIORITY_BOOST="pypy openoffice*"

# Define format for buildnames
# Default: %Y-%m-%d_%Hh%Mm%Ss
# ISO8601:
#BUILDNAME_FORMAT="%FT%T%z"

# Define format for build duration times
# Default: %H:%M:%S
#DURATION_FORMAT="%H:%M:%S"

# Use colors when in a TTY
# Default: yes
#USE_COLORS=yes

# Only build what is requested. Do not rebuild build deps if nothing requested
# depends on them. This can create an inconsistent repository if you often
# build one-off packages but expect the repository to stay consistent.
# Defaut: yes
#TRIM_ORPHANED_BUILD_DEPS=yes

# A list of directories to exclude from leftover and filesystem violation
# mtree checks.  Ccache is used here as an example but is already
# excluded by default.  There is no need to add it here unless a
# special configuration is used where it is a problem.
# Default: none
#LOCAL_MTREE_EXCLUDES="/usr/obj /var/tmp/ccache"

# Set to hosted to use the /data directory instead of inline style HTML
# Default: inline
#HTML_TYPE="hosted"

# Set to track remaining ports in the HTML interface.  This can slow down
# processing of the queue slightly, especially for bulk -a builds.
# Default: no
#HTML_TRACK_REMAINING=yes
#+END_SRC

*** Creating the Build Environment

#+BEGIN_SRC sh
poudriere jail -c -j freebsd_14-0x64 -v 14.1-RELEASE
#+END_SRC

This will take awhile to complete, so be patient.  
When you are finished, you can see the installed jail by typing:

#+BEGIN_SRC sh
poudriere jail -l
#+END_SRC

Once you have a jail created, we will have to install a ports tree. It is possible to maintain multiple ports trees in order to serve different development needs. We will be installing a single ports tree that our jail can utilize.

We can use the -p flag to name our ports tree. We will call our tree "HEAD" as it accurately summarizes the use of this tree (the "head" or most up-to-date point of the tree). We will be updating it regularly to match the most current version of the ports tree available:

#+BEGIN_SRC sh
poudriere ports -c -p HEAD
#+END_SRC

Again, this procedure will take awhile because the entire ports tree must be fetched and extracted. When it is finished, we can view our ports tree by typing:

#+BEGIN_SRC sh
poudriere ports -l
#+END_SRC

*** license

Accepting all possible licenses is also a good idea.

#+begin_src sh
echo DISABLE_LICENSES=yes >> /usr/local/etc/poudriere.d/make.conf
#+end_src

*** Creating a Port Building List and Setting Port Options

We will be creating a list of ports that we can pass directly to the command.  

#+BEGIN_SRC sh
vi /usr/local/etc/poudriere.d/port-list 
#+END_SRC

The file create should list the port category followed by a slash and the port name to reflect its location within the ports tree, like this:

important create a new line after adding the code below

#+BEGIN_SRC sh
www/linux-widevine-cdm

#+END_SRC

*** Building the Ports

Now, we are finally ready to start building ports.

The last thing we need to do is ensure that both our jail and ports tree are up-to-date. This probably won't be an issue the first time you build ports since we just created both the ports tree and the jail, but it is good to get in the habit to do this each time you run a build.

To update your jail, type:

#+BEGIN_SRC sh
poudriere jail -u -j freebsd_14-0x64
#+END_SRC

To update your ports tree, type:

#+BEGIN_SRC sh
poudriere ports -u -p HEAD
#+END_SRC

Once that is complete, we can kick off the bulk build process.

#+BEGIN_SRC sh
poudriere bulk -j freebsd_14-0x64 -p HEAD -f /usr/local/etc/poudriere.d/port-list
#+END_SRC

This will start up a number of workers (depending on your poudriere.conf file or the number of CPUs available) and begin building the ports.

At any time during the build process, you can get information about the progress by holding the CTRL key and hitting t:

#+BEGIN_SRC sh
CTRL-t
#+END_SRC

*** Configuring pkg Clients to Use a Poudriere Repository
	
Now that you have packages built and a repository configured to serve your packages, you can configure your clients to use your the server as the source of their packages.
Configuring the Build Server to Use Its Own Package Repo

We can begin by configuring the build server to use the packages it has been building.

First, we need to make a directory to hold our repository configuration files:

#+BEGIN_SRC sh
mkdir -p /usr/local/etc/pkg/repos
#+END_SRC

Inside this directory, we can create our repository configuration file. It must end in .conf, so we will call it poudriere.conf to reflect its purpose:

#+BEGIN_SRC sh
vi /usr/local/etc/pkg/repos/poudriere.conf
#+END_SRC

We will define the repository name as poudriere once again. Inside the definition, we will point to the location on disk where our packages are stored. This should be a directory that combines your jail name and port tree name with a dash. Check your filesystem to be certain. We will also set up signature validation of our packages by pointing to the certificate we created.

In the end, your file should look something like this:

#+BEGIN_SRC conf
Poudriere: {
    url: "file:///usr/local/poudriere/data/packages/freebsd_14-0x64-HEAD"
    mirror_type: "srv",
    signature_type: "pubkey",
    pubkey: "/usr/local/etc/ssl/certs/poudriere.cert",
    enabled: yes,
    priority: 100
}
#+END_SRC

At this point, you need to make a decision. If you want to prefer your compiled packages and fall back on the packages provided by the main FreeBSD repositories, you can set a priority here, telling it to prefer packages out of this repository. This will cause our local repository to take priority over the official repositories.

Keep in mind that mixing packages in this way can have some complicated consequences. If the official repositories have a package version that is higher than your local repository version, your compiled package may be replaced by the generic one from the official repositories (until you rebuild with poudriere and reinstall with pkg). Also, the official packages may assume that dependent packages are built in a certain way and may not function when mixed with your custom packages.

If you choose to mix these two package sources, be prepared to carefully audit each install to ensure that you are not accidentally causing undesirable behavior.

To mix packages, add a priority setting to your repository definition, specifying that the local repo has a higher precedence

*** pkg update

make sure you have switched to root
Update the repo info:

#+begin_src sh
pkg update -f
#+end_src

install

#+begin_src sh
pkg install linux-widevine-cdm
#+end_src

*** chromium ozone and wayland

Since version 97, native Wayland support in Chromium can be enabled with the following flags [6]:

#+begin_src sh
chrome --ozone-platform-hint=auto
#+end_src

If this doesn't work, e.g. on version 106 under Weston, then use:

#+begin_src sh
chrome --ozone-platform=wayland
#+end_src

you can set the wayland option using the using a desktop entry

copy the chromium-browser.desktop which is used in application launchers

#+begin_src sh
cp /usr/local/share/applications/chromium-browser.desktop ~/.local/share/applications
#+end_src

edit chromium-browser.desktop you just copied in the local share application directory in your home

#+begin_src sh
vi ~/.local/share/applications/chromium-browser.desktop
#+end_src

edit the Exec line and set the option to start chromium using wayland

#+begin_src conf
Exec=chrome --ozone-platform=wayland %U
#+end_src

the final desktop entry should look like this

#+begin_src conf
[Desktop Entry]
Type=Application
Version=1.0
Encoding=UTF-8
Name=Chromium
Comment=Google web browser based on WebKit
Icon=chrome
Exec=chrome --ozone-platform=wayland %U
Categories=Application;Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;
StartupNotify=true
#+end_src

**** check widevine drm is working

in the url bar in chromium add the following url to show the chromium flags

#+begin_src conf
chrome://flags
#+end_src

if you scroll to the bottom of the page

#+begin_src conf
Cdm Storage Database
Start to use the CdmStorageDatabase to store data alongside the MediaLicenseDatabase. If disabled, we will not use CdmStorage* at all, even in MediaLicense* code. – Mac, Windows, Linux, ChromeOS, Fuchsia, Lacros

#cdm-storage-database

Default

Cdm Storage Database Migration
Use the Cdm Storage Database over the MediaLicenseDatabase for Cdm storage operations. – Mac, Windows, Linux, ChromeOS, Fuchsia, Lacros

#cdm-storage-database-migration

Default
#+end_src

** virtual_oss audiofor obs

virtual oss to record sndio audio in obs studio

*** cuse boot loader.conf

add cuse_load="YES" loader.conf using sysrc

#+begin_src sh
sudo sysrc -f /boot/loader.conf cuse_load="YES"
#+end_src

or edit loader.conf with vi

#+begin_src sh
sudo vi /boot/loader.conf
#+end_src

and add the following code

#+begin_src conf
cuse_load="YES"
#+end_src

load cuse

#+begin_src sh
sudo kldload cuse
#+end_src

*** rc.conf

enable virtual_oss and sndiod in your rc.conf using sysrc

#+begin_src sh
sudo sysrc virtual_oss_enable="YES"
sudo sysrc sndiod_enable="YES"
#+end_src

or manually edit your /etc/rc/.conf

#+begin_src sh
sudo vi /etc/rc.conf
#+end_src

add the following code to your /etc/rc.conf

#+begin_src conf
# virtual oss
virtual_oss_enable="NO"
# sndiod audio
sndiod_enable="YES"
#+end_src

*** virtual oss

create a loopback device on /dev/dsp to record desktop audio

switch to root

#+begin_src sh
su
#+end_src

edit you /boot/loader.conf

#+begin_src sh
vi /boot/loader.conf
#+end_src

and add the following code

#+begin_src conf
# virtual oss - start with: sudo sysrc onestart virtual_oss 
virtual_oss_enable="NO"
#+end_src

start virtual_oss

#+begin_src sh
sudo service virtual_oss onestart 
#+end_src

replace dsp0 with you device

#+begin_src sh
virtual_oss -S -C 2 -c 2 -r 48000 -b 16 -s 1024 -f /dev/dsp0 -w vdsp.wav -l dsp
#+end_src

*** obs

under sources click add select

Audio Input Capture

in the properties window set DSP to Custom

and the Custom DSP Path to

#+begin_example
/dev/dsp
#+end_example

** ollama
*** zfs datasets
we will also create a zfs dataset for our ollama

change djwilcox to your username in the code below

#+begin_src sh
doas zfs create zroot/home/djwilcox/.ollama
#+end_src

#+begin_src sh
doas chown -R djwilcox:djwilcox /home/djwilcox/.ollama
#+end_src

*** ollama vulkan

enable vulkan support for ollama

edit your zshenv file

#+begin_src sh
vi ~/.zshenv
#+end_src

add export OLLAMA_VULKAN=1

#+begin_src conf
#===============================================================================
# ollama vulkan
#===============================================================================

export OLLAMA_VULKAN=1
#+end_src

source your zshenv file

#+begin_src sh
source ~/.zshenv
#+end_src

** shutdown

shutdown and reboot

#+begin_src sh
sudo shutdown -r now
#+end_src

shutdown and dont reboot

#+begin_src sh
sudo shutdown -p now
#+end_src
