#+STARTUP: content
* freebsd 15.1 upgrade
** poudriere
*** Create an SSL Certificate and Key

When we build packages with poudriere, we want to be able to sign them with a private key. This will ensure all of our machines that the packages created are legitimate and that nobody is intercepting the connection to the build machine to serve malicious packages.

To start off, we will create a directory structure for our key and certificate. Since all of our optional software configuration takes place within the /usr/local/etc directory, and because other software uses the /usr/local/etc/ssl location, this is where we will place our files.

We will ensure that we have an ssl directory that contains two subdirectories called keys and certs. We can do this in one command by typing:

#+BEGIN_SRC sh
doas mkdir -p /usr/local/etc/ssl/{keys,certs}
#+END_SRC

Our private key, which must be kept secret, will be placed in the keys directory. This will be used to sign the packages that we will be creating. Keeping this secure is essential to ensuring that our packages are not being tampered with. We can lock down the directory so that users without root or sudo privileges will be unable to interact with the directory or its contents:

#+BEGIN_SRC sh
doas chmod 0600 /usr/local/etc/ssl/keys
#+END_SRC

The certs directory will contain our publicly available certificate created with the key. As such, we can leave the default permissions on that directory.

Next, we will generate a 4096 bit key called poudriere.key, and place it in our keys directory by typing:

#+BEGIN_SRC sh
doas openssl genrsa -out /usr/local/etc/ssl/keys/poudriere.key 4096
#+END_SRC

After the key is generated, we can create a public cert from it by typing:

#+BEGIN_SRC sh
doas openssl rsa -in /usr/local/etc/ssl/keys/poudriere.key -pubout -out /usr/local/etc/ssl/certs/poudriere.cert
#+END_SRC

We now have the SSL components we need to sign packages and verify the signatures. Later on, we will configure our clients to use the generated certificate for package verification.

*** poudriere install

#+BEGIN_SRC sh
doas pkg install poudriere
#+END_SRC

*** create the distfiles directory

#+BEGIN_SRC sh
doas mkdir -p /usr/ports/distfiles
#+END_SRC

edit the poudriere.conf file

#+BEGIN_SRC sh
doas vi /usr/local/etc/poudriere.conf
#+END_SRC

change the poudriere.conf so it looks like this

#+BEGIN_SRC sh
# Poudriere can optionally use ZFS for its ports/jail storage. For
# ZFS define ZPOOL, otherwise set NO_ZFS=yes
# 
#### ZFS
# The pool where poudriere will create all the filesystems it needs
# poudriere will use ${ZPOOL}/${ZROOTFS} as its root
#
# You need at least 7GB of free space in this pool to have a working
# poudriere.
#
ZPOOL=zroot

### NO ZFS
# To not use ZFS, define NO_ZFS=yes
#NO_ZFS=yes

# root of the poudriere zfs filesystem, by default /poudriere
ZROOTFS=/poudriere

# the host where to download sets for the jails setup
# You can specify here a host or an IP
# replace _PROTO_ by http or ftp
# replace _CHANGE_THIS_ by the hostname of the mirrors where you want to fetch
# by default: ftp://ftp.freebsd.org
#
# Also note that every protocols supported by fetch(1) are supported here, even
# file:///
# Suggested: https://download.FreeBSD.org
FREEBSD_HOST=https://download.FreeBSD.org

# By default the jails have no /etc/resolv.conf, you will need to set
# RESOLV_CONF to a file on your hosts system that will be copied has
# /etc/resolv.conf for the jail, except if you don't need it (using an http
# proxy for example)
RESOLV_CONF=/etc/resolv.conf

# The directory where poudriere will store jails and ports
BASEFS=/usr/local/poudriere

# The directory where the jail will store the packages and logs
# by default a zfs filesystem will be created and set to
# ${BASEFS}/data
#
POUDRIERE_DATA=${BASEFS}/data

# Use portlint to check ports sanity
USE_PORTLINT=no

# When building packages, a memory device can be used to speedup the build.
# Only one of MFSSIZE or USE_TMPFS is supported. TMPFS is generally faster
# and will expand to the needed amount of RAM. MFS is a slower since it
# uses UFS and several abstraction layers.

# If set WRKDIRPREFIX will be mdmfs of the given size (mM or gG)
#MFSSIZE=4G

# Use tmpfs(5)
# This can be a space-separated list of options:
# wrkdir    - Use tmpfs(5) for port building WRKDIRPREFIX
# data      - Use tmpfs(5) for poudriere cache/temp build data
# localbase - Use tmpfs(5) for LOCALBASE (installing ports for packaging/testing)
# all       - Run the entire build in memory, including builder jails.
# yes       - Enables tmpfs(5) for wrkdir and data
# no        - Disable use of tmpfs(5)
# EXAMPLE: USE_TMPFS="wrkdir data"
USE_TMPFS=yes

# How much memory to limit tmpfs size to for *each builder* in GiB
# (default: none)
#TMPFS_LIMIT=8

# How much memory to limit jail processes to for *each builder*
# in GiB (default: none)
#MAX_MEMORY=8

# How many file descriptors to limit each jail process to (default: 1024)
# This can also be set per PKGBASE, such as MAX_FILES_RStudio=2048.
# Package names with hyphens (-) should be replaced with underscores (_).
#MAX_FILES=1024

# If set the given directory will be used for the distfiles
# This allows to share the distfiles between jails and ports tree
# If this is "no", poudriere must be supplied a ports tree that already has
# the required distfiles.
DISTFILES_CACHE=/usr/ports/distfiles

# If set the ports tree or source tree marked to use svn will use the defined
# mirror (default: svn.FreeBSD.org)
# The SSL fingerprints are published here:
# https://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/svn.html#svn-mirrors
#SVN_HOST=svn.FreeBSD.org

# Automatic OPTION change detection
# When bulk building packages, compare the options from kept packages to
# the current options to be built. If they differ, the existing package
# will be deleted and the port will be rebuilt.
# Valid options: yes, no, verbose
# verbose will display the old and new options
CHECK_CHANGED_OPTIONS=verbose

# Automatic Dependency change detection
# When bulk building packages, compare the dependencies from kept packages to
# the current dependencies for every port. If they differ, the existing package
# will be deleted and the port will be rebuilt. This helps catch changes such
# as DEFAULT_RUBY_VERSION, PERL_VERSION, WITHOUT_X11 that change dependencies
# for many ports.
# Valid options: yes, no
# Default: yes
CHECK_CHANGED_DEPS=yes

# Consider bad dependency lines on the wrong PKGNAME as fatal.
# For example:
#    BUILD_DEPENDS=  p5-List-MoreUtils>=0:lang/p5-List-MoreUtils
# If this port's PKGNAME were really "List-MoreUtils" then it would
# not be recorded into the resulting package.  The next build with
# CHECK_CHANGED_DEPS enabled would consider it a "new dependency"
# since it is in the port but not in the package.  This is usually
# a warning but can be made fatal instead by enabling this option.
# Default: no
#BAD_PKGNAME_DEPS_ARE_FATAL=yes


# Path to the RSA key to sign the PKG repo with. See pkg-repo(8)
#PKG_REPO_SIGNING_KEY=/etc/ssl/keys/repo.key
PKG_REPO_SIGNING_KEY=/usr/local/etc/ssl/keys/poudriere.key


# ccache support. Supply the path to your ccache cache directory.
# It will be mounted into the jail and be shared among all jails.
# It is recommended that extra ccache configuration be done with
# ccache -o rather than from the environment.
#CCACHE_DIR=/var/cache/ccache

# Static ccache support from host.  This uses the existing
# ccache from the host in the build jail.  This is useful for
# using ccache+memcached which cannot easily be bootstrapped
# otherwise.  The path to the PREFIX where ccache was installed
# must be used here, and ccache must have been built statically.
# Note also that ccache+memcached will require network access
# which is normally disabled.  Separately setting RESTRICT_NETWORKING=no
# may be required for non-localhost memcached servers.
#CCACHE_STATIC_PREFIX=/usr/local

# The jails normally only allow network access during the 'make fetch'
# phase.  This is a security restriction to prevent random things
# ran during a build from accessing the network.  Disabling this
# is not advised.  ALLOW_NETWORKING_PACKAGES may be used to allow networking
# for a subset of packages only.
#RESTRICT_NETWORKING=yes
#ALLOW_NETWORKING_PACKAGES="npm-foo"

# parallel build support.
#
# By default poudriere uses hw.ncpu to determine the number of builders.
# You can override this default by changing PARALLEL_JOBS here, or
# by specifying the -J flag to bulk/testport.
#
# Example to define PARALLEL_JOBS to one single job
# PARALLEL_JOBS=1

# How many jobs should be used for preparing the build? These tend to
# be more IO bound and may be worth tweaking. Default: PARALLEL_JOBS * 1.25
# PREPARE_PARALLEL_JOBS=1


# If set, failed builds will save the WRKDIR to ${POUDRIERE_DATA}/wrkdirs
# SAVE_WRKDIR=yes

# Choose the default format for the workdir packing: could be tar,tgz,tbz,txz
# default is tbz
# WRKDIR_ARCHIVE_FORMAT=tbz

# Disable linux support
# NOLINUX=yes

# By default poudriere sets FORCE_PACKAGE
# To disable it (useful when building public packages):
# NO_FORCE_PACKAGE=yes

# By default poudriere sets PACKAGE_BUILDING
# To disable it:
# NO_PACKAGE_BUILDING=yes

# If you are using a proxy define it here:
# export HTTP_PROXY=bla
# export FTP_PROXY=bla
#
# Cleanout the restricted packages
# NO_RESTRICTED=yes

# By default MAKE_JOBS is disabled to allow only one process per cpu
# Use the following to allow it anyway
# ALLOW_MAKE_JOBS=yes

# List of packages that will always be allowed to use MAKE_JOBS
# regardless of ALLOW_MAKE_JOBS. This is useful for allowing ports
# which holdup the rest of the queue to build more quickly.
#ALLOW_MAKE_JOBS_PACKAGES="pkg ccache py*"

# Timestamp every line of build logs
# Default: no
#TIMESTAMP_LOGS=no

# URL where your POUDRIERE_DATA/logs are hosted
# This will be used for giving URL hints to the HTML output when
# scheduling and starting builds
#URL_BASE=http://yourdomain.com/poudriere/


# This defines the max time (in seconds) that a command may run for a build
# before it is killed for taking too long. Default: 86400
#MAX_EXECUTION_TIME=86400

# This defines the time (in seconds) before a command is considered to
# be in a runaway state for having no output on stdout. Default: 7200
#NOHANG_TIME=7200


# The repository is updated atomically if set yes. This leaves the
# repository untouched until the build completes. This involves using
# hardlinks and symlinks. The operations are fast, but can be intrusive
# for remote syncing or backups.
# Recommended to always keep on.
# Default: yes
#ATOMIC_PACKAGE_REPOSITORY=yes

# When using ATOMIC_PACKAGE_REPOSITORY, commit the packages if some
# packages fail to build. Ignored ports are considered successful.
# This can be set to 'no' to only commit the packages once no failures
# are encountered.
# Default: yes
#COMMIT_PACKAGES_ON_FAILURE=yes

# Keep older package repositories. This can be used to rollback a system
# or to bisect issues by changing the repository to one of the older
# versions and reinstalling everything with `pkg upgrade -f`
# ATOMIC_PACKAGE_REPOSITORY is required for this.
# Default: no
#KEEP_OLD_PACKAGES=no

# How many old package repositories to keep with KEEP_OLD_PACKAGES
# Default: 5
#KEEP_OLD_PACKAGES_COUNT=5

# Make testing errors fatal.
# If set to 'no', ports with test failure will be marked as failed but still
# packaged to permit testing dependent ports (useful for bulk -t -a)
# Default: yes
#PORTTESTING_FATAL=yes

# Define the building jail hostname to be used when building the packages
# Some port/packages hardcode the hostname of the host during build time
# This is a necessary setup for reproducible builds.
#BUILDER_HOSTNAME=pkg.FreeBSD.org

# Define to get a predictable timestamp on the ports tree
# This is a necessary setup for reproducible builds.
#PRESERVE_TIMESTAMP=yes

# Define to yes to build and stage as a regular user
# Default: yes, unless CCACHE_DIR is set and CCACHE_DIR_NON_ROOT_SAFE is not
# set.  Note that to use ccache with BUILD_AS_NON_ROOT you will need to
# use a non-shared CCACHE_DIR that is only built by PORTBUILD_USER and chowned
# to that user.  Then set CCACHE_DIR_NON_ROOT_SAFE to yes.
#BUILD_AS_NON_ROOT=no

# Define to the username to build as when BUILD_AS_NON_ROOT is yes.
# Default: nobody (uid PORTBUILD_UID)
#PORTBUILD_USER=nobody

# Define to the uid to use for PORTBUILD_USER if the user does not
# already exist in the jail.
# Default: 65532
#PORTBUILD_UID=65534

# Define pkgname globs to boost priority for
# Default: none
#PRIORITY_BOOST="pypy openoffice*"

# Define format for buildnames
# Default: %Y-%m-%d_%Hh%Mm%Ss
# ISO8601:
#BUILDNAME_FORMAT="%FT%TZ"

# Define format for build duration times
# Default: %H:%M:%S
#DURATION_FORMAT="%H:%M:%S"

# Use colors when in a TTY
# Default: yes
#USE_COLORS=yes

# Only build what is requested. Do not rebuild build deps if nothing requested
# depends on them. This can create an inconsistent repository if you often
# build one-off packages but expect the repository to stay consistent.
# Defaut: yes
#TRIM_ORPHANED_BUILD_DEPS=yes

# A list of directories to exclude from leftover and filesystem violation
# mtree checks.  Ccache is used here as an example but is already
# excluded by default.  There is no need to add it here unless a
# special configuration is used where it is a problem.
# Default: none
#LOCAL_MTREE_EXCLUDES="/usr/obj /var/tmp/ccache"

# Set to hosted to use the /data directory instead of inline style HTML
# Default: inline
#HTML_TYPE="hosted"

# Set to track remaining ports in the HTML interface.  This can slow down
# processing of the queue slightly, especially for bulk -a builds.
# Default: no
#HTML_TRACK_REMAINING=yes
#+END_SRC

** upgrade
*** 1) bectl boot env

Create the 15-1 boot env

#+begin_src sh
doas bectl create 15-1
#+end_src

Mount the boot env

#+begin_src sh
doas bectl mount 15-1 /tmp/upgrade-15.1
#+end_src

*** 2) kld list

I would suggest disabling the DRM driver during the upgrade. That way it won't interfere or cause problems during the upgrade. Once you have the base OS completely upgraded you can focus on upgrading packages, including any from the kmods repositories.
 
This is what I had to do though I actually uninstalled it and reinstalled after going through the rest of the upgrade process cause 15.1 would only start with a page fault.

So comment out the kld_list

#+begin_src conf
#kld_list="nvidia-modeset nvidia-drm nvidia_gsp_tu10x_fw linux linux64 i915kms ext2fs mac_priority fusefs vmm nmdm"
#+end_src

and just use a temporary kld_list during the upgrade

#+begin_src sh
kld_list="linux linux64"
#+end_src

*** 3) First, update pkg(8) itself to ensure you have the latest version:

#+begin_src sh
doas pkg upgrade -yr FreeBSD-ports pkg
#+end_src

*** 4) Second, upgrade the base system

Create a temporary repository configuration that points exactly to the 15.1-RC1 package repository:

Create the upgrade.conf file

#+begin_src sh
echo 'FreeBSD-base: {
    url: "pkg+https://pkg.FreeBSD.org/${ABI}/base_release_1"
}' | doas tee /tmp/upgrade-15.1/upgrade.conf
#+end_src

*** 5) Then upgrade the base system:

#+begin_src sh
doas pkg -r /tmp/upgrade-15.1 \
      -o REPOS_DIR=/etc/pkg,/usr/local/etc/pkg/repos,/tmp/upgrade-15.1 \
      -o IGNORE_OSVERSION=yes upgrade -r FreeBSD-base
#+end_src

*** 6) after upgrade 

After the upgrade, review any messages printed by pkg(8). Some base packages may require additional configuration steps (e.g., running ‘service setup‘). Follow those instructions as needed.

Third, update any third-party kernel modules (kmods) that you may have installed from packages (e.g. drm-kmod, acpi_call). Use the same temporary repository configuration:

#+begin_src sh
doas pkg -r /tmp/upgrade-15.1 \
      -o REPOS_DIR=/etc/pkg,/usr/local/etc/pkg/repos,/tmp/upgrade-15.1 \
      upgrade -r FreeBSD-ports-kmods
#+end_src

*** 7) uefi bootloader

Identify the EFI System Partition (ESP) where the boot loader resides by executing the following command:

#+begin_src sh
doas efibootmgr -v
#+end_src

#+begin_example
[i] Yes Master ? doas efibootmgr -v
Boot to FW : false
BootCurrent: 0001
Timeout    : 0 seconds
BootOrder  : 0001
+Boot0001* UEFI: Micron 2300 NVMe 1024GB, Partition 1 HD(1,GPT,01b224cb-3a84-11f1-93f9-0050b610e975,0x28,0x82000)/File(\EFI\Boot\BootX64.efi)
                                                         gpt/efiboot0:/EFI/Boot/BootX64.efi /boot/efi//EFI/Boot/BootX64.efi
                                                     VenHw(2d6447ef-3bc9-41a0-ac19-4d51d01b4ce6,4d006900630072006f006e002000320033003000300020004e0056004d00650020003100300032003400470042000000)


Unreferenced Variables:
 Boot0006  FreeBSD HD(1,GPT,56ac6e30-904d-11ee-88b9-0050b610e975,0x28,0x82000)/File(\efi\freebsd\loader.efi)
 Boot0000* ubuntu HD(1,GPT,b3006ff6-1fa2-4aad-9ec6-8b7437b4545f,0x800,0x100000)/File(\EFI\ubuntu\shimx64.efi)
[djwilcox@pollux ~/desktop]
#+end_example

*** 8) Mounting the ESP

Backup the loader.efi

#+begin_src sh
cp -r /boot/efi ~/desktop
#+end_src

If the ESP is not already mounted at /boot/efi, mount the partition listed in the efibootmgr output:

#+begin_src sh
mount_msdosfs /dev/nda0p1 /boot/efi
#+end_src

*** 9) Install the Boot Loader

Note that some installations may not have freebsd/loader.efi.

#+begin_src sh
doas cp /boot/loader.efi /boot/efi/efi/boot/bootx64.efi
doas cp /boot/loader.efi /boot/efi/efi/freebsd/loader.efi
#+end_src

*** 10) check for configuration file updates that may have been installed as ‘.pkgnew‘ files:

#+begin_src sh
doas find /etc /usr/local/etc -name '*.pkgnew' -ls
#+end_src

If such files exist, manually compare them with the originals (e.g. ‘diff /etc/rc.conf /etc/rc.conf.pkgnew‘) and merge any necessary changes.

#+begin_example
[i] Yes Master ? doas find /etc /usr/local/etc -name '*.pkgnew' -ls
525415        1 lrwxr-xr-x    1 root                             wheel                                  14  8 Jun 19:53 /etc/unbound.pkgnew -> ../var/unbound
#+end_example

Since we arent using the built in version of unbound and using the pkg version

We can back up the directory and then delete it

#+begin_src sh
cp -r /etc/unbound.pkgnew ~/desktop
#+end_src

Remove the unbound.pkgnew

#+begin_src sh
doas rm -rf /etc/unbound.pkgnew
#+end_src

*** 11) activate the new boot env

#+begin_src sh
doas bectl umount 15-1
doas bectl activate 15-1
#+end_src

Finally, reboot to load the new kernel and userland:

#+begin_src sh
doas shutdown -r now
#+end_src

*** 12) update kmods
**** ports install

install git

#+begin_src sh
doas pkg install git
#+end_src

use poudriere to pull ports

#+begin_src sh
doas poudriere ports -c -p local -m git+https -B 2026Q2
#+end_src

**** Creating the Build Environment

#+BEGIN_SRC sh
doas poudriere jail -c -j freebsd_15-1x64 -v 15.1-RELEASE
#+END_SRC

This will take awhile to complete, so be patient.  
When you are finished, you can see the installed jail by typing:

#+BEGIN_SRC sh
doas poudriere jail -l
#+END_SRC

Again, this procedure will take awhile because the entire ports tree must be fetched and extracted. When it is finished, we can view our ports tree by typing:

#+BEGIN_SRC sh
poudriere ports -l
#+END_SRC

**** Creating a Port Building List and Setting Port Options

We will be creating a list of ports that we can pass directly to the command.  

#+BEGIN_SRC sh
doas vi /usr/local/etc/poudriere.d/port-list 
#+END_SRC

The file create should list the port category followed by a slash and the port name to reflect its location within the ports tree, like this:

#+BEGIN_SRC sh
x11/nvidia-driver
graphics/nvidia-drm-66-kmod

#+END_SRC

If you use specific make.conf options to build your ports, you can create a make.conf file for each jail within your /usr/local/etc/poudriere.d directory. For example, for our jail, we can create a make.conf file with this name:

#+BEGIN_SRC sh
doas vi /usr/local/etc/poudriere.d/freebsd_15-1x64-make.conf
#+END_SRC

#+BEGIN_SRC sh
OPTIONS_UNSET+= DOCS NLS EXAMPLES
DISABLE_LICENSES=yes
#+END_SRC

set IGNORE_OSVERSION in pkg.conf

#+begin_src sh
doas vi /usr/local/etc/pkg.conf
#+end_src

#+begin_src conf
IGNORE_OSVERSION = true;
#+end_src

Afterwards, we can configure each of our ports, which will create files with the options we selected.

You can configure anything which has not been already configured using the options command. We should pass in both the port tree we created (using the -p option) and the jail we are setting these options for (using the -j option). We also must specify the list of ports we want to configure using the -f option.

bulk build with no user input

#+BEGIN_SRC sh
doas poudriere bulk -j freebsd_15-1x64 -p local -f /usr/local/etc/poudriere.d/port-list
#+END_SRC

**** Updating the Ports

Now, we are finally ready to start building ports.

The last thing we need to do is ensure that both our jail and ports tree are up-to-date. This probably won't be an issue the first time you build ports since we just created both the ports tree and the jail, but it is good to get in the habit to do this each time you run a build.

To update your jail, type:

#+BEGIN_SRC sh
doas poudriere jail -u -j freebsd_15-1x64
#+END_SRC

To update your ports tree, type:

#+BEGIN_SRC sh
doas poudriere ports -u -p local
#+END_SRC

Once that is complete, we can kick off the bulk build process.

#+BEGIN_SRC sh
doas poudriere bulk -j freebsd_15-1x64 -p local -f /usr/local/etc/poudriere.d/port-list
#+END_SRC

This will start up a number of workers (depending on your poudriere.conf file or the number of CPUs available) and begin building the ports.

At any time during the build process, you can get information about the progress by holding the CTRL key and hitting t:

#+BEGIN_SRC sh
CTRL-t
#+END_SRC

**** Configuring pkg Clients to Use a Poudriere Repository
	
Now that you have packages built and a repository configured to serve your packages, you can configure your clients to use your the server as the source of their packages.
Configuring the Build Server to Use Its Own Package Repo

We can begin by configuring the build server to use the packages it has been building.

First, we need to make a directory to hold our repository configuration files:

#+BEGIN_SRC sh
doas mkdir -p /usr/local/etc/pkg/repos
#+END_SRC

Inside this directory, we can create our repository configuration file. It must end in .conf, so we will call it poudriere.conf to reflect its purpose:

#+BEGIN_SRC sh
doas vi /usr/local/etc/pkg/repos/poudriere.conf
#+END_SRC

We will define the repository name as poudriere once again. Inside the definition, we will point to the location on disk where our packages are stored. This should be a directory that combines your jail name and port tree name with a dash. Check your filesystem to be certain. We will also set up signature validation of our packages by pointing to the certificate we created.

In the end, your file should look something like this:

#+BEGIN_SRC sh
Poudriere: {
    url: "file:///usr/local/poudriere/data/packages/freebsd_15-1x64-local"
    mirror_type: "srv",
    signature_type: "pubkey",
    pubkey: "/usr/local/etc/ssl/certs/poudriere.cert",
    enabled: yes,
    priority: 100
}
#+END_SRC

At this point, you need to make a decision. If you want to prefer your compiled packages and fall back on the packages provided by the main FreeBSD repositories, you can set a priority here, telling it to prefer packages out of this repository. This will cause our local repository to take priority over the official repositories.

Keep in mind that mixing packages in this way can have some complicated consequences. If the official repositories have a package version that is higher than your local repository version, your compiled package may be replaced by the generic one from the official repositories (until you rebuild with poudriere and reinstall with pkg). Also, the official packages may assume that dependent packages are built in a certain way and may not function when mixed with your custom packages.

If you choose to mix these two package sources, be prepared to carefully audit each install to ensure that you are not accidentally causing undesirable behavior.

To mix packages, add a priority setting to your repository definition, specifying that the local repo has a higher precedence

Update the repo info:

#+BEGIN_SRC sh
doas pkg update
#+END_SRC

**** nvidia install

remove the old nvidia packages

#+begin_src sh
doas pkg delete -y nvidia-driver 'nvidia*kmod*' nvidia-settings
#+end_src

Install the new nvidia packages

#+begin_src sh
doas pkg install nvidia-driver nvidia-drm-66-kmod nvidia-settings
#+end_src

*** 13) How to Determine Your Base System Type

Run the following command:

#+begin_src sh
doas pkg which /usr/bin/uname
#+end_src

if the output shows a package name starting with ‘FreeBSD-‘ (for example ‘FreeBSD-runtime-15.0‘), then your base system is managed by pkg (pkgbase). If the output says ‘/usr/bin/uname was not installed by a package‘, then your system uses the traditional layout (freebsd-update(8)
is the appropriate upgrade method).

To check whether you have any third-party kernel modules (kmods) installed from packages, run the following command:

#+begin_src sh
doas pkg which $(kldstat -v | awk -F '[()]' '/\.ko/ {print $2}')
#+end_src

Modules located in ‘/boot/kernel/‘ (such as ‘zfs.ko‘) are part of the base system packages, and belong to a ‘FreeBSD-kernel-*‘ package. Modules located in ‘/boot/modules/‘ (such as ‘sysctlinfo.k‘) are third-party kmods installed from the ports/pkg repository. If the command shows any packages with names that do not start with ‘FreeBSD-‘, those are third-party kmods. If no such packages appear, you have no third-party kmods installed.

I assume that when FreeBSD 15.1-RELEASE will be released – even more detailed instructions could be available in the Release Notes document.

** Uninstall Poudriere Nvidia drivers and install PKG version
*** switch to single user mode 

Turn the computer on 

+ Enter you geli password to decrypt the drive
+ At the boot screen select single user mode by pressing 2
+ at the prompt enter your root password

if you run mount you wil see the file system is mounted read only

#+BEGIN_SRC sh
mount
#+END_SRC

So we need to mount /root as read write  
we do this by setting readonly to off

#+BEGIN_SRC sh
zfs set readonly=off zroot
#+END_SRC

mount all

#+begin_src sh
zfs mount -a
#+end_src

*** Remove the Poudriere-built packages

Uninstall the custom packages.

#+begin_src sh
pkg delete -y nvidia-driver 'nvidia*kmod*'
#+end_src

*** Change poudriere enable to no

#+begin_src sh
vi /usr/local/etc/pkg/repos/poudriere.conf
#+end_src

#+begin_src sh
Poudriere: {
    url: "file:///usr/local/poudriere/data/packages/freebsd_15-1x64-local"
    mirror_type: "srv",
    signature_type: "pubkey",
    pubkey: "/usr/local/etc/ssl/certs/poudriere.cert",
    enabled: no,     # <--- Change this to "no" temporarily
    priority: 100
}
#+end_src

*** Update your local package database

Ensure your local pkg cache is completely synchronized with the upstream FreeBSD repositories:

#+begin_src sh
pkg update -f
#+end_src

*** Install the Nvidia pkg packages

#+begin_src sh
pkg install nvidia-driver nvidia-drm-66-kmod
#+end_src

*** Remove entries from your Poudriere port-list

Edit your port-list file:

#+begin_src sh
vi /usr/local/etc/poudriere.d/port-list
#+end_src

Delete these two lines so Poudriere stops compiling them on future bulk runs:

#+begin_src sh
x11/nvidia-driver
graphics/nvidia-drm-66-kmod
#+end_src

*** Change poudriere enable to yes

#+begin_src sh
vi /usr/local/etc/pkg/repos/poudriere.conf
#+end_src

#+begin_src sh
Poudriere: {
    url: "file:///usr/local/poudriere/data/packages/freebsd_15-1x64-local"
    mirror_type: "srv",
    signature_type: "pubkey",
    pubkey: "/usr/local/etc/ssl/certs/poudriere.cert",
    enabled: yes,
    priority: 100
}
#+end_src

*** Reboot

#+begin_src sh
doas shutdown -r now
#+end_src
