#+STARTUP: content
* invidious bhyve
** vm-bhyve setup
*** packages

#+begin_src sh
doas pkg install bhyve-firmware grub2-bhyve edk2-bhyve vm-bhyve-devel
#+end_src

*** zfs dataset

change djwilcox to your username.

#+begin_src sh
doas zfs create zroot/home/djwilcox/vm
doas zfs create zroot/home/djwilcox/vm/.iso
doas zfs create zroot/home/djwilcox/vm/.templates
doas zfs create zroot/home/djwilcox/vm/.config
doas zfs create zroot/home/djwilcox/vm/.img
#+end_src

change the permission on the vm directory

#+begin_src sh
doas chown -R djwilcox:djwilcox /home/djwilcox/vm
#+end_src

*** rc.conf

#+begin_src sh
doas sysrc kld_list+="vmm nmdm"
doas sysrc vm_enable=YES
doas sysrc vm_dir="zfs:zroot/home/djwilcox/vm"
#+end_src

*** kldload

only needed if you havent rebooted, and not needed after that

#+begin_src sh
doas kldload vmm nmdm
#+end_src

*** networking

gateway enable

#+begin_src sh
doas sysrc gateway_enable=YES
#+end_src

sysctl 

#+begin_src sh
doas sysctl net.link.tap.up_on_open=1
doas sysctl net.inet.ip.forwarding=1
#+end_src

set option permanently

#+begin_src sh
doas echo "net.link.tap.up_on_open=1" >> /etc/sysctl.conf
doas echo "net.inet.ip.forwarding=1" >> /etc/sysctl.conf
#+end_src

*** copy vm-bhyve config

#+begin_src sh
doas cp -a /usr/local/share/examples/vm-bhyve /home/djwilcox/vm/.templates
#+end_src

*** doas

edit doas.conf and add a rule for the vm command

#+begin_src sh
doas vi /usr/local/etc/doas.conf
#+end_src

#+begin_src conf
# vm-bhyve
permit nopass :djwilcox cmd vm
#+end_src

** vm-bhyve start
*** service vm start

#+begin_src sh
doas service vm start
#+end_src

*** vm init

#+begin_src sh
doas vm init
#+end_src

*** networking

replace laggo with your network device

#+begin_src sh
doas vm switch create public
doas vm switch add public lagg0
doas ifconfig vm-public addm lagg0
#+end_src

** vm-bhyve create
*** fetch iso

i found the vm iso command stopped downloading the iso part way through,
so instead i used fetch to download the iso

#+begin_src sh
fetch -o /home/djwilcox/vm/.iso 'https://releases.ubuntu.com/26.04/ubuntu-26.04-live-server-amd64.iso'
#+end_src

*** find number of cpu's

find the number of cpu's

#+begin_src sh
sysctl kern.sched.topology_spec
#+end_src

*** vm config

#+begin_src sh
doas vi /home/djwilcox/vm/.templates/ubuntu.conf
#+end_src

#+begin_src conf
# =====================================================================
# ubuntu
# =====================================================================

loader="uefi"
cpu="4"
memory="4G"
network0_type="virtio-net"
network0_switch="public"

# =====================================================================
# Switch from file image to sparse Zvol block storage
# =====================================================================
disk0_type="nvme"
disk0_name="disk0"
disk0_dev="sparse-zvol"

# =====================================================================
# System context lines
# =====================================================================

utctime="yes"
virt_random="yes"
graphics="yes"
xhci_mouse="yes"
graphics_res="1920x1080"
uefi_vars="yes"
#+end_src

*** vm create

#+begin_src sh
doas vm create -t ubuntu -s 60G ubuntu
#+end_src

** vm install

use the -f option to run the vm in the current terminal

#+begin_src sh
doas vm install -f ubuntu ubuntu-26.04-live-server-amd64.iso
#+end_src

** vnc

intstall wlvncc.

#+begin_src sh
doas pkg install wlvncc
#+end_src

log in with vnc.

#+begin_src sh
wlvncc -s 127.0.0.1 5900
#+end_src

** ubuntu
*** podman

#+begin_src sh
sudo apt install git podman podman-compose pwgen
#+end_src

*** registeries

#+begin_src sh
sudo vi /etc/containers/registries.conf
#+end_src

append the following code to the end of the file.

#+begin_src conf
[registries.search]
registries = ['docker.io', 'quay.io']
#+end_src

save and quit.

*** app armour

#+begin_src sh
sudo vi /etc/apparmor.d/usr.bin.pasta
#+end_src

add the following code 

#+begin_src conf
  signal receive set=term peer=podman,
#+end_src

usr.bin.pasta

#+begin_src conf
# SPDX-License-Identifier: GPL-2.0-or-later
#
# PASST - Plug A Simple Socket Transport
#  for qemu/UNIX domain socket mode
#
# PASTA - Pack A Subtle Tap Abstraction
#  for network namespace/tap device mode
#
# contrib/apparmor/usr.bin.pasta - AppArmor profile for pasta(1)
#
# Copyright (c) 2022 Red Hat GmbH
# Author: Stefano Brivio <sbrivio@redhat.com>

abi <abi/4.0>,

include <tunables/global>

profile pasta /usr/bin/pasta{,.avx2} flags=(attach_disconnected) {
  include <abstractions/pasta>

  # podman
  signal receive set=term peer=podman,

  # Alternatively: include <abstractions/user-tmp>
  /tmp/**				rw,	# tap_sock_unix_open(),
						# tap_sock_unix_init(), pcap(),
						# pidfile_open(),
						# pidfile_write(),
						# logfile_init(),
						# pasta_open_ns()

  owner @{HOME}/**			w,	# pcap(), pidfile_open(),
						# pidfile_write()
}
#+end_src

*** loginctl

log into the server with ssh

set loginctl enable-linger with your username

#+begin_src sh
loginctl enable-linger djwilcox
#+end_src

*** clone the invidious repository

create the invidious-podman directory

#+begin_src sh
mkdir -p invidious-podman
#+end_src

change into the invidious-podman directory

#+begin_src sh
cd invidious-podman
#+end_src

clone the invidious git repo

#+begin_src sh
git clone https://github.com/iv-org/invidious.git
#+end_src

*** compose.yaml for pulling images

if you dont need the channel-fix you can use the following compose.yaml

and you can run the start-invidious script to pull down the images

#+begin_src yaml
version: "3"
services:

  invidious:
    #image: quay.io/invidious/invidious:latest
    image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    restart: unless-stopped
    # Remove "127.0.0.1:" if used from an external IP
    ports:
      - "3000:3000"
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        invidious_companion:
        # URL used for the internal communication between invidious and invidious companion
        # There is no need to change that except if Invidious companion does not run on the same docker compose file.
        - private_url: "http://companion:8282/companion"
        # IT is NOT recommended to use the same key as HMAC KEY. Generate a new key!
        # Use the key generated in the 2nd step
        invidious_companion_key: ${INVIDIOUS_COMPANION_KEY}
        # external_port:
        # domain:
        # https_only: false
        # statistics_enabled: false
        # Use the key generated in the 2nd step
        hmac_key: ${INVIDIOUS_HMAC_KEY}
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  companion:
    image: quay.io/invidious/invidious-companion:latest
    environment:
    # Use the key generated in the 2nd step
       SERVER_SECRET_KEY=${INVIDIOUS_COMPANION_KEY}
    restart: unless-stopped
    # Uncomment only if you have configured "public_url" for Invidious companion
    # Or if you want to use Invidious companion as an API in your program.
    # Remove "127.0.0.1:" if used from an external IP
    #ports:
    #  - "127.0.0.1:8282:8282"
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    cap_drop:
      - ALL
    read_only: true
    # cache for youtube library
    volumes:
      - companioncache:/var/tmp/youtubei.js:rw
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./invidious/config/sql:/config/sql
      - ./invidious/docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
  companioncache:
#+end_src

*** channel fix

change into the invidious directory

#+begin_src sh
cd invidious
#+end_src

Download the PR code into your existing directory

#+begin_src sh
git fetch origin pull/5736/head:channel-fix
#+end_src

Swap your working files over to the fix branch

#+begin_src sh
git checkout channel-fix
#+end_src

compose.yml

create the compose.yml file in invidious-podman directory

#+begin_src yaml
version: "3"
services:

  invidious:
    #image: quay.io/invidious/invidious:latest
    # image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    image: my-patched-invidious
    restart: unless-stopped
    # Remove "127.0.0.1:" if used from an external IP
    ports:
      - "3000:3000"
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        invidious_companion:
        # URL used for the internal communication between invidious and invidious companion
        # There is no need to change that except if Invidious companion does not run on the same docker compose file.
        - private_url: "http://companion:8282/companion"
        # IT is NOT recommended to use the same key as HMAC KEY. Generate a new key!
        # Use the key generated in the 2nd step
        invidious_companion_key: ${INVIDIOUS_COMPANION_KEY}
        # external_port:
        # domain:
        # https_only: false
        # statistics_enabled: false
        # Use the key generated in the 2nd step
        hmac_key: ${INVIDIOUS_HMAC_KEY}
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  companion:
    image: quay.io/invidious/invidious-companion:latest
    environment:
    # Use the key generated in the 2nd step
       SERVER_SECRET_KEY=${INVIDIOUS_COMPANION_KEY}
    restart: unless-stopped
    # Uncomment only if you have configured "public_url" for Invidious companion
    # Or if you want to use Invidious companion as an API in your program.
    # Remove "127.0.0.1:" if used from an external IP
    #ports:
    #  - "127.0.0.1:8282:8282"
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    cap_drop:
      - ALL
    read_only: true
    # cache for youtube library
    volumes:
      - companioncache:/var/tmp/youtubei.js:rw
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./invidious/config/sql:/config/sql
      - ./invidious/docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
  companioncache:
#+end_src

build invidious with the channel fix

#+begin_src sh
podman build \
  -t my-patched-invidious \
  --build-arg release=true \
  -f docker/Dockerfile \
  --from docker.io/crystallang/crystal:1.14.0-alpine .
#+end_src

*** start-invidious script

create the start-invidious script in the invidious-podman directory

make the script executable

#+begin_src sh
chmod +x start-invidious
#+end_src

start-invidious script

#+begin_src sh
#!/bin/sh

# This script generates a new secret key and starts invidious

# Generate a new random secret key.
SECRET_COMPANION_KEY=$(pwgen 16 1)
SECRET_HMAC_KEY=$(pwgen 16 1)

# Start the services, passing the generated secret key as an environment variable.
# The `podman-compose up -d` command will read this variable and apply it.
INVIDIOUS_COMPANION_KEY=$SECRET_COMPANION_KEY INVIDIOUS_HMAC_KEY=$SECRET_HMAC_KEY \
podman-compose up -d
#+end_src

*** start invidious

change directory into the invidious-podman directory

and run the start-invidious script

#+begin_src sh 
./start-invidious
#+end_src

*** login

in the bhyve vm find your ip address

#+begin_src sh
ip a
#+end_src

open your browser to the address of invidious

[[http://192.168.1.236:3000]]

select login and add a user name and password

on the next screen you have to complete a captcha
by adding the time shown in the clock

*** invidious vm start

#+begin_src sh
doas vm start ubuntu
#+end_src

*** stop invidious

change directory into the invidious git repository

#+begin_src sh 
podman-compose down
#+end_src

*** update invidious

change directory into the invidious git repository

#+begin_src sh
podman-compose pull
podman-compose up -d
podman image prune -f
#+end_src

*** vm destroy

#+begin_src sh
doas vm stop ubuntu
doas vm destroy ubuntu
#+end_src

alternative method

#+begin_src sh
doas bhyvectl --vm=ubuntu --destroy
#+end_src

*** vm start

#+begin_src sh
doas vm start ubuntu
#+end_src

*** vm stop

#+begin_src sh
doas vm stop ubuntu
#+end_src

*** ssh

copy your ssh keys to the vm and enter your password.

#+begin_src sh
ssh-copy-id djwilcox@192.168.1.236
#+end_src

log in with ssh.

#+begin_src sh
ssh djwilcox@192.168.1.236
#+end_src

*** podman remove all containers

#+begin_src sh
podman rmi $(podman images -qa) -f
#+end_src

#+begin_src sh
podman system prune --all --force && podman rmi --all --force
#+end_src
