#+STARTUP: content
#+OPTIONS: num:nil
#+OPTIONS: author:nil

* pef encrypted directory and pam_pefs

pefs install

#+BEGIN_SRC sh
sudo pkg install pefs-kmod
#+END_SRC

** pefs load kernel module

Once installed, we next need to load the pefs kernel module:

#+BEGIN_SRC sh
sudo kldload pefs
#+END_SRC

check the pefs kernel module is loaded with kldstat

#+BEGIN_SRC sh
kldstat
#+END_SRC

If we want to keep this module loaded across reboots, add it to /boot/loader.conf:

#+BEGIN_SRC sh
sudo vim /boot/loader.conf
#+END_SRC

+ then add the following line to /boot/load.conf

#+BEGIN_SRC sh
pefs_load="YES"
#+END_SRC

*** pefs pam set up

Please note that your home directory has to be mounted, I mount it in
/etc/rc.local, but don't add any keys. pam_pefs adds the key. Also note
that it has to be exactly your home directory (/home/gleb in my case), to
prevent possible attacks. And keychain database has to be created, so
that pam_pefs knows how to verify the key.

Details on how to create it available in my original email. That's
rather inconvenient procedure, but you need to do it just once, it's so
complicated because pefs is read-only if no key specified, but database
should not be encrypted to make it accessible by pam_pefs:


create directory to encrypt

#+BEGIN_SRC sh
mkdir -p ~/storage
#+END_SRC

change permissions so only our user can read and write to the directory

#+BEGIN_SRC sh
chmod 700 ~/storage
#+END_SRC

+ mount pefs file system

#+BEGIN_SRC sh
pefs mount ~/storage ~/storage
#+END_SRC

+ add the pefs key

#+BEGIN_SRC sh
pefs addkey -a aes256 ~/storage
#+END_SRC

+ add the pefs keychain

#+BEGIN_SRC sh
pefs addchain -Z -a aes256 ~/storage
#+END_SRC

dont encrypt .pefs.db
move the ~/storage/.pefs.db to /tmp

#+BEGIN_SRC sh
mv ~/storage/.pefs.db /tmp
#+END_SRC

+ umount the pefs directory

#+BEGIN_SRC sh
umount ~/storage
#+END_SRC

+ move the /tmp/.pefs.db file back into the pefs encrypted directory

#+BEGIN_SRC sh
mv /tmp/.pefs.db ~/storage
#+END_SRC

+ mount the pefs directory

#+BEGIN_SRC sh
pefs mount ~/storage ~/storage
#+END_SRC

add the pefs key
Use -c option to verify key is in databas

#+BEGIN_SRC 
pefs addkey -c -a aes256 ~/storage
#+END_SRC

*** pefs unlock at login 

Edit /etc/pam.d/system:

#+BEGIN_SRC sh
sudo vim /etc/pam.d/system
#+END_SRC

add the following code under the listed sections

#+BEGIN_SRC sh
# auth
auth       sufficient  pam_pefs.so     try_first_pass delkeys

# session
session    optional    pam_pefs.so     delkeys
#+END_SRC

the complete file should look like this 

#+BEGIN_SRC sh
#
# $FreeBSD: releng/11.2/etc/pam.d/system 197769 2009-10-05 09:28:54Z des $
#
# System-wide defaults
#

# auth
auth		sufficient	pam_opie.so		no_warn no_fake_prompts
auth		requisite	pam_opieaccess.so	no_warn allow_local
#auth		sufficient	pam_krb5.so		no_warn try_first_pass
#auth		sufficient	pam_ssh.so		no_warn try_first_pass
auth        sufficient  pam_pefs.so     try_first_pass delkeys
auth		required	pam_unix.so		no_warn try_first_pass nullok

# account
#account	required	pam_krb5.so
account		required	pam_login_access.so
account		required	pam_unix.so

# session
#session	optional	pam_ssh.so		want_agent
session     optional    pam_pefs.so     delkeys
session		required	pam_lastlog.so		no_fail

# password
#password	sufficient	pam_krb5.so		no_warn try_first_pass
password	required	pam_unix.so		no_warn try_first_pass
#+END_SRC

*** pefs fstab

edit fstab to mount the pefs directory

#+BEGIN_SRC sh
sudo vim /etc/fstab
#+END_SRC

replace username with your username and storage with the name of your pefs directory  
late is needed for zfs filesystems to ensure that the pefs directory is correctly mounted

#+BEGIN_SRC sh
# pefs encrypted directory
/home/username/storage /home/username/storage pefs rw,late 0 0
#+END_SRC

**** pefs reference

+ [[pefs site][http://pefs.io/]]
+ [[bsd now pefs][http://www.bsdnow.tv/tutorials/pefs]]
+ [[pefs email message][https://lists.freebsd.org/pipermail/freebsd-current/2010-September/019691.html]]
+ [[pefs email message][https://lists.freebsd.org/pipermail/freebsd-current/2010-September/019708.html]]
