#+STARTUP: content
* podman freebsd
** resources

[[https://podman.io/docs/installation#installing-on-freebsd-140]]

[[https://docs.skunkwerks.at/s/fUiAmi4pE#]]

** podman install

There's also a podman-suite meta package that will pull additional packages for you (buildah, skopeo).

To install podman-compose you need to install the py311-podman-compose package as well

#+begin_src sh
doas pkg install podman-suite py311-podman-compose
#+end_src

*** fstab

To properly support Podman's container restart policy, conmon needs fdescfs(5) to be mounted on /dev/fd.

If /dev/fd is not already mounted:

#+begin_src sh
doas mount -t fdescfs fdesc /dev/fd
#+end_src

To make it permanent, add the following line to /etc/fstab:

#+begin_src sh
doas vi /etc/fstab
#+end_src

#+begin_src conf
fdesc   /dev/fd         fdescfs         rw      0       0
#+end_src

#+begin_src sh
doas mount -t procfs proc /proc
#+end_src

*** linux

Enable Linux compatibility at boot

#+begin_src sh
doas sysrc linux_enable="YES"
#+end_src

Start the service and load the 64-bit Linux kernel module

#+begin_src sh
doas service linux start
#+end_src

load linux 

#+begin_src sh
doas kldload linux64
#+end_src

Ensure it loads every boot

#+begin_src sh
doas sysrc kld_list+="linux64"
#+end_src

*** pf

#+begin_src sh
service pf enable
#+end_src

#+begin_src sh
service pf start
#+end_src

#+begin_src sh
doas echo 'pf_load="YES"' >> /boot/loader.conf
#+end_src

#+begin_src sh
kldload pf
#+end_src

Container networking relies on NAT to allow container network packets out to the host's network. This requires a PF firewall to perform the translation. A simple example is included - to use it:

#+begin_src sh
cp /usr/local/etc/containers/pf.conf.sample .
#+end_src

pf.conf.sample

#+begin_src conf
# Change these to the interface(s) with the default route
v4egress_if = "ix0"
v6egress_if = "ix0"

nat on $v4egress_if inet from <cni-nat> to any -> ($v4egress_if)
nat on $v6egress_if inet6 from <cni-nat> to !ff00::/8 -> ($v6egress_if)

rdr-anchor "cni-rdr/*"
nat-anchor "cni-rdr/*"
table <cni-nat>
#+end_src

Edit /etc/pf.conf and set v4egress_if, v6egress_if variables to your network interface(s)s

The sample PF configuration includes support for port redirections. These are implemented as redirect rules in anchors nested under cni-rdr.

Redirect rules will work if the destination address is localhost (e.g. 127.0.0.1 or ::1) - to enable this, the following line must be included in your /etc/pf.conf:

#+begin_src conf
nat-anchor "cni-rdr/*"
#+end_src

#+begin_src sh
doas vi /etc/pf.conf
#+end_src

#+begin_src conf
#=========================================================================#
# pf.conf
#=========================================================================#

#=========================================================================#
# variables, macro and tables                                             #
#=========================================================================#

int_if="lagg0" # lagg0 failover
v4egress_if = "lagg0" # podman
v6egress_if = "lagg0" # podman
vpn_if="tun0" # vpn interface
all_networks="0.0.0.0/0"
vpn_network="$vpn_if:network"
# 6881, 6882 = transmission. , 22000, 22000, 21027 = syncthing
# searxng podman = 8080
tcp_services = "{ ntp, 6881, 22000, 8080 }" # tcp services - torrent
udp_services = "{ ntp, 6882, 22000, 21027 }" # udp services - torrent
#nfs_services = "{ 2049 }" # 2049 = nfs
icmp_types = "{ echoreq, unreach }"
tcp_state="flags S/SA keep state"
udp_state="keep state"

#table <internet> { $all_networks, !self, !$int_if:network } # internet
table <lan> { $int_if:network, !self }                      # lan network
table <myself> { self }                                     # self
table <martians> { 0.0.0.0/8 10.0.0.0/8 127.0.0.0/8 169.254.0.0/16     \
	 	   172.16.0.0/12 192.0.0.0/24 192.0.2.0/24 224.0.0.0/3 \
	 	   192.168.0.0/16 198.18.0.0/15 198.51.100.0/24        \
	 	   203.0.113.0/24 }                         # broken networks

#=========================================================================#
# global policy                                                           #
#=========================================================================#

set block-policy drop
set loginterface $int_if
set fingerprints "/etc/pf.os"
set skip on { lo0, cni-podman0 }
scrub in all fragment reassemble no-df max-mss 1440
# nat jail
nat on $int_if from {lo1:network} to any -> ($int_if)
# podman nat
nat on $v4egress_if inet from <cni-nat> to any -> ($v4egress_if)
nat on $v6egress_if inet6 from <cni-nat> to !ff00::/8 -> ($v6egress_if)
# podman anchor
rdr-anchor "cni-rdr/*"
nat-anchor "cni-rdr/*"
table <cni-nat>
# antispoof
antispoof log quick for { lo $int_if } label "block_spoofing"


#=========================================================================#
# block                                                                   #
#=========================================================================#

block log all # block log all
block return out quick inet6 all tag IPV6 # block ipv6 
block in quick inet6 all tag IPV6 # block ipv6


#=========================================================================#
# anchors                                                                 #
#=========================================================================#

# openvpn - anchor
anchor "openvpn"

#=========================================================================#
# traffic tag                                                             #
#=========================================================================#

# icmp
pass inet proto icmp all icmp-type $icmp_types keep state tag ICMP

# Allow the tcp and udp services defined in the macros at the top of the file
pass in on $int_if inet proto tcp from any to ($int_if) port $tcp_services $tcp_state tag TCP_IN
pass in on $int_if inet proto udp from any to ($int_if) port $udp_services $udp_state tag UDP_IN

# outbound traffic
block out on $int_if all
pass out quick on $int_if all modulate state
#+end_src

restart pf

#+begin_src sh
doas service pf restart
#+end_src

*** zfs

create a zfs dataset for podman

#+begin_src sh
doas zfs create -o mountpoint=/var/db/containers zroot/containers
#+end_src

*** sysctl

apply net.pf.filter_local=1

#+begin_src sh
doas sysctl net.pf.filter_local=1
#+end_src

set net.pf.filter_local=1 permanently

#+begin_src sh
doas vi /etc/sysctl.conf
#+end_src

#+begin_src conf
#=========================================================================#
# podman
#=========================================================================#

net.pf.filter_local=1
#+end_src

*** podman enable

Podman can restart containers after a host is rebooted. To enable this, use:

#+begin_src sh
doas sysrc podman_enable=YES
#+end_src

or you can manually edit your /etc/rc.conf

#+begin_src sh
doas vi /etc/rc.conf
#+end_src

#+begin_src conf
#=========================================================================#
# podman
#=========================================================================#

podman_enable=YES
#+end_src

*** registries.conf

edit the registries.conf to define repos to podman

#+begin_src sh
doas vi /usr/local/etc/containers/registries.conf
#+end_src

append the following code

#+begin_src conf
unqualified-search-registries = ["docker.io", "quay.io", "ghcr.io"]

[[registry]]
location = "docker.io"

[[registry]]
location = "quay.io"

[[registry]]
location = "ghcr.io"
#+end_src

*** podman zfs dataset for config files

we will also create a zfs dataset for our podman config files

change djwilcox to your username in the code below

#+begin_src sh
doas zfs create zroot/home/djwilcox/podman
#+end_src

#+begin_src sh
doas chown -R djwilcox:djwilcox /home/djwilcox/podman
#+end_src

*** doas podman set up

set up doas so you can can run podman without being prompted for a password

#+begin_src sh
doas vi 
#+end_src

change username to your username

#+begin_src conf
#=========================================================================#
# doas.conf
#=========================================================================#

#=========================================================================#
# permit user
#=========================================================================#

permit keepenv setenv { PATH } username


#=========================================================================#
# allow root to switch to our user
#=========================================================================#

permit nopass keepenv setenv { PATH } root as username


#=========================================================================#
# permit user - no pass
#=========================================================================#

permit nopass keepenv setenv { PATH } username


#=========================================================================#
# podman permit user - no pass
#=========================================================================#

permit nopass keepenv username cmd /usr/local/bin/podman


#=========================================================================#
# root as root
#=========================================================================#

permit nopass keepenv root as root
#+end_src

** podman test

run the hello workd podmand container

#+begin_src sh
doas podman run --rm docker.io/dougrabson/hello
#+end_src

** searxng
*** pull the images

specify os linux to pull the images

#+begin_src sh
doas podman pull --os linux docker.io/library/redis:7-bookworm
#+end_src

#+begin_src sh
doas podman pull --os linux docker.io/searxng/searxng:latest
#+end_src

*** searxng config
**** compose.yaml

#+begin_src yaml
version: "3.8"

services:
  redis:
    container_name: redis
    image: docker.io/library/redis:7-bookworm
    command: ["redis-server", "--save", "30", "1", "--loglevel", "warning"]
    restart: unless-stopped
    network_mode: host
    volumes:
      - valkey-data2:/data

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${HOME}/podman/searxng:/etc/searxng:rw
      - ./searxng-genkey:/usr/local/bin/searxng-genkey
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080
      # Use 127.0.0.1 because network_mode: host shares the interface
      - SEARXNG_REDIS_URL=redis://127.0.0.1:6379/0
      - SEARXNG_SECRET=${SEARXNG_SECRET}
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}

networks:
  searxng:

volumes:
  searxng_config:
  valkey-data2:

#+end_src

**** limiter.toml

#+begin_src toml
# This configuration file updates the default configuration file
# See https://github.com/searxng/searxng/blob/master/searx/limiter.toml

[botdetection.ip_limit]
# activate link_token method in the ip_limit method
link_token = true

#+end_src

**** searxng-genkey

#+begin_src sh
#!/bin/sh

# This script generates a new secret key and starts the SearXNG containers.

# Generate a new random 32-byte hex secret key.
SEARXNG_SECRET=$(openssl rand -hex 32)
#+end_src

**** settings.yml

#+begin_src yaml
# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: ""
  limiter: false  # changed to false for open-webui
  image_proxy: true
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
general:
  # Debug mode, only for development. Is overwritten by ${SEARXNG_DEBUG}
  debug: false
  # displayed name
  instance_name: "Searxng"
  # For example: https://example.com/privacy
  privacypolicy_url: false
  # use true to use your own donation page written in searx/info/en/donate.md
  # use false to disable the donation link
  donation_url: false
  # mailto:contact@example.com
  contact_url: false
  # record stats
  enable_metrics: true
  # expose stats in open metrics format at /metrics
  # leave empty to disable (no password set)
  # open_metrics: <password>
  open_metrics: ''

search:
  # Filter results. 0: None, 1: Moderate, 2: Strict
  safe_search: 0
  # Existing autocomplete backends: "360search", "baidu", "brave", "dbpedia", "duckduckgo", "google", "yandex",
  # "mwmbl", "seznam", "sogou", "stract", "swisscows", "qwant", "wikipedia" -
  # leave blank to turn it off by default.
  autocomplete: ""
  # minimun characters to type before autocompleter starts
  autocomplete_min: 4
  # backend for the favicon near URL in search results.
  # Available resolvers: "allesedv", "duckduckgo", "google", "yandex" - leave blank to turn it off by default.
  favicon_resolver: ""
  # Default search language - leave blank to detect from browser information or
  # use codes from 'languages.py'
  default_lang: "auto"
  # max_page: 0  # if engine supports paging, 0 means unlimited numbers of pages
  # Available languages
  # languages:
  #   - all
  #   - en
  #   - en-US
  #   - de
  #   - it-IT
  #   - fr
  #   - fr-BE
  # ban time in seconds after engine errors
  ban_time_on_fail: 5
  # max ban time in seconds after engine errors
  max_ban_time_on_fail: 120
  suspended_times:
    # Engine suspension time after error (in seconds; set to 0 to disable)
    # For error "Access denied" and "HTTP error [402, 403]"
    SearxEngineAccessDenied: 86400
    # For error "CAPTCHA"
    SearxEngineCaptcha: 86400
    # For error "Too many request" and "HTTP error 429"
    SearxEngineTooManyRequests: 3600
    # Cloudflare CAPTCHA
    cf_SearxEngineCaptcha: 1296000
    cf_SearxEngineAccessDenied: 86400
    # ReCAPTCHA
    recaptcha_SearxEngineCaptcha: 604800

  # remove format to deny access, use lower case.
  # formats: [html, csv, json, rss]
  formats:
    - html
    - csv
    - json
    - rss
categories_as_tabs:
  general:
  images:
  videos:
  news:
  it:
  files:
  map:
  social media:

#+end_src

*** start searxng 

#+begin_src sh
doas podman-compose up -d
#+end_src

*** stop searxng

#+begin_src sh
doas podman-compose down
#+end_src

*** podman-compose pull

update the containers

#+begin_src sh
doas podman pull --os linux docker.io/searxng/searxng:latest
doas podman pull --os linux docker.io/library/redis:7-bookworm
#+end_src

clean up old images

#+begin_src sh
doas podman-compose up -d
doas podman image prune -f
#+end_src

*** permisions

note the permissions on the searxng directory and files will be changed to tests

#+begin_example
-rwxr-xr-x  1 tests    tests     916 26 Apr 18:59 compose.yaml
-rwxr-xr-x  1 tests    tests     232 26 Apr 14:41 limiter.toml
-rwxr-xr-x  1 tests    tests     175 26 Apr 14:41 searxng-genkey
-rwxr-xr-x  1 tests    tests    2791 26 Apr 18:44 settings.yml
#+end_example

so you will need to use doas or sudo to edit the files

** mcp-searxng-enhanced
*** resources

[[https://github.com/NapoleonWils0n/mcp-searxng-enhanced]]

*** download the git repo

#+begin_src sh
git clone https://github.com/NapoleonWils0n/mcp-searxng-enhanced.git
#+end_src

*** build mcp-searxng-enhanced

#+begin_src sh
cd mcp-searxng-enhanced
#+end_src

#+begin_src sh
doas podman build --network host -t mcp-searxng-enhanced:local .
#+end_src

*** emacs init.el

#+begin_src sh
vi ~/.config/emacs/init.el
#+end_src

Change usernname to yout username

#+begin_src emacs-lisp
;; ----------------------------------------------------------------------------------
;; mcp server
;; ----------------------------------------------------------------------------------

(use-package mcp
  :after gptel
  :custom
  (mcp-hub-servers 
   `(("searxng" . (
      :command "/home/username/bin/mcp-searxng-enhanced"
      ))))
  :config
  (require 'mcp-hub))
#+end_src

**** create a bin directory

#+begin_src sh
mkdir -p ~/bin
#+end_src

**** zshenv add the bin directory to your shell path

#+begin_src sh
vi ~/.zshenv
#+end_src

#+begin_src sh
#===============================================================================
# ~/.zshenv
#===============================================================================

#===============================================================================
# Path
#===============================================================================

typeset -U PATH path
path=("$HOME/bin" "/usr/local/bin" "$path[@]")
export PATH
#+end_src

**** mcp-searxng-enhanced script

#+begin_src sh
chmod +x ~/bin/mcp-searxng-enhanced
#+end_src

#+begin_src sh
#!/bin/sh

# Force unbuffered output so the stream isn't delayed
export PYTHONUNBUFFERED=1

# Filter the output:
# 1. '--line-buffered' ensures Emacs gets the data immediately.
# 2. '^{"jsonrpc"' matches only the start of valid MCP/JSON-RPC messages.
exec /usr/local/bin/doas /usr/local/bin/podman run -i --rm --network=host \
    -e "SEARXNG_URL=http://localhost:8080" \
    -e "PYTHONUNBUFFERED=1" \
    localhost/mcp-searxng-enhanced:local | grep --line-buffered '^{"jsonrpc"'
#+end_src

