#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Sat Feb 27, 2016
#
# DESC: Elvi to search 1337x
# elvis: 1337x		-- Search 1337x for torrents (1337x.to)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search 1337x (1337x.to) for torrents
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://1337x.to"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://1337x.to/search/${escaped_args}/1/"
fi
