#!/bin/sh
# DESC: Elvi to search dailymotion
# elvis: dailymotion     -- Search dailymotion (https://dailymotion.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search dailymotion (https://dailymotion.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://dailymotion.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://dailymotion.com/search/${escaped_args}/videos"
fi
