#!/bin/sh
# DESC: Elvi to search Google Video
# elvis: iplayer         -- Search bbc iplayer (https://bbc.co.uk/iplayer)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search bbc iplayer (https://bbc.co.uk/iplayer)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://bbc.co.uk/iplayer"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://bbc.co.uk/iplayer/search?q=${escaped_args}"
fi
