#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Wed Mar 11, 2020
#
# DESC: Elvi to search limetorrents
# elvis: limetorrents    -- Search limetorrents for torrents (limetorrents.info)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search limetorrents (limetorrents.info) for torrents
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://limetorrents.info"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.limetorrents.info/search/all/${escaped_args}"
fi
