#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Sat Nov 17 2012
#
# DESC: Elvi to search stackexchange computer questions
# elvis: stackexchange	-- Search StackExchange for computer questions (www.stackexchange.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search stackexchange (www.stackexchange.org) for computer questions
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.stackexchange.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://stackexchange.com/search?q=${escaped_args}"
fi
