#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Sun Feb 14, 2016
#
# DESC: Elvi to search sunxdcc for irc xdcc files
# elvis: sunxdcc		-- Search sunxdcc for irc xdcc files (http://sunxdcc.com/)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search sunxdcc (http://sunxdcc.com/) for irc xdcc files 
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://sunxdcc.com/"
else
    escaped_args=$(w3_url_of_arg $w3_args)
    w3_browse_url "http://sunxdcc.com/?sterm=${escaped_args}%20-tar%20-rar"
fi
