#!/bin/sh
# DESC: Elvi to search thepacket for irc xdcc files
# elvis: thepacket     		-- Search thepacket for irc xdcc files (https://thepacket.info/)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search thepacket (https://thepacket.info/) for irc xdcc files 
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://thepacket.info"
else
    escaped_args=$(w3_url_of_arg $w3_args)
    w3_browse_url "https://thepacket.info/?q=${escaped_args}"
fi
