#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Wed Nov 21, 2018
#
# DESC: Elvi to search torrentgalaxy
# elvis: torrentgalaxy   -- Search torrentgalaxy for torrents (torrentgalaxy.to)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search torrentgalaxy (torrentgalaxy.to) for torrents
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://torrentgalaxy.to"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://torrentgalaxy.to/torrents.php?search=${escaped_args}"
fi
