#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Wed June 14, 2017
#
# DESC: Elvi to search xdcceu for irc xdcc files
# elvis: xdcceu		-- Search xdcceu for irc xdcc files (http://xdcc.eu/)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search xdcceu (http://xdcc.eu/) for irc xdcc files 
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://xdcc.eu/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.xdcc.eu/search.php?searchkey=${escaped_args}"
fi
