#!/bin/sh


#===============================================================================
# relay-remote stream a remote video to a named pipe
#===============================================================================


#===============================================================================
# script usage
#===============================================================================

usage () {
# if argument passed to function echo it
[ -z "${1}" ] || echo "! ${1}"
# display help
echo "\
$(basename "$0") -i input -s 00:00:00 -t 00:00:00"
exit 2
}


#===============================================================================
# error messages
#===============================================================================

INVALID_OPT_ERR='Invalid option:'
REQ_ARG_ERR='requires an argument'
WRONG_ARGS_ERR='wrong number of arguments passed to script'


#===============================================================================
# check number of aruments passed to script
#===============================================================================

[ $# -gt 0 ] || usage "${WRONG_ARGS_ERR}"


#===============================================================================
# getopts check options passed to script
#===============================================================================

while getopts ':s:i:t:h' opt
do
  case ${opt} in
     s) start="${OPTARG}";;
     i) input="${OPTARG}";;
     t) end="${OPTARG}";;
     h) usage;;
     \?) usage "${INVALID_OPT_ERR} ${OPTARG}" 1>&2;;
     :) usage "${INVALID_OPT_ERR} ${OPTARG} ${REQ_ARG_ERR}" 1>&2;;
  esac
done
shift $((OPTIND-1))


#===============================================================================
# named pipe
#===============================================================================

# check if the /tmp/relay named pipe exist otherwise create it
[ -p /tmp/relay ] || mkfifo /tmp/relay


#===============================================================================
# url
#===============================================================================

# yt-dlp url
url=$(yt-dlp -f b -g --no-playlist "${input}")

# check number of stream links
streamcount=$(echo "${url}" | awk 'END{print NR}')


#===============================================================================
# one stream containing audio and video
#===============================================================================

one_stream () {
ffmpeg \
-hide_banner \
-stats -v panic \
-y \
-i "${url}" \
-c:a copy -c:v copy \
-tune zerolatency \
-f matroska /tmp/relay
}


#===============================================================================
# calculate duration using your sexagesimal math
#===============================================================================

get_duration() {
    printf "%s %s\n" "$1" "$2" | awk '
        {
          start = $1
          end = $2
          if (start ~ /:/) {
            split(start, t, ":")
            sseconds = (t[1] * 3600) + (t[2] * 60) + t[3] 
          }
          if (end ~ /:/) {
            split(end, t, ":")
            eseconds = (t[1] * 3600) + (t[2] * 60) + t[3] 
          }
          duration = eseconds - sseconds
          printf("%s\n"), duration
        }' \
    | awk -F. '
        NF==1 { printf("%02d:%02d:%02d\n"), ($1 / 3600), ($1 % 3600 / 60), ($1 % 60) }
        NF==2 { printf("%02d:%02d:%02d.%s\n"), ($1 / 3600), ($1 % 3600 / 60), ($1 % 60), ($2) }'
}


#===============================================================================
# trim video using stream copying
#===============================================================================

one_stream_trim () {
    if [ -n "${start}" ] && [ -n "${end}" ]; then
        duration=$(get_duration "${start}" "${end}")
        duration_arg="-t ${duration}"
    elif [ -n "${end}" ]; then
        duration_arg="-t ${end}"
    fi

    # shellcheck disable=SC2086
    ffmpeg \
    -hide_banner \
    -stats -v panic \
    -y \
    -ss "${start}" \
    -i "${url}" \
    ${duration_arg} \
    -c:a copy -c:v copy \
    -tune zerolatency \
    -f matroska /tmp/relay
}


#===============================================================================
# two streams containing audio and video
#===============================================================================

# copy audio and video streams
two_streams () {
video_url=$(echo "${url}" | awk 'BEGIN{ RS ="" ; FS ="\n" }{print $1}')
audio_url=$(echo "${url}" | awk 'BEGIN{ RS ="" ; FS ="\n" }{print $2}')

    # shellcheck disable=SC2086
    ffmpeg \
    -hide_banner \
    -stats -v panic \
    -y \
    -i "${video_url}" \
    -i "${audio_url}" \
    -c:a copy -c:v copy \
    -tune zerolatency \
    -f matroska /tmp/relay
}


#===============================================================================
# trim two streams containing audio and video
#===============================================================================

two_streams_trim () {
video_url=$(echo "${url}" | awk 'BEGIN{ RS ="" ; FS ="\n" }{print $1}')
audio_url=$(echo "${url}" | awk 'BEGIN{ RS ="" ; FS ="\n" }{print $2}')

    if [ -n "${start}" ] && [ -n "${end}" ]; then
        duration=$(get_duration "${start}" "${end}")
        duration_arg="-t ${duration}"
    elif [ -n "${end}" ]; then
        duration_arg="-t ${end}"
    fi

    # shellcheck disable=SC2086
    ffmpeg \
    -hide_banner \
    -stats -v panic \
    -y \
    -ss "${start}" \
    -i "${video_url}" \
    -i "${audio_url}" \
    ${duration_arg} \
    -c:a copy -c:v copy \
    -tune zerolatency \
    -f matroska /tmp/relay
}

#===============================================================================
# case statement check for number of streams
#===============================================================================

if [ -n "${start}" ] || [ -n "${end}" ]; then
    case "${streamcount}" in
        1) one_stream_trim ;;
        2) two_streams_trim ;;
        *) usage ;;
    esac
else
    case "${streamcount}" in
        1) one_stream ;;
        2) two_streams ;;
        *) usage ;;
    esac
fi
