#!/bin/sh

#===============================================================================
# srt-mpv - receive a srt stream with mpv
#===============================================================================


#===============================================================================
# script usage
#===============================================================================

usage () {
# if argument passed to function echo it
[ -z "${1}" ] || echo "! ${1}"
# display help
echo "\
$(basename "$0") -i ip -p port -l latency"
exit 2
}

#===============================================================================
# error messages
#===============================================================================

INVALID_OPT_ERR='Invalid option:'
REQ_ARG_ERR='requires an argument'
WRONG_ARGS_ERR='wrong number of arguments passed to script'


#===============================================================================
# getopts check options passed to script
#===============================================================================

while getopts 'i:p:l:h' opt
do
  case ${opt} in
     i) ip="${OPTARG}";;
     p) port="${OPTARG}";;
     l) latency="${OPTARG}";;
     h) usage;;
     \?) usage "${INVALID_OPT_ERR} ${OPTARG}" 1>&2;;
     :) usage "${INVALID_OPT_ERR} ${OPTARG} ${REQ_ARG_ERR}" 1>&2;;
  esac
done
shift $((OPTIND-1))

#===============================================================================
# defaults
#===============================================================================

# default ip
ip_default='192.168.1.131'

# default latency
latency_default='1000'

# default port
port_default='6882'


#===============================================================================
# srt_recv function
#===============================================================================

srt_recv () {
srt-live-transmit "srt://${ip:=${ip_default}}:${port:=${port_default}}?mode=listener&latency=${latency:=${latency_default}}&timeout=5000000" file://con | mpv --fs -
}

#===============================================================================
# run srt_recv function
#===============================================================================

srt_recv
