#+STARTUP: content
* emacs completion
** org mode completion

#+begin_example
M-TAB
#+end_example

[[https://orgmode.org/manual/Completion.html]]

Complete word at point.

At the beginning of an empty headline, complete TODO keywords.
After ‘\’, complete TeX symbols supported by the exporter.
After ‘:’ in a headline, complete tags. Org deduces the list of tags from the ‘TAGS’ in-buffer option (see Setting Tags), the variable org-tag-alist, or from all tags used in the current buffer.
After ‘:’ and not in a headline, complete property keys. The list of keys is constructed dynamically from all keys used in the current buffer.
After ‘[[’, complete link abbreviations (see Link Abbreviations).
After ‘[[*’, complete headlines in the current buffer so that they can be used in search links like: ‘[[*find this headline]]’
After ‘#+’, complete the special keywords like ‘TYP_TODO’ or file-specific ‘OPTIONS’. After option keyword is complete, pressing M-TAB again inserts example settings for this keyword.
After ‘STARTUP’ keyword, complete startup items.
When point is anywhere else, complete dictionary words using Ispell. 

** ispell complete word

#+begin_example
C-M-i
#+end_example

** hippie expand

#+begin_example
M-/
#+end_example
