#+TITLE: searxng search
#+OPTIONS: toc:nil num:nil
#+STARTUP: overview hideblocks 
#+SELECT_TAGS: export
#+PROPERTY: header-args :results output wrap append :noweb yes :var page=1 query="buster keaton"
* usage
** global search

edit the PROPERTY at the top of the file and change the query and page number

#+begin_example
#+PROPERTY: header-args :results output wrap append :noweb yes :var page=1 query="buster keaton"
#+end_example

** custom search

You can override the global search using a custom search using header-args

As shown below without the comma before the heading

#+begin_example
,*** custom general search
:PROPERTIES:
:header-args:sh: :var category="general" page=1 query="harold lloyd"
:END:
#+NAME: custom-general-search
#+BEGIN_SRC sh 
<<general-noweb>>
#+end_src
#+end_example

** org refesh

To tell Org-mode to re-scan the entire file for changes to #+PROPERTY or #+OPTIONS lines, put your cursor anywhere on a line starting with #+ and press:

#+begin_example
C-c C-c
#+end_example

Sometimes Org-mode caches the result of a code block and won't run it again if it thinks nothing has changed. To force a fresh execution regardless of the cache, use the "Universal Argument":

#+begin_example
C-u C-c C-c
#+end_example

C-c C-c (on a #+ line): Refreshes global properties/settings for the buffer.

C-c C-c (on a code block): Runs that specific search.

C-u C-c C-c (on a code block): Forces the search to run even if Org is being stubborn.

** export results

1) Move your cursor so it is physically on the * results headline

2) Press C-c C-e to open the export settings
  
3) Press C-s this will toggle the setting from Buffer to Subtree

4) Once it says Subtree, press your export keys (e.g., m m for Markdown).

* noweb code blocks
** searxng-curl noweb
:CODE:
#+NAME: searxng-curl
#+begin_src sh 
curl -s -G "http://localhost:8080/search" \
--data-urlencode "q=${query}" \
--data "format=json" \
--data "categories=${category}" \
--data "pageno=${page}" \
--data "language=auto" \
--data "time_range=" \
--data "safesearch=0"
#+end_src
:END:

** general noweb
:CODE:
#+NAME: general-noweb
#+begin_src sh :noweb yes
<<searxng-curl>> | jq -rj '.results | sort_by(.score) | reverse | to_entries[] | 
"\(.key + 1): [[\(.value.url)][\(.value.title)]]\n" + 
(if (.value.content and .value.content != "") then "\n\(.value.content)\n\n" else "\n" end) +
"Score: \(.value.score)\nCategory: \(.value.category)\nEngine: \(.value.engines)\n\n"'
#+end_src
:END:

** image noweb
:CODE:
#+NAME: image-noweb
#+begin_src sh :noweb yes
<<searxng-curl>> | jq -rj '.results | sort_by(.score) | reverse | to_entries[] | "\(.key + 1): [[\(.value.url)][\(.value.title)]]\n\n[[\(.value.img_src)]]\n\nResolution: \(.value.resolution)\nFile Size: \(.value.filesize)\nScore: \(.value.score)\nCategory: \(.value.category)\nEngine: \(.value.engines)\n\n"'
#+end_src
:END:

** video noweb
:CODE:
#+NAME: video-noweb
#+begin_src sh :noweb yes
<<searxng-curl>> | jq -rj '.results | sort_by(.score) | reverse | to_entries[] | "\(.key + 1): [[\(.value.url)][\(.value.title)]]\n\n\(.value.content // "No snippet available")\n\nLength: \(.value.length // "N/A")\nPublished: \(.value.pubdate // "N/A")\nAuthor: \(.value.author)\nScore: \(.value.score)\nCategory: \(.value.category)\nEngine: \(.value.engines)\n\n"'
#+end_src
:END:

** news noweb
:CODE:
#+NAME: news-noweb
#+begin_src sh :noweb yes
<<searxng-curl>> | jq -rj '.results | sort_by(.score) | reverse | to_entries[] | 
"\(.key + 1): [[\(.value.url)][\(.value.title)]]\n" + 
(if (.value.content and .value.content != "") then "\n\(.value.content)\n\n" else "\n" end) +
"Score: \(.value.score)\nCategory: \(.value.category)\nEngine: \(.value.engines)\n\n"'
#+end_src
:END:

* search
** general
:PROPERTIES:
:header-args:sh: :var category="general"
:END:
#+NAME: general-search
#+BEGIN_SRC sh 
<<general-noweb>>
#+end_src

** images
:PROPERTIES:
:header-args:sh: :var category="images"
:END:
#+NAME: image-search
#+BEGIN_SRC sh
<<image-noweb>>
#+end_src

** videos
:PROPERTIES:
:header-args:sh: :var category="videos"
:END:
#+NAME: video-search
#+BEGIN_SRC sh
<<video-noweb>>
#+end_src

** news
:PROPERTIES:
:header-args:sh: :var category="news"
:END:
#+NAME: news-search
#+BEGIN_SRC sh
<<news-noweb>>
#+end_src

** custom 
*** custom general
:PROPERTIES:
:header-args:sh: :var category="general" page=1 query="!ddg nixos"
:END:
#+NAME: custom-general-search
#+BEGIN_SRC sh 
<<general-noweb>>
#+end_src

* results :export:
** general
#+RESULTS: general-search

** image
#+RESULTS: image-search

** video
#+RESULTS: video-search

** news
#+RESULTS: news-search

** custom
*** custom general
#+RESULTS: custom-general-search

